---
sidebar: sidebar
permalink: trident-docker/multiple-instances-docker.html
keywords: deploy, Trident, docker, trident for docker, managed plugin, trident instances, alias
summary: Multiple instances of Trident are needed when you desire to have multiple storage configurations available simultaneously. The key to multiple instances is to give them different names using the --alias option with the containerized plugin, or --volume-driver option when instantiating Trident on the host.
---

= Manage multiple Trident instances
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Multiple instances of Trident are needed when you desire to have multiple storage configurations available simultaneously. The key to multiple instances is to give them different names using the `--alias` option with the containerized plugin, or `--volume-driver` option when instantiating Trident on the host.

== Steps for Docker managed plugin (version 1.13/17.03 or later)

. Launch the first instance specifying an alias and configuration file.
+
----
docker plugin install --grant-all-permissions --alias silver netapp/trident-plugin:21.07 config=silver.json
----
. Launch the second instance, specifying a different alias and configuration file.
+
----
docker plugin install --grant-all-permissions --alias gold netapp/trident-plugin:21.07 config=gold.json
----
. Create volumes specifying the alias as the driver name.
+
For example, for gold volume:
+
----
docker volume create -d gold --name ntapGold
----
+
For example, for silver volume:
+
----
docker volume create -d silver --name ntapSilver
----

== Steps for traditional (version 1.12 or earlier)

. Launch the plugin with an NFS configuration using a custom driver ID:
+
----
sudo trident --volume-driver=netapp-nas --config=/path/to/config-nfs.json
----
. Launch the plugin with an iSCSI configuration using a custom driver ID:
+
----
sudo trident --volume-driver=netapp-san --config=/path/to/config-iscsi.json
----
. Provision Docker volumes for each driver instance:
+
For example, for NFS:
+
----
docker volume create -d netapp-nas --name my_nfs_vol
----
+
For example, for iSCSI:
+
----
docker volume create -d netapp-san --name my_iscsi_vol
----
