---
sidebar: sidebar
permalink: trident-docker/prereqs-docker.html
keywords: deploy, Trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config, nvme/tcp, nvme
summary: You have to install and configure the necessary protocol prerequisites on your host before you can deploy Trident.
---

= Prerequisites for deployment
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You have to install and configure the necessary protocol prerequisites on your host before you can deploy Trident.

== Verify the requirements

* Verify that your deployment meets all of the link:../trident-get-started/requirements.html[requirements].
* Verify that you have a supported version of Docker installed. If your Docker version is out of date, https://docs.docker.com/engine/install/[install or update it^].
+
[source,console]
----
docker --version
----
* Verify that the protocol prerequisites are installed and configured on your host.

=== NFS tools
Install the NFS tools using the commands for your operating system. 

[role="tabbed-block"]
====
.RHEL 8+
--
[source,console]
----
sudo yum install -y nfs-utils
----
--
.Ubuntu
--
[source,console]
----
sudo apt-get install -y nfs-common
----
====
WARNING: Reboot your worker nodes after installing the NFS tools to prevent failure when attaching volumes to containers.

=== iSCSI tools
Install the iSCSI tools using the commands for your operating system.

[role="tabbed-block"]
====
.RHEL 8+
--
. Install the following system packages:
+
[source,console]
----
sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath
----
. Check that iscsi-initiator-utils version is 6.2.0.874-2.el7 or later:
+
[source,console]
----
rpm -q iscsi-initiator-utils
----
. Set scanning to manual:
+
[source,console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. Enable multipathing:
+
[source,console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+
NOTE: Ensure `etc/multipath.conf` contains `find_multipaths no` under `defaults`.

. Ensure that `iscsid` and `multipathd` are running:
+
[source,console]
----
sudo systemctl enable --now iscsid multipathd
----
. Enable and start `iscsi`:
+
[source,console]
----
sudo systemctl enable --now iscsi
----
--

.Ubuntu
--
. Install the following system packages:
+
[source,console]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. Check that open-iscsi version is 2.0.874-5ubuntu2.10 or later (for bionic) or 2.0.874-7.1ubuntu6.1 or later (for focal):
+
[source,console]
----
dpkg -l open-iscsi
----
. Set scanning to manual:
+
[source,console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. Enable multipathing:
+
[source,console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+
NOTE: Ensure `etc/multipath.conf` contains `find_multipaths no` under `defaults`.

. Ensure that `open-iscsi` and `multipath-tools` are enabled and running:
+
[source,console]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----
--
====

== NVMe tools
Install the NVMe tools using the commands for your operating system.

[NOTE]
====
* NVMe requires RHEL 9 or later. 
* If the kernel version of your Kubernetes node is too old or if the NVMe package is not available for your kernel version, you might have to update the kernel version of your node to one with the NVMe package. 
====

[role="tabbed-block"]
====
.RHEL 9
--
[source,console]
----
sudo yum install nvme-cli
sudo yum install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
.Ubuntu
--
[source,console]
----
sudo apt install nvme-cli
sudo apt -y install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
====

== FC tools

Install the FC tools using the commands for your operating system.  

* When using worker nodes that run RHEL/Red Hat Enterprise Linux CoreOS (RHCOS) with FC PVs, specify the `discard` mountOption in the StorageClass to perform inline space reclamation. Refer to https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems[Red Hat documentation^].

[role="tabbed-block"]
====
.RHEL 8+
--
. Install the following system packages:
+
[source,console]
----
sudo yum install -y lsscsi device-mapper-multipath
----
. Enable multipathing:
+
[source,console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+
NOTE: Ensure `etc/multipath.conf` contains `find_multipaths no` under `defaults`.

. Ensure that `multipathd` is running:
+
[source,console]
----
sudo systemctl enable --now multipathd
----
--
.Ubuntu
--
. Install the following system packages:
+
[source,console]
----
sudo apt-get install -y lsscsi sg3-utils multipath-tools scsitools
----
. Enable multipathing:
+
[source,console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+
NOTE: Ensure `etc/multipath.conf` contains `find_multipaths no` under `defaults`.

. Ensure that `multipath-tools` is enabled and running:
+
[source,console]
----
sudo systemctl status multipath-tools
----
====
