---
sidebar: sidebar
permalink: trident-docker/prereqs-docker.html
keywords: deploy, astra trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config
summary: You have to install and configure the necessary protocol prerequisites on your host before you can deploy Astra Trident.
---

= Prerequisites for deployment
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You have to install and configure the necessary protocol prerequisites on your host before you can deploy Astra Trident.

== Verify the requirements

* Verify that your deployment meets all of the link:../trident-get-started/requirements.html[requirements].
* Verify that you have a supported version of Docker installed. If your Docker version is out of date, https://docs.docker.com/engine/install/[install or update it^].
+
----
docker --version
----
* Verify that the protocol prerequisites are installed and configured on your host:

[%header,cols=3*]
|===
|Protocol
|Operating system
|Commands

|NFS
a|RHEL 8+
a|`sudo yum install -y nfs-utils`

|NFS
a|Ubuntu
a|`sudo apt-get install -y nfs-common`

|iSCSI
a|RHEL 8+
a|
. Install the following system packages:
+
`sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath`
. Check that iscsi-initiator-utils version is 6.2.0.874-2.el7 or later:
+
`rpm -q iscsi-initiator-utils`
. Set scanning to manual:
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`
. Enable multipathing:
+
`sudo mpathconf --enable --with_multipathd y --find_multipaths n`
+
NOTE: Ensure `etc/multipath.conf` contains `find_multipaths no` under `defaults`.

. Ensure that `iscsid` and `multipathd` are running:
+
`sudo systemctl enable --now iscsid multipathd`
. Enable and start `iscsi`:
+
`sudo systemctl enable --now iscsi`

|iSCSI
a|Ubuntu
a|
. Install the following system packages:
+
`sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools`
. Check that open-iscsi version is 2.0.874-5ubuntu2.10 or later (for bionic) or 2.0.874-7.1ubuntu6.1 or later (for focal):
+
`dpkg -l open-iscsi`
. Set scanning to manual:
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`
. Enable multipathing:
+
`sudo tee /etc/multipath.conf <<-'EOF'
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart`
+
NOTE: Ensure `etc/multipath.conf` contains `find_multipaths no` under `defaults`.

. Ensure that `open-iscsi` and `multipath-tools` are enabled and running:
+
`sudo systemctl status multipath-tools`
`sudo systemctl enable --now open-iscsi.service`
`sudo systemctl status open-iscsi`
|===
