---
sidebar: sidebar
permalink: trident-docker/upgrade-uninstall-docker.html
keywords: uninstall, astra trident, trident for docker, docker, upgrade trident for docker
summary: You can safely upgrade Astra Trident for Docker without any impact to volumes that are in use. During the upgrade process there will be a brief period where `docker volume` commands directed at the plugin will not succeed, and applications will be unable to mount volumes until the plugin is running again. Under most circumstances, this is a matter of seconds.
---

= Upgrade or uninstall Astra Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You can safely upgrade Astra Trident for Docker without any impact to volumes that are in use. During the upgrade process there will be a brief period where `docker volume` commands directed at the plugin will not succeed, and applications will be unable to mount volumes until the plugin is running again. Under most circumstances, this is a matter of seconds.

== Upgrade

Perform the steps below to upgrade Astra Trident for Docker.

.Steps

. List the existing volumes:
+
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----
. Disable the plugin:
+
----
docker plugin disable -f netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Upgrade the plugin:
+
----
docker plugin upgrade --skip-remote-check --grant-all-permissions netapp:latest netapp/trident-plugin:21.07
----
+
NOTE: The 18.01 release of Astra Trident replaces the nDVP. You should upgrade directly from the `netapp/ndvp-plugin` image to the `netapp/trident-plugin` image.
. Enable the plugin:
+
----
docker plugin enable netapp:latest
----
. Verify that the plugin is enabled:
+
----
docker plugin ls
ID                  NAME                DESCRIPTION                             ENABLED
7067f39a5df5        netapp:latest       Trident - NetApp Docker Volume Plugin   true
----
. Verify that the volumes are visible:
+
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----

IMPORTANT: If you are upgrading from an old version of Astra Trident (pre-20.10) to Astra Trident 20.10 or later, you might run into an error. For more information, refer to link:known-issues-docker.html[Known Issues^]. If you run into the error, you should first disable the plugin, then remove the plugin, and then install the required Astra Trident version by passing an extra config parameter: `docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json`

== Uninstall

Perform the steps below to uninstall Astra Trident for Docker.

.Steps

. Remove any volumes that the plugin created.

. Disable the plugin:
+
----
docker plugin disable netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. Remove the plugin:
+
----
docker plugin rm netapp:latest
----
