---
sidebar: sidebar
permalink: trident-docker/volumes-docker.html
keywords: create volumes, trident, trident for docker, docker, docker volume
summary: To create volumes, use the standard `docker volume` commands with the Trident driver name specified when needed.
---

= Work with volumes
:hardbreaks:
:icons: font
:imagesdir: ../media/

You can easily create, clone, and remove volumes using the standard `docker volume` commands with the Trident driver name specified when needed.

== Create a volume

* Create a volume with a Trident driver using the default name:
+
[source,console]
docker volume create -d netapp --name firstVolume

* Create a volume with a specific Trident instance:
+
[source,console]
docker volume create -d ntap_bronze --name bronzeVolume

NOTE: If you do not specify any link:storage-driver-options.html[options^], the defaults for the driver are used. 

== Upgrade
Perform the steps below to upgrade Trident for Docker.

.Steps

. List the existing volumes:
+
[source,console]
docker volume ls
+
----
DRIVER              VOLUME NAME
netapp:latest       my_volume
----

. Disable the plugin:
+
[source,console]
docker plugin disable -f netapp:latest
+
[source,console]
docker plugin ls
+
----
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----

. Upgrade the plugin:
+
[source,console]
docker plugin upgrade --skip-remote-check --grant-all-permissions netapp:latest netapp/trident-plugin:21.07
+
NOTE: The 18.01 release of Trident replaces the nDVP. You should upgrade directly from the `netapp/ndvp-plugin` image to the `netapp/trident-plugin` image.

. Enable the plugin:
+
[source,console]
docker plugin enable netapp:latest

. Verify that the plugin is enabled:
+
[source,console]
docker plugin ls
+
----
ID                  NAME                DESCRIPTION                             ENABLED
7067f39a5df5        netapp:latest       Trident - NetApp Docker Volume Plugin   true
----

. Verify that the volumes are visible:
+
[source,console]
docker volume ls
+
----
DRIVER              VOLUME NAME
netapp:latest       my_volume
----
IMPORTANT: If you are upgrading from an old version of Trident (pre-20.10) to Trident 20.10 or later, you might run into an error. For more information, see Known Issues. If you run into the error, you should first disable the plugin, then remove the plugin, and then install the required Trident version by passing an extra config parameter: `docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json`

== Uninstall

Perform the steps below to uninstall Trident for Docker.

.Steps

. Remove any volumes that the plugin created.

. Disable the plugin:
+
[source,console]
docker plugin disable netapp:latest
+
[source,console]
docker plugin ls
+
----
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----

. Remove the plugin:
+
[source,console]
docker plugin rm netapp:latest
