---
sidebar: sidebar
permalink: get-help.html
keywords: get help, get support, knowledgebase, discord, phone, web, ticket, contact support, support ticket
summary: NetApp provides support for Trident in a variety of ways. Extensive free self-support options are available 24x7, such as a Discord channel.
---

= Support
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
NetApp provides support for Trident in a variety of ways. Extensive free self-support options are available 24x7, such as knowledgebase (KB) articles and a Discord channel. 

== Trident support lifecycle
Trident provides three levels of support based on your version. Refer to link:https://mysupport.netapp.com/site/info/version-support[NetApp software version support for definitions^].

Full support:: Trident provides full support for twelve months from the release date. 

Limited support:: Trident provides limited support for months 13 - 24 from the release date.

Self-support:: Trident documentation is available for months 25 - 36 from the release date. 

.Trident version support schedule
[cols="1, 1, 1, 1"]
|===
|Version | Full support | Limited support | Self-support

a|link:https://docs.netapp.com/us-en/trident/index.html[24.10^] |October 2025 | October 2026 | October 2027
a|link:https://docs.netapp.com/us-en/trident-2406/index.html[24.06^] |June 2025 | June 2026 | June 2027
a|link:https://docs.netapp.com/us-en/trident-2402/index.html[24.02^] |February 2025 | February 2026 | February 2027
a|link:https://docs.netapp.com/us-en/trident-2310/index.html[23.10^] |October 2024 | October 2025 | October 2026
a|link:https://docs.netapp.com/us-en/trident-2307/index.html[23.07^] |July 2024 | July 2025 | July 2026
a|link:https://docs.netapp.com/us-en/trident-2304/index.html[23.04^] |-- | April 2025 | April 2026
a|link:https://docs.netapp.com/us-en/trident-2301/index.html[23.01^] |-- | January 2025 | January 2026
a|link:https://docs.netapp.com/us-en/trident-2210/index.html[22.10^] |-- | October 2024 | October 2025
a|link:https://docs.netapp.com/us-en/trident-2207/index.html[22.07^] |-- | July 2024 | July 2025
a|link:https://docs.netapp.com/us-en/trident-2204/index.html[22.04^] |-- | -- | April 2025
a|link:https://docs.netapp.com/us-en/trident-2201/index.html[22.01^] |-- | -- | January 2025

|===

== Self-support
For a comprehensive list of troubleshooting articles, Refer to https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Trident_Kubernetes[NetApp Knowledgebase (login required)^].

== Community support
There is a vibrant public community of container users (including Trident developers) on our link:https://discord.gg/NetApp[Discord channel^]. This is a great place to ask general questions about the project and discuss related topics with like-minded peers.

== NetApp technical support
For help with Trident, create a support bundle using `tridentctl logs -a -n trident` and send it to `NetApp Support <Getting Help>`.

== For more information

* link:https://netapp.io/persistent-storage-provisioner-for-kubernetes/[Trident blogs^]
* link:https://cloud.netapp.com/kubernetes-hub[Kubernetes Hub^]
* link:https://netapp.io/[NetApp.io^]