---
sidebar: sidebar
permalink: get-help.html
keywords: get help, get support, knowledgebase, discord, phone, web, ticket, contact support, support ticket
summary: NetApp provides support for Trident in a variety of ways. Extensive free self-support options are available 24x7, such as a Discord channel.
---

= Support
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
NetApp provides support for Astra Trident in a variety of ways. Extensive free self-support options are available 24x7, such as knowledgebase (KB) articles and a Discord channel. 

== Astra Trident support lifecycle
Astra Trident provides three levels of support based on your version. Refer to link:https://mysupport.netapp.com/site/info/version-support[NetApp software version support for definitions^].

Full support:: Astra Trident provides full support for twelve months from the release date. 

Limited support:: Astra Trident provides limited support for months 13 - 24 from the release date.

Self-support:: Astra Trident documentation is available for months 25 - 36 from the release date. 

.Astra Trident version support schedule
[cols="1, 1, 1, 1"]
|===
|Version | Full support | Limited support | Self-support

a|link:https://docs.netapp.com/us-en/trident/index.html[24.02^] |January 2025 | January 2026 | January 2027
a|link:https://docs.netapp.com/us-en/trident-2310/index.html[23.10^] |October 2024 | October 2025 | October 2026
a|link:https://docs.netapp.com/us-en/trident-2307/index.html[23.07^] |July 2024 | July 2025 | July 2026
a|link:https://docs.netapp.com/us-en/trident-2304/index.html[23.04^] |April 2024 | April 2025 | April 2026
a|link:https://docs.netapp.com/us-en/trident-2301/index.html[23.01^] |January 2024 | January 2025 | January 2026
a|link:https://docs.netapp.com/us-en/trident-2210/index.html[22.10^] |-- | October 2024 | October 2025
a|link:https://docs.netapp.com/us-en/trident-2207/index.html[22.07^] |-- | July 2024 | July 2025
a|link:https://docs.netapp.com/us-en/trident-2204/index.html[22.04^] |-- | April 2024 | April 2025
a|link:https://docs.netapp.com/us-en/trident-2201/index.html[22.01^] |-- | January 2024 | January 2025
a|link:https://docs.netapp.com/us-en/trident-2110/index.html[21.10^] |-- | -- | October 2024
a|link:https://docs.netapp.com/us-en/trident-2107/index.html[21.07^] |-- | -- | July 2024
a|link:https://netapp-trident.readthedocs.io/en/stable-v21.04/[21.04^] |-- | -- | April 2024
a|link:https://netapp-trident.readthedocs.io/en/stable-v21.01/[21.01^] |-- | --| January 2024

|===

NOTE: Releases prior to 21.07, redirect to the legacy documentation site.

== Self-support
For a comprehensive list of troubleshooting articles, see the https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Trident_Kubernetes[NetApp Knowledgebase (login required)^]. You can also find information about troubleshooting issues related to Astra https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra[here^].

== Community support
There is a vibrant public community of container users (including Astra Trident developers) on our Astra link:https://discord.gg/NetApp[Discord channel^]. This is a great place to ask general questions about the project and discuss related topics with like-minded peers.

== NetApp technical support
For help with Astra Trident, create a support bundle using `tridentctl logs -a -n trident` and send it to `NetApp Support <Getting Help>`.

== For more information

* link:https://cloud.netapp.com/blog/topic/astra[Astra blogs^]
* link:https://netapp.io/persistent-storage-provisioner-for-kubernetes/[Astra Trident blogs^]
* link:https://cloud.netapp.com/kubernetes-hub[Kubernetes Hub^]
* link:https://netapp.io/[NetApp.io^]