---
sidebar: sidebar
permalink: get-help.html
keywords: get help, get support, knowledgebase, discord, phone, web, ticket, contact support, support ticket
summary: NetApp provides support for Trident in a variety of ways. Extensive free self-support options are available 24x7, such as a Discord channel.
---

= Support
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
NetApp provides support for Astra Trident in a variety of ways. Extensive free self-support options are available 24x7, such as knowledgebase (KB) articles and a Discord channel. 

== Self-support
For a comprehensive list of troubleshooting articles, see the https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Trident_Kubernetes[NetApp Knowledgebase (login required)^]. You can also find information about troubleshooting issues related to Astra https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra[here^].

== Community support
There is a vibrant public community of container users (including Astra Trident developers) on our Astra link:https://discord.gg/NetApp[Discord channel^]. This is a great place to ask general questions about the project and discuss related topics with like-minded peers.

== NetApp technical support
For help with Astra Trident, create a support bundle using `tridentctl logs -a -n trident` and send it to `NetApp Support <Getting Help>`.