---
sidebar: sidebar
permalink: index.html
summary: Trident is a fully supported open source storage provisioner and orchestrator maintained by NetApp.
keywords: netapp, trident, kubernetes, containers, docker, storage provisioning
---

= Trident 21.xx Documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

Trident is a fully supported open source storage provisioner and orchestrator maintained by NetApp.

Trident supports popular container platforms, such as Kubernetes and Docker. In doing so, Trident understands the natural and evolving languages of these platforms and translates requirements expressed or implied through them into an automated and orchestrated response from the infrastructure.

Today, that includes ONTAP (AFF/FAS/Select/Cloud), Element (NetApp HCI/SolidFire), and SANtricity (E/EF-Series) data management software, plus the Azure NetApp Files service in Azure, the Cloud Volumes Service for AWS in Amazon Web Services, and the Cloud Volumes Service for GCP in Google Cloud. This list continues to grow.

NOTE: For information about Trident’s support policy, see https://mysupport.netapp.com/site/info/trident-support[Trident's Release and Support Lifecycle^].

[discrete]
== Find more information
* https://github.com/NetApp/trident[Trident GitHub^]
