sidebar:
  entries:
    - title: Trident documentation
      url: /index.html
    - section: trident-rn
    - section: trident-concepts
    - section: trident-get-started
    - section: trident-deploy-k8s
    - section: trident-backend
    - section: trident-managing-k8s
    - section: trident-reco
    - title: Monitor Trident
      url: /monitor-trident.html
    - title: FAQs
      url: /faq.html
    - title: Troubleshooting
      url: /troubleshooting.html
    - title: Get help
      url: /get-help.html
    - title: Earlier versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal.html

homepage:
  tiles:
    - title: Get started
      #image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Trident requirements
          summary: Learn about the requirements for Trident.
          url: /trident-get-started/requirements.html
        - title: What's new
          summary: Learn what's new with Trident.
          url: /trident-rn/whatsnew.html
        - title: Quick start
          summary: Get started quickly with Trident.
          url: /trident-get-started/quickstart.html
        - title: FAQ
          summary: Read frequently asked questions.
          url: /faq.html
    - title: Deploy Trident
      links:
        - title: Deploy using Trident operator
          summary: Learn how to deploy Trident using the operator.
          url: /trident-deploy-k8s/kubernetes-deploy-operator.html
        - title: Deploy using tridentctl
          summary: Learn how to deploy Trident using tridentctl.
          url: /trident-deploy-k8s/kubernetes-deploy-tridentctl.html
    - title: Demos & tutorials
      links:
        - title: Trident videos
          summary: Watch videos that show how to use Trident.
          url:
    - title: Blogs & community
      links:
        - title: Slack
          summary: Ask questions, exchange ideas, and share best practices.
          url:
        - title: Kubernetes Hub
          summary: A curated collection of blog postings to learn more about Kubernetes and persistent storage.
          url: https://cloud.netapp.com/kubernetes-hub
