---
settings:
  name: Astra Trident
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "trident-rn.html"
  versions:
    - name: Astra Trident
      url: /trident
      version-number: "23.07"
    - name: Astra Trident
      url: /trident-2304
      version-number: "23.04"
    - name: Astra Trident
      url: /trident-2301
      version-number: "23.01"
    - name: Astra Trident
      url: /trident-2210
      version-number: "22.10"
    - name: Astra Trident
      url: /trident-2207
      version-number: "22.07"
sidebar:
  entries:
    - title: Astra Trident docs
      url: /index.html
    - title: Release notes
      entries:
      - title: What's new
        url: /trident-rn.html
      - title: Earlier versions
        url: /earlier-versions.html
    - section: trident-get-started
    - section: trident-install
    - section: trident-use
    - section: trident-managing-k8s    
    - section: trident-docker
    - section: trident-reco
    - title: Knowledge and support
      entries:
      - title: FAQs
        url: /faq.html
      - title: Troubleshooting
        url: /troubleshooting.html
      - title: Get help
        url: /get-help.html
    - section: trident-reference
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: All Astra documentation