sidebar:
  entries:
    - title: Trident documentation
      url: /index.html
    - title: Release notes
      url: /trident-rn.html
    - section: trident-concepts
    - section: trident-get-started
    - section: trident-managing-k8s
    - section: trident-use
    - section: trident-reco
    - title: Monitor Trident
      url: /monitor-trident.html
    - title: FAQs
      url: /faq.html
    - title: Troubleshooting
      url: /troubleshooting.html
    - title: Earlier versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal.html

homepage:
  tiles:
    - title: Get started
      #image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Trident requirements
          url: /trident-get-started/requirements.html
        - title: What's new
          url: trident-rn.html
        - title: Try it out
          url: /trident-get-started/quickstart.html
        - title: FAQ
          url: /faq.html
    - title: Deploy Trident
      links:
        - title: Deploy using Trident operator
          url: /trident-deploy-k8s/kubernetes-deploy-operator.html
        - title: Deploy using tridentctl
          url: /trident-deploy-k8s/kubernetes-deploy-tridentctl.html
    - title: Demos & tutorials
      links:
        - title: Trident videos
          url:
    - title: Blogs & community
      links:
        - title: Slack
          url:
        - title: Kubernetes Hub
          url: https://cloud.netapp.com/kubernetes-hub
