sidebar:
  entries:
    - title: Trident documentation
      url: /index.html
    - title: Release notes
      url: /trident-rn.html
    - section: trident-concepts
    - section: trident-get-started
    - section: trident-managing-k8s
    - section: trident-use
    - section: trident-reco
    - title: Monitor Trident
      url: /monitor-trident.html
    - title: Trident for Docker
      url: /trident-docker.html
    - title: FAQs
      url: /faq.html
    - title: Troubleshooting
      url: /troubleshooting.html
    - section: trident-reference
    - title: Earlier versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal.html

homepage:
  tiles:
    - title: Get started
      #image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Trident requirements
          url: /trident-get-started/requirements.html
        - title: What's new
          url: trident-rn.html
        - title: Try it out
          url: /trident-get-started/quickstart.html
        - title: FAQ
          url: /faq.html
    - title: Deploy Trident
      links:
        - title: Deploy using Trident operator
          url: /trident-get-started/kubernetes-deploy-operator.html
        - title: Deploy using tridentctl
          url: /trident-get-started/kubernetes-deploy-tridentctl.html
        - title: Deploy Trident for Docker
          url: /trident-docker/deploy-docker.html 
    - title: Upgrade Trident
      links:
        - title: Upgrade with Trident operator
          url: /trident-managing-k8s/upgrade-operator.html
        - title: Upgrade with tridentctl
          url: /trident-managing-k8s/upgrade-tridentctl.html
    - title: Use Trident
      links:
        - title: Configure backends
          url: /trident-use/anf.html
        - title: Manage backends
          url: /trident-use/manage-backend.html
    - title: Demos & tutorials
      links:
        - title: Trident videos
          url: https://tv.netapp.com/detail/video/5995831475001/using-trident-with-kubernetes
    - title: Blogs & community
      links:
        - title: Kubernetes Hub
          url: https://cloud.netapp.com/kubernetes-hub
        - title: NetApp.io
          url: https://netapp.io/
        - title: Trident blogs
          url: https://netapp.io/persistent-storage-provisioner-for-kubernetes/
        - title: Slack
          url: https://netapppub.slack.com/
