---
settings:
  name: Astra Trident
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "trident-rn.html"
  versions:
    - name: Astra Trident
      url: /trident
      version-number: "22.07"
    - name: Astra Trident
      url: /trident-2204
      version-number: "22.04"
    - name: Astra Trident
      url: /trident-2201
      version-number: "22.01"
    - name: Astra Trident
      url: /trident-2110
      version-number: "21.10"
sidebar:
  entries:
    - title: Astra Trident docs
      url: /index.html
    - title: Release notes
      url: /trident-rn.html
    - section: trident-concepts
    - section: trident-get-started
    - section: trident-managing-k8s
    - section: trident-use
    - section: trident-docker
    - title: FAQs
      url: /faq.html
    - title: Support
      url: /get-help.html
    - title: Troubleshooting
      url: /troubleshooting.html
    - section: trident-reco
    - section: trident-reference
    - title: Earlier versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal.html
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: All Astra documentation