---
settings:
  name: Trident
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  pdf:
     allow-incremental: false
  rss_page: "trident-rn.html"
  versions:
    - version-number: "25.06"
      url: /trident
    - version-number: "25.02"
      url: /trident-2502  
    - version-number: "24.10"
      url: /trident-2410
    - version-number: "24.06"
      url: /trident-2406 
    - version-number: "24.02"
      url: /trident-2402 
    - version-number: "23.10"
      url: /trident-2310   
    - version-number: "23.07"
      url: /trident-2307      
    - version-number: "23.04"
      url: /trident-2304      
    - version-number: "23.01"
      url: /trident-2301      
    - version-number: "22.10"
      url: /trident-2210      
    - version-number: "22.07"
      url: /trident-2207
                        
sidebar:
  entries:
    - title: Trident docs
      url: /index.html
    - title: Release notes
      entries:
      - title: What's new
        url: /trident-rn.html
      - title: Earlier versions
        url: /earlier-versions.html
      - title: Known issues
        url: /known-issues.html
    - section: trident-get-started
    - section: trident-install
    - section: trident-use
    - section: trident-managing-k8s    
    - section: trident-docker
    - section: trident-reco
    - section: trident-protect
    - title: Blog posts
      url: /blog-posts.html 
    - title: Knowledge and support
      entries:
      - title: FAQs
        url: /faq.html
      - title: Troubleshooting
        url: /troubleshooting.html
      - title: Get help
        url: /get-help.html
    - section: trident-reference
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Trident
  repo: astra-family