---
sidebar: sidebar
permalink: trident-rn/whatsnew.html
keywords: what's new, new features, enhancements
summary: NetApp is continually improving and enhancing its products and services. Here are some of the latest features and functionalities available in Trident.
---

= What's new in Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

NetApp is continually improving and enhancing its products and services. Here are some of the latest features and functionalities available with Trident.

* The 21.01 release of Trident introduced the following key architectural changes to the operator:
** The operator is now cluster scoped. Previous instances of the Trident operator (versions 20.04 through 20.10) were namespace scoped. The advantages of a cluster-scoped operator are as follows:
*** Resource accountability: The operator can now manage resources associated with a Trident installation at the cluster level. As part of installing Trident, the operator creates and maintains several resources by using `ownerReferences`. Maintaining `ownerReferences` on cluster-scoped resources can throw up errors on certain Kubernetes distributors, such as OpenShift. This is mitigated with a cluster-scoped operator. For auto-healing and patching Trident resources, this is an essential requirement.
*** Cleaning up during uninstalls: A complete removal of Trident requires all the associated resources to be deleted. A namespace-scoped operator might experience issues with the removal of cluster-scoped resources (such as, `clusterRole`, `ClusterRoleBinding`, and `PodSecurityPolicy`) and lead to an incomplete clean up. A cluster-scoped operator eliminates this issue.
** `TridentProvisioner` is replaced with `TridentOrchestrator` as the Custom Resource used to install and manage Trident. In addition, a new field is introduced to the `TridentOrchestrator` spec. You can specify the namespace Trident must be installed/upgraded from by using the `spec.namespace` field. See https://github.com/NetApp/trident/blob/stable/v21.01/deploy/crds/tridentorchestrator_cr.yaml[an example here^].
* The 21.01 release of Trident introduced Helm-based installs and upgrades.
