---
sidebar: sidebar
permalink: trident-managing-k8s/downgrade-trident.html
keywords: downgrade, astra trident, methods, operator, tridentctl, helm
summary: You should use the same method to downgrade Astra Trident that you used to install Astra Trident. 
---

= Downgrade Astra Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You might consider downgrading Astra Trident for contingency planning, an immediate fix for bugs observed after an upgrade, dependency issues, or an unsuccessful or incomplete upgrade. You should use the same method to downgrade Astra Trident that you used to install Astra Trident. 

== Important considerations before downgrading
* You should downgrade only to address issues caused by an upgrade.
* You should downgrade to only the immediately preceding version. For example:
** You can downgrade from 23.07 to 23.04. 
** You should not downgrade from 23.07 to 23.01. 
* To move to a version other than the immediately preceding version, you should completely link:../uninstall-trident.html[uninstall Astra Trident]--including all associated CRDs--and perform a new installation to the earlier version. 

== Determine the original installation method
You should use the same method to downgrade Astra Trident that you used to install it. Before downgrading, verify which version you used to originally install Astra Trident. 

. Use `kubectl get pods -n trident` to examine the pods. 
* If there is no operator pod, Astra Trident was installed using `tridentctl`.
* If there is an operator pod, Astra Trident was installed using the Trident operator either manually or using Helm. 
. If there is an operator pod, use `kubectl describe tproc trident` to determine if Astra Trident was installed using Helm. 
* If there is a Helm label, Astra Trident was installed using Helm. 
* If there is no Helm label, Astra Trident was installed manually using the Trident operator. 

== Downgrade a Trident operator installation
You can downgrade a Trident operator installation manually or using Helm.

=== Downgrade a manual installation
You can manually downgrade Astra Trident installed using the Trident operator.

.Steps
. link:uninstall-trident.html[Uninstall Astra Trident^]. 
+
WARNING: Do not delete the CRDs unless you want a fresh Astra Trident installation. For example, if you are moving to any version other than the immediately preceding version. This cannot be undone. 

. Delete the Trident operator using the operator manifest associated with your version of Trident. For example, `\https://github.com/NetApp/trident/tree/stable/_vXX.XX_/deploy/_bundle.yaml_` where `_vXX.XX_` is the version number (for example `v22.10`) and `_bundle.yaml_` is the bundle YAML file name.
. Install the earlier version using the link:../earlier-versions.html[documentation for that release]. 

=== Downgrade a Helm installation
You can downgrade using Helm, with the `helm rollback` command. For example:
----
helm rollback trident [revision #]
----

== Downgrade a `tridentctl` installation

You can downgrade Astra Trident that was installed using `tridentctl`.

.Before you begin
Before beginning the downgrade, take a snapshot of your Kubernetes cluster `etcd`. This enables you to back up the current state of Astra Trident CRDs.

.Steps
. Uninstall Astra Trident with the existing `tridentctl` binary.  In this case, you will uninstall with the 23.04 binary.
+
----
tridentctl version -n trident
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 23.04.0        | 23.04.0        |
+----------------+----------------+

tridentctl uninstall -n trident
INFO Deleted Trident deployment.
INFO Deleted Trident daemonset.
INFO Deleted Trident service.
INFO Deleted Trident secret.
INFO Deleted cluster role binding.
INFO Deleted cluster role.
INFO Deleted service account.
INFO Deleted pod security policy.                  podSecurityPolicy=tridentpods
INFO The uninstaller did not delete Trident's namespace in case it is going to be reused.
INFO Trident uninstallation succeeded.
----
. After this is complete, obtain the Trident binary for the desired version (in this example, 23.01), and use it to install Astra Trident. You can generate custom YAMLs for a link:../trident-get-started/kubernetes-customize-deploy-tridentctl.html[customized installation] if needed.
+
----
cd 23.01/trident-installer/
./tridentctl install -n trident-ns
INFO Created installer service account.            serviceaccount=trident-installer
INFO Created installer cluster role.               clusterrole=trident-installer
INFO Created installer cluster role binding.       clusterrolebinding=trident-installer
INFO Created installer configmap.                  configmap=trident-installer
...
...
INFO Deleted installer cluster role binding.
INFO Deleted installer cluster role.
INFO Deleted installer service account.
----
