---
sidebar: sidebar
permalink: trident-managing-k8s/downgrade-trident.html
keywords: downgrade, astra trident, methods, operator, tridentctl, helm
summary: You should use the same method to downgrade Astra Trident that you used to install Astra Trident. 
---

= Downgrade Astra Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You might consider downgrading Astra Trident for contingency planning, an immediate fix for bugs observed after an upgrade, dependency issues, or an unsuccessful or incomplete upgrade. You should use the same method to downgrade Astra Trident that you used to install Astra Trident. 

== Determine the original installation method
You should use the same method to downgrade Astra Trident that you used to install it. Before downgrading, verify which version you used to originally install Astra Trident. 

. Use `kubectl get pods -n trident` to examine the pods. 
* If there is no operator pod, Astra Trident was installed using `tridentctl`.
* If there is an operator pod, Astra Trident was installed using the Trident operator either manually or using Helm. 
. If there is an operator pod, use `kubectl describe tproc trident` to determine if Astra Trident was installed using Helm. 
* If there is a Helm label, Astra Trident was installed using Helm. 
* If there is no Helm label, Astra Trident was installed manually using the Trident operator. 

// You can consider a downgrade when moving to a Astra Trident release that uses CRDs. Because Astra Trident uses CRDs for maintaining state, all storage entities created (backends, storage classes, PV, and volume snapshots) have associated CRD objects instead of data written into the `trident` PV (used by the earlier installed version of Astra Trident). Newly created PVs, backends, and storage classes are all maintained as CRD objects. 

// Only attempt downgrade for a version of Astra Trident that runs using CRDs (19.07 and later). This ensures operations performed on the current Astra Trident release are visible after the downgrade occurs.

== Downgrade a Trident operator installation
You can downgrade a trident operator installation manually or using Helm. Astra Trident can be downgraded to either:

* A version installed using the cluster-scoped operator (21.01 and later).
* A version installed using the namespace-scoped operator (20.07 - 20.10). For namespace-scoped operator downgrade instructions, refer to the downgrade instructions link:../earlier-versions.html[for your installed version]. 

=== Downgrade a manual installation
You can manually downgrade from any Astra Trident version that uses the cluster-scoped operator to any other cluster-scoped operator version (Astra Trident 21.01 and later).

.Steps
. link:uninstall-trident.html[Uninstall Astra Trident^]. **Do not delete the CRDs unless you want to completely remove an existing installation.**
. The Trident operator can be deleted by using the operator manifest associated with your version of Trident. For example, `\https://github.com/NetApp/trident/tree/stable/_vXX.XX_/deploy/_bundle.yaml_` where `_vXX.XX_` is the version number (for example `v22.10`) and `_bundle.yaml_` is the bundle YAML file name.
. Continue downgrading by installing the desired version of Astra Trident. Follow the documentation for the desired release.

// === Downgrade to namespace-scoped operator

// To downgrade to an Astra Trident release between 20.07 and 20.10, which will be installed using the namespace-scoped operator, refer to the the downgrade instructions for your version. 

// .Steps
// . link:uninstall-trident.html[Uninstall Astra Trident^]. **Do not wipeout the CRDs unless you want to completely remove an existing installation.**
// Make sure the `tridentorchestrator` is deleted.
// +
// ----
// #Check to see if there are any tridentorchestrators present
// kubectl get torc
// NAME        AGE
// trident     20h

// #Looks like there is a tridentorchestrator that needs deleting
// kubectl delete torc trident
// tridentorchestrator.trident.netapp.io "trident" deleted
// ----
// . The Trident operator can be deleted by using the operator manifest associated with your version of Trident. For example, `\https://github.com/NetApp/trident/tree/stable/_vXX.XX_/deploy/_bundle.yaml_` where `_vXX.XX_` is the version number (for example `v22.10`) and `_bundle.yaml_` is the bundle YAML file name.
// . Delete the `tridentorchestrator` CRD.
// +
// ----
// #Check to see if ``tridentorchestrators.trident.netapp.io`` CRD is present and delete it.

// kubectl get crd tridentorchestrators.trident.netapp.io

// NAME                                     CREATED AT
// tridentorchestrators.trident.netapp.io   2021-01-21T21:11:37Z

// kubectl delete crd tridentorchestrators.trident.netapp.io

// customresourcedefinition.apiextensions.k8s.io "tridentorchestrators.trident.netapp.io" deleted
// ----
// Astra Trident has been uninstalled.
// . Continue downgrading by installing the desired version. Follow the documentation for the desired release.

=== Downgrade a Helm installation
You can easily downgrade using Helm, with the `helm rollback` command. For example:
----
helm rollback trident [revision #]
----

== Downgrade a `tridentctl` installation

You can downgrade Astra Trident that was installed using `tridentctl`.

.Before you begin
Before beginning the downgrade, take a snapshot of your Kubernetes cluster `etcd`. This enables you to back up the current state of Astra Trident CRDs.

.Steps
. Uninstall Astra Trident with the existing `tridentctl` binary.  In this case, you will uninstall with the 23.04 binary.
+
----
tridentctl version -n trident
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 23.04.0        | 23.04.0        |
+----------------+----------------+

tridentctl uninstall -n trident
INFO Deleted Trident deployment.
INFO Deleted Trident daemonset.
INFO Deleted Trident service.
INFO Deleted Trident secret.
INFO Deleted cluster role binding.
INFO Deleted cluster role.
INFO Deleted service account.
INFO Deleted pod security policy.                  podSecurityPolicy=tridentpods
INFO The uninstaller did not delete Trident's namespace in case it is going to be reused.
INFO Trident uninstallation succeeded.
----
. After this is complete, obtain the Trident binary for the desired version (in this example, 23.01), and use it to install Astra Trident. You can generate custom YAMLs for a link:../trident-get-started/kubernetes-customize-deploy-tridentctl.html[customized installation] if needed.
+
----
cd 23.01/trident-installer/
./tridentctl install -n trident-ns
INFO Created installer service account.            serviceaccount=trident-installer
INFO Created installer cluster role.               clusterrole=trident-installer
INFO Created installer cluster role binding.       clusterrolebinding=trident-installer
INFO Created installer configmap.                  configmap=trident-installer
...
...
INFO Deleted installer cluster role binding.
INFO Deleted installer cluster role.
INFO Deleted installer service account.
----
