---
sidebar: sidebar
permalink: trident-managing-k8s/downgrade-trident.html
keywords: downgrade, trident, methods, operator, tridentctl, helm
summary: Learn about the steps involved in downgrading to an earlier version of Trident.
---

= Downgrade Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn about the steps involved in downgrading to an earlier version of Trident. You might consider downgrading for various reasons, such as the following:
* Contingency planning
* Immediate fix for bugs observed as a result of an upgrade
* Dependency issues, unsuccessful and incomplete upgrades

== When to downgrade

You should consider a downgrade when moving to a Trident release that uses CRDs. Because Trident now uses CRDs for maintaining state, all storage entities created (backends, storage classes, PV, and volume snapshots) have associated CRD objects instead of data written into the Trident PV (used by the earlier installed version of Trident). Newly created PVs, backends, and storage classes are all maintained as CRD objects. If you need to downgrade, this should only be attempted for a version of Trident that runs using CRDs (19.07 and above). This is to ensure that all the operations performed on the current Trident release are visible after the downgrade occurs.

== When not to downgrade

You should not downgrade to a release of Trident that uses `etcd` to maintain state (19.04 and earlier). All operations performed with the current Trident release are not reflected after the downgrade. Newly created PVs are not usable when moving back to an earlier version. Changes made to objects such as backends, PVs, storage classes, and volume snapshots (created/updated/deleted) are not visible to Trident when moving back to an earlier version. Going back to an earlier version does not disrupt access for PVs that were already created by using the older release, unless they have been upgraded.

== Overview of downgrade process



== Find more information
* link:upgrade-operator.html[Upgrade by using the Trident operator^]
* link:upgrade-tridentctl.html[Upgrade by using `tridentctl`]
