---
sidebar: sidebar
permalink: trident-managing-k8s/uninstall-trident.html
keywords: uninstall, astra trident, methods, operator, tridentctl, helm, downgrade, obliviate, crds, wipeout
summary: You should use the same method to uninstall Astra Trident that you used to install Astra Trident. 
---

= Uninstall Astra Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You should use the same method to uninstall Astra Trident that you used to install Astra Trident. 

== Determine the original installation method
You should use the same method to uninstall Astra Trident that you used to install it. Before uninstalling, verify which version you used to originally install Astra Trident. 

. Use `kubectl get pods -n trident` to examine the pods. 
* If there is no operator pod, Astra Trident was installed using `tridentctl`.
* If there is an operator pod, Astra Trident was installed using the Trident operator either manually or using Helm. 
. If there is an operator pod, use `kubectl describe tproc trident` to determine if Astra Trident was installed using Helm. 
* If there is a Helm label, Astra Trident was installed using Helm. 
* If there is no Helm label, Astra Trident was installed manually using the Trident operator. 

== Uninstall a Trident operator installation
You can uninstall a trident operator installation manually or using Helm. 

=== Uninstall manual installation
If you installed Astra Trident by using the operator, you can uninstall it by doing one of the following:

* **Edit `TridentOrchestrator` to set the uninstall flag:** You can edit `TridentOrchestrator` and set `spec.uninstall=true`. 
** Edit the `TridentOrchestrator` CR and set the `uninstall` flag as shown below:
+
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
** When the `uninstall` flag is set to `true`, the Trident operator uninstalls Trident, but does not remove the TridentOrchestrator itself. You should clean up the TridentOrchestrator and create a new one if you want to
install Trident again.

* **Delete `TridentOrchestrator`:** By removing the `TridentOrchestrator` CR that was used to deploy Astra Trident, you instruct the operator to uninstall Trident. 
** The operator processes the removal of `TridentOrchestrator` and proceeds to remove the Astra Trident deployment and daemonset, deleting the Trident pods it had created as part of the installation.
** To uninstall Astra Trident and completely remove Astra Trident (including the CRDs it creates), edit `TridentOrchestrator` to pass the `wipeout` option. Subsequent installations will be treated as new installations. 
+
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"wipeout":["crds"],"uninstall":true}}'
----
+
WARNING: This cannot be undone. Do not wipe out the CRDs unless you want a fresh Astra Trident installation. For example, if you are moving to version other than the immediately preceding version.

=== Uninstall Helm installation

If you installed Astra Trident by using Helm, you can uninstall it by using `helm uninstall`.

----
#List the Helm release corresponding to the Astra Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----

== Uninstall a `tridentctl` installation

Use the `uninstall` command in `tridentctl` to remove all of the resources associated with Astra Trident except for the CRDs and related objects. This makes is simple to run the installer again to update to a more recent version.

----
./tridentctl uninstall -n <namespace>
----

To perform a complete removal of Astra Trident, you should remove the finalizers for the CRDs created by Astra Trident and delete the CRDs.
