---
sidebar: sidebar
permalink: trident-managing-k8s/uninstall-trident.html
keywords: uninstall, trident, methods, operator, tridentctl, helm
summary: Depending on how Trident is installed, there are multiple options to uninstall Trident.
---

= Uninstall Astra Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

Depending on how Trident is installed, there are multiple options to uninstall Trident.

== Uninstall by using Helm

If you installed Trident by using Helm, you can uninstall it by using `helm uninstall`.

[source,console]
----
#List the Helm release corresponding to the Trident install.
$ helm ls -n trident
NAME   	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                          	APP VERSION
trident	trident  	1       	2021-04-20 00:26:42.417764794 +0000 UTC	deployed	trident-operator-21.04.0  	21.04.0

#Uninstall Helm release to remove Trident
$ helm uninstall trident -n trident
release "trident" uninstalled
----

== Uninstall by using the Trident operator

If you installed Trident by using the operator, you can uninstall Trident by doing one of the following:

* **Edit the TridentOrchestrator to set the uninstall flag:** You can edit the TridentOrchestrator and set `spec.uninstall=true` to uninstall Trident.
* **Delete the TridentOrchestrator:** By removing the `TridentOrchestrator` CR that was used to deploy Trident, you instruct the operator to uninstall Trident. The operator processes the removal of the TridentOrchestrator and proceeds to remove the Trident deployment and daemonset, deleting the Trident pods it had created as part of the installation. Edit the `TridentOrchestrator` CR and set the `uninstall` flag as shown below:

----
$  kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----

When the `uninstall` flag is set to `true`, the Trident operator uninstalls Trident, but does not remove the TridentOrchestrator itself. You should clean up the TridentOrchestrator and create a new one if you want to
install Trident again.

To completely remove Trident (including the CRDs it creates) and effectively wipe the slate clean, you can edit `TridentOrchestrator` to pass the `wipeout` option. See the following example:

----
$ kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"wipeout":["crds"],"uninstall":true}}'
----

This uninstalls Trident completely and clears all metadata related to the backends and volumes it manages. Subsequent installations are treated as fresh installations.

WARNING: You should only consider wiping out the CRDs when performing a complete uninstallation. This cannot be undone. **Do not wipe out the CRDs unless you are looking to start over and create a fresh Trident installation**.

== Uninstall by using `tridentctl`

Run the uninstall command in `tridentctl` as follows to removes all of the resources associated with Trident except for the CRDs and related objects, thereby making it easy to run the installer again to update to a more recent version.

----
./tridentctl uninstall -n <namespace>
----

To perform a complete removal of Trident, you should remove the finalizers for the CRDs created by Trident and delete the CRDs.

== Find more information
* link:upgrade-operator.html[Upgrade by using the Trident operator^]
* link:upgrade-tridentctl.html[Upgrade by using `tridentctl`]
