---
sidebar: sidebar
permalink: trident-managing-k8s/upgrade-tridentctl.html
keywords: upgrade, trident, methods, operator, tridentctl, helm
summary: You can easily upgrade an existing Trident installation by using `tridentctl`.
---

= Upgrade Trident by using `tridentctl`
:hardbreaks:
:icons: font
:imagesdir: ../media/

You can easily upgrade an existing Trident installation by using `tridentctl`.

.What you'll need

To upgrade by using the Trident operator, the following conditions should be met:

* You should have a CSI-based Trident installation. To check if you are running CSI Trident, examine the pods in your Trident namespace. If they follow the `trident-csi-*` naming pattenr, you are running CSI Trident.
* You should have a CRD-based Trident installation. This represents all Trident releases from 19.07 and later. If you have a CSI-based installation, you most likely have a CRD-based installation.
* If you have uninstalled CSI Trident and the metadata from the installation persists, you can upgrade by using the operator.
* Only one Trident installation should exist across all the namespaces in a given Kubernetes cluster.
* You should be using a Kubernetes cluster that runs version 1.14 and later.
* If alpha snapshot CRDs are present, you should remove them with `tridentctl obliviate alpha-snapshot-crd`. This deletes the CRDs for the alpha snapshot spec. For existing snapshots that should be deleted/migrated, see https://netapp.io/2020/01/30/alpha-to-beta-snapshots/[this blog^].

WARNING: When upgrading Trident by using the operator on OpenShift Container Platform, you should upgrade to Trident 21.01.1 or later. The Trident operator released with 21.01.0 contains a known issue that has been fixed in 21.01.1. For more details, see the https://github.com/NetApp/trident/issues/517[issue details on GitHub^].

== Determine the Trident version to upgrade to

* You can upgrade to the `YY.MM` release from the ``YY-1.MM`` release and any in-between releases. For example, you can perform a direct upgrade to 20.07 from 19.07 and later (including dot releases, such as 19.07.1).
* If you have an earlier release, you should perform a multistep upgrade. This requires you to first upgrade to the most recent release that fits your four-release window. For example, if you are running 18.07 and want to upgrade to the 20.07 release, then follow the multistep upgrade process as given below:
** First upgrade from 18.07 to 19.07. See the documentation of the respective release to obtain specific instructions for upgrading.
** Now upgrade from 19.07 to 20.07.

IMPORTANT: All upgrades for versions 19.04 and earlier require the migration of Trident's metadata from it's own `etcd` to CRD objects. Ensure that you check the documentation of the release to understand how the upgrade works.

WARNING: If you are running Kubernetes 1.17 or later, and are looking to upgrade to 20.07.1 or later, it is important you provide ``parameter.fsType`` in `StorageClasses` used by Trident. You can delete and re-create `StorageClasses` without disrupting pre-existing volumes. This is a **requirement** for enforcing https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[security contexts] for SAN volumes. The https://github.com/NetApp/trident/tree/master/trident-installer/sample-input[sample input^] directory contains examples, such as https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-basic.yaml.templ[`storage-class-basic.yaml.templ`^] and https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-bronze-default.yaml[`storage-class-bronze-default.yaml`^].
For more information, see <insert link to known issues>.

== Which upgrade path should I choose?

You can upgrade by using one of the following paths:

* Using the Trident operator.
* Using `tridentctl`.

You can use the Trident operator to upgrade if the following conditions are met:

* You are running CSI Trident (19.07 and later).
* You have a CRD-based Trident release (19.07 and later).
* You are **not** performing a customized install (using custom YAMLs).

WARNING: Do not use the operator to upgrade Trident if you are using an `etcd`-based Trident release (19.04 or earlier).

If you do not want to use the operator or you have a customized install that cannot be supported by the operator, you can upgrade by using `tridentctl`. This is the preferred method of upgrades for Trident releases 19.04 and earlier.

== Find more information
* https://netapp.io/2020/01/30/alpha-to-beta-snapshots/[Things to know before upgrading Kubernetes clusters for Trident 20.01+ and K8s 1.17+]
