---
sidebar: sidebar
permalink: trident-managing-k8s/upgrade-trident.html
keywords: upgrade, trident, methods, operator, tridentctl, helm
summary: Trident follows a quarterly release cadence, delivering four major releases every calendar
year. Each new release builds on top of the previous releases, providing new
features and performance enhancements as well as bug fixes and improvements. You are encouraged to upgrade Trident at least once a year to take advantage of the new features in Trident.
---

= Upgrade Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

Trident follows a quarterly release cadence, delivering four major releases every calendar
year. Each new release builds on top of the previous releases, providing new
features and performance enhancements as well as bug fixes and improvements. You are encouraged to upgrade Trident at least once a year to take advantage of the new features in Trident.

NOTE:  Upgrading to a Trident release that is five releases ahead will require you to perform a multistep upgrade.

== Determine the Trident version to upgrade to

* You can upgrade to the `YY.MM` release from the ``YY-1.MM`` release and any in-between releases. For example, you can perform a direct upgrade to 20.07 from 19.07 and later (including dot releases, such as 19.07.1).
* If you have an earlier release, you should perform a multistep upgrade. This requires you to first upgrade to the most recent release that fits your four-release window. For example, if you are running 18.07 and want to upgrade to the 20.07 release, then follow the multistep upgrade process as given below:
** First upgrade from 18.07 to 19.07. See the documentation of the respective release to obtain specific instructions for upgrading.
** Now upgrade from 19.07 to 20.07.

IMPORTANT: All upgrades for versions 19.04 and earlier require the migration of Trident's metadata from it's own `etcd` to CRD objects. Ensure that you check the documentation of the release to understand how the upgrade works.

WARNING: If you are running Kubernetes 1.17 or later, and are looking to upgrade to 20.07.1 or later, it is important you provide ``parameter.fsType`` in `StorageClasses` used by Trident. You can delete and re-create `StorageClasses` without disrupting pre-existing volumes. This is a **requirement** for enforcing https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[security contexts] for SAN volumes. The https://github.com/NetApp/trident/tree/master/trident-installer/sample-input[sample input^] directory contains examples, such as https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-basic.yaml.templ[`storage-class-basic.yaml.templ`^] and https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-bronze-default.yaml[`storage-class-bronze-default.yaml`^].
For more information, see <insert link to known issues>.

== Which upgrade path should I choose?

You can upgrade by using one of the following paths:

* Using the Trident operator.
* Using `tridentctl`.

You can use the Trident operator to upgrade if the following conditions are met:

* You are running CSI Trident (19.07 and later).
* You have a CRD-based Trident release (19.07 and later).
* You are **not** performing a customized install (using custom YAMLs).

WARNING: Do not use the operator to upgrade Trident if you are using an `etcd`-based Trident release (19.04 or earlier).

For a complete list of prerequisites, click :ref:`here <operator-prereq>`.

If you do not want to use the operator or you have a customized install that cannot be supported by the operator, you can upgrade by using `tridentctl`. This is the preferred method of upgrades for Trident releases 19.04 and earlier.
