---
sidebar: sidebar
permalink: trident-managing-k8s/upgrade-tridentctl.html
keywords: upgrade, trident, methods, operator, tridentctl, helm
summary: You can easily upgrade an existing Trident installation by using `tridentctl`.
---

= Upgrade Trident by using `tridentctl`
:hardbreaks:
:icons: font
:imagesdir: ../media/

You can easily upgrade an existing Trident installation by using `tridentctl`.

.Considerations

When upgrading to the latest release of Trident, consider the following:

* Starting with Trident 20.01, only the beta release of https://kubernetes.io/docs/concepts/storage/volume-snapshots/[volume snapshots^] is supported. Kubernetes administrators should take care to safely back up or convert the alpha snapshot objects to beta to retain the legacy alpha snapshots.
* The beta release of volume snapshots introduces a modified set of CRDs and a snapshot controller, both of which should be set up before installing Trident.

NOTE: https://netapp.io/2020/01/30/alpha-to-beta-snapshots/[This blog^] discusses the steps involved in migrating alpha volume snapshots to the beta format.

.About this task

When you uninstall Trident, the PVC and PV used by the Trident deployment are not deleted. Uninstalling Trident and reinstalling it acts as an upgrade.

Upgrading Trident from any release earlier than 19.07 by running a `tridentctl install` command does the following:

* Initiates a one-time process that copies the metadata stored in the Trident PV into CRD objects.
* Provides periodic updates throughout the upgrade with respect to the migration of Trident's metadata.

PVs that have already been provisioned remain available while Trident is offline, and Trident provisions volumes for any PVCs that are created in the interim when it is back online.

IMPORTANT: When upgrading Trident, do not interrupt the upgrade process. Ensure that the installer runs to completion.

== Upgrade Trident on Kubernetes 1.14 and later

For Kubernetes 1.14 and later, perform an uninstall followed by a reinstall to upgrade to the latest version of Trident.

WARNING: If you are running Kubernetes 1.17 or later, and are looking to upgrade to Trident 20.07.1 or later, you should provide `parameter.fsType` in StorageClasses used by Trident. This is a *requirement* for enforcing https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[Security
Contexts^] for SAN volumes. The https://github.com/NetApp/trident/tree/master/trident-installer/sample-input[sample-input^] directory contains examples, such as https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-basic.yaml.templ[storage-class-basic.yaml.templ^], and https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-bronze-default.yaml[storage-class-bronze-default.yaml^]. For more information, see the link:../trident-rn/known-issues.html[Known Issues^].

== Upgrade Trident on Kubernetes 1.13

On Kubernetes 1.13, you can upgrade Trident as follows:

* Install Trident in the desired namespace by executing the `tridentctl install` command with the `--csi` flag. This configures Trident to function as an enhanced CSI provisioner. This requires enabling some link:../trident-get-started/requirements.html[feature gates^].
* If you cannot enable the feature gates required by Trident, install Trident without the `--csi` flag. This configures Trident to work in its traditional format without using the CSI specification.

== Next steps after upgrade

To make use of the rich set of features that are available in newer Trident releases (such as, On-Demand Volume Snapshots), you can upgrade the volumes by using the `tridentctl upgrade` command.

If there are legacy volumes, you should upgrade them from a NFS/iSCSI type to the CSI type to be able to use the complete set of new features in Trident. A legacy PV that has been provisioned by Trident supports the traditional set of features.

Consider the following when deciding to upgrade volumes to the CSI type:

* You might not need to upgrade all the volumes. Previously created volumes will continue to be accessible and function normally.
* A PV can be mounted as part of a deployment/StatefulSet when upgrading. It is not required to bring down the deployment/StatefulSet.
* You *cannot* attach a PV to a standalone pod when upgrading. You should shut down the pod before upgrading the volume.
* You can upgrade only a volume that is bound to a PVC. Volumes that are not bound to PVCs should be removed and imported before upgrading.

Before proceeding, you should determine if your Trident deployment is capable of upgrading legacy volumes. The version of Trident installed should be at least 19.07 and Trident should be configured as a CSI provisioner. This can be confirmed by doing a `kubectl get pods -n <trident-namespace>`. The presence of a `trident-csi-<generated-id>` indicates that it is running as a CSI provisioner and supports upgrading legacy volumes. See the following code sample:

[source,console]
----
$ tridentctl version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 19.10.0        | 19.10.0        |
+----------------+----------------+

$ kubectl get pods -n <trident-namespace>
NAME                          READY   STATUS    RESTARTS   AGE
trident-csi-426nx             2/2     Running   0          20m
trident-csi-b5cf8fd7c-fnq24   4/4     Running   0          20m
----

=== Volume upgrade example

Here is an example that shows how a volume upgrade is performed.

. Run `kubectl get pv` to list the PVs.
+
[source,console]
----
$ kubectl get pv
NAME                         CAPACITY     ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                  STORAGECLASS    REASON   AGE
default-pvc-1-a8475          1073741824   RWO            Delete           Bound    default/pvc-1          standard                 19h
default-pvc-2-a8486          1073741824   RWO            Delete           Bound    default/pvc-2          standard                 19h
default-pvc-3-a849e          1073741824   RWO            Delete           Bound    default/pvc-3          standard                 19h
default-pvc-4-a84de          1073741824   RWO            Delete           Bound    default/pvc-4          standard                 19h
trident                      2Gi          RWO            Retain           Bound    trident/trident                                 19h
----
+
There are currently four PVs that have been created by Trident 19.04, using the `netapp.io/trident` provisioner.
. Run `kubectl describe pv` to get the details of the PV.
+
[source,console]
----
$ kubectl describe pv default-pvc-2-a8486

Name:            default-pvc-2-a8486
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: netapp.io/trident
                 volume.beta.kubernetes.io/storage-class: standard
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    standard
Status:          Bound
Claim:           default/pvc-2
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        1073741824
Node Affinity:   <none>
Message:
Source:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    10.xx.xx.xx
    Path:      /trid_1907_alpha_default_pvc_2_a8486
    ReadOnly:  false
----
+
The PV was created by using the `netapp.io/trident` provisioner and is of the type NFS. To support all the new features provided by Trident, this PV should be upgraded to the CSI type.
. Run the `tridenctl upgrade volume <name-of-trident-volume>` command to upgrade a legacy Trident volume to the CSI spec.
+
[source,console]
----
$ ./tridentctl get volumes -n trident
+---------------------+---------+---------------+----------+--------------------------------------+--------+---------+
|            NAME     |  SIZE   | STORAGE CLASS | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
+---------------------+---------+---------------+----------+--------------------------------------+--------+---------+
| default-pvc-2-a8486 | 1.0 GiB | standard      | file     | c5a6f6a4-b052-423b-80d4-8fb491a14a22 | online | true    |
| default-pvc-3-a849e | 1.0 GiB | standard      | file     | c5a6f6a4-b052-423b-80d4-8fb491a14a22 | online | true    |
| default-pvc-1-a8475 | 1.0 GiB | standard      | file     | c5a6f6a4-b052-423b-80d4-8fb491a14a22 | online | true    |
| default-pvc-4-a84de | 1.0 GiB | standard      | file     | c5a6f6a4-b052-423b-80d4-8fb491a14a22 | online | true    |
+---------------------+---------+---------------+----------+--------------------------------------+--------+---------+

$ ./tridentctl upgrade volume default-pvc-2-a8486 -n trident
+---------------------+---------+---------------+----------+--------------------------------------+--------+---------+
|            NAME     |  SIZE   | STORAGE CLASS | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
+---------------------+---------+---------------+----------+--------------------------------------+--------+---------+
| default-pvc-2-a8486 | 1.0 GiB | standard      | file     | c5a6f6a4-b052-423b-80d4-8fb491a14a22 | online | true    |
+---------------------+---------+---------------+----------+--------------------------------------+--------+---------+
----
. Run a `kubectl describe pv` to verify that the volume is a CSI volume.
+
[source,console]
----
$ kubectl describe pv default-pvc-2-a8486
Name:            default-pvc-2-a8486
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: csi.trident.netapp.io
                 volume.beta.kubernetes.io/storage-class: standard
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    standard
Status:          Bound
Claim:           default/pvc-2
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        1073741824
Node Affinity:   <none>
Message:
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            csi.trident.netapp.io
    VolumeHandle:      default-pvc-2-a8486
    ReadOnly:          false
    VolumeAttributes:      backendUUID=c5a6f6a4-b052-423b-80d4-8fb491a14a22
                           internalName=trid_1907_alpha_default_pvc_2_a8486
                           name=default-pvc-2-a8486
                           protocol=file
Events:                <none>
----
+
In this manner, you can upgrade volumes of the NFS/iSCSI type that were created by Trident to the CSI type, on a per-volume basis.

== Find more information
* link:upgrade-operator.html[Upgrade by using the Trident operator^]
