---
sidebar: sidebar
permalink: trident-managing-k8s/upgrade-operator-overview.html
keywords: upgrade, trident, operator, helm, controller, daemonset, node pods
summary: Before using the Trident operator to upgrade Astra Trident, you should understand the background processes that occur during upgrade. This includes changes to the Trident controller, controller and node Pods, and node DaemonSet.
---

= Understand the operator upgrade workflow
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Before using the Trident operator to upgrade Astra Trident, you should understand the background processes that occur during upgrade. This includes changes to the Trident controller, controller Pod and node Pods, and node DaemonSet.

== Trident operator upgrade handling workflow
One of the many link:../trident-get-started/kubernetes-deploy.html[benefits of using the Trident operator] to install and upgrade Astra Trident is the automatic handling of Kubernetes objects. 

Mention the high-level steps performed by the Trident Operator when upgrading Trident

Trident Controller Deployment and Node Daemonset are deleted.
New Trident Controller Deployment and Node Daemonset are created.
As the Controller Pod and Node Pods are terminated, new versions take their place.
If a certain Node is not updated, it does not stop the rest from being updated
Only Nodes with a running Trident node pod can mount volumes.
Existing volume mounts, I/O, etc are unaffected during install/upgrade.
Workflow:

Trident Admin: Upgrade Trident Operator to version N+1
Operator: Detects Trident version N is installed
Operator: Updates all K8s objects such as CRDs, RBAC, Trident SVC, etc
Operator: Deletes Trident Controller Deployment N
Operator: Creates new Trident Controller Deployment N + 1
Kubernetes: creates Trident controller pod N+1
Operator: Deletes Trident Node Daemonset N (does not wait for Node pod termination)
Operator: Creates Trident node Daemonset N+1
Kubernetes: creates Trident node pods on nodes not running Trident Node Pod N, ensuring only a single Trident Node Pod of any version on a node
