---
sidebar: sidebar
permalink: trident-use/anf-prep.html
keywords: trident backend, azure netapp files, smb volumes, smb, windows, active directory, csi proxy
summary: Before you can configure your ANF backend, you need to ensure the following requirements are met. 
---

= Prepare to configure an Azure NetApp Files backend
:hardbreaks:
:icons: font
:imagesdir: ../media/


Before you can configure your ANF backend, you need to ensure the following requirements are met. 

If you are using Azure NetApp Files for the first time or in a new location, some initial configuration is required. 

* To set up Azure NetApp files and create an NFS volume, refer to https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-quickstart-set-up-account-create-volumes[Azure: Set up Azure NetApp Files and create an NFS volume^].

* To configure Azure NetApp Files and add an SMB volume, refer to: https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-create-volumes-smb[Azure: Create an SMB volume for Azure NetApp Files^]. 


== Requirements 

To configure and use an https://azure.microsoft.com/en-us/services/netapp/[Azure NetApp Files^] backend, you need the following:

* `subscriptionID` from an Azure subscription with Azure NetApp Files enabled.
* `tenantID`, `clientID`, and `clientSecret` from an link:https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[App Registration^] in Azure Active Directory with sufficient permissions to the Azure NetApp Files service. The App Registration should use the `Owner` or `Contributor` role predefined by Azure.
+
TIP: To learn more about Azure built-in roles, refer to the link:https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles[Azure documentation^].

* The Azure `location` that contains at least one link:https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-delegate-subnet[delegated subnet^]. As of Trident 22.01, the `location` parameter is a required field at the top level of the backend configuration file. Location values specified in virtual pools are ignored.

== Additional requirements for SMB volumes

* A Kubernetes cluster with a Linux controller node and at least one Windows worker node running Windows Server 2019. Astra Trident supports SMB volumes mounted to pods running on Windows nodes only.

* At least one Astra Trident secret containing your Active Directory credentials so ANF can authenticate to Active Directory. To generate secret `smbcreds`:
+
[source, cli]
----
kubectl create secret generic smbcreds --from-literal username=user --from-literal password='pw'
----

* A CSI proxy configured as a Windows service. To configure a `csi-proxy`, refer to link:https://github.com/kubernetes-csi/csi-proxy[GitHub: CSI Proxy^] or link:https://github.com/Azure/aks-engine/blob/master/docs/topics/csi-proxy-windows.md[GitHub: CSI Proxy for Windows^] for Kubernetes nodes running on Windows. 