---
sidebar: sidebar
permalink: trident-use/anf-prep.html
keywords: trident backend, azure netapp files, smbvolumes, smb, windows, active directory, csi proxy
summary: Before you can configure your Azure NetApp Files backend, you need to ensure the following requirements are met.
---

= Prepare to configure an Azure NetApp Files backend
:hardbreaks:
:icons: font
:imagesdir: ../media/


Before you can configure your Azure NetApp Files backend, you need to ensure the following requirements are met.

If you are using Azure NetApp Files for the first time or in a new location, some initial configuration is required.

* To set up Azure NetApp files and create an NFS volume, refer to https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-quickstart-set-up-account-create-volumes[Azure: Set up Azure NetApp Files and create an NFS volume^].

* To configure Azure NetApp Files and add an SMB volume, refer to: https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-create-volumes-smb[Azure: Create an SMB volume for Azure NetApp Files^].


== Requirements

To configure and use an https://azure.microsoft.com/en-us/services/netapp/[Azure NetApp Files^] backend, you need the following:

* `subscriptionID` from an Azure subscription with Azure NetApp Files enabled.
* `tenantID`, `clientID`, and `clientSecret` from an link:https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[App Registration^] in Azure Active Directory with sufficient permissions to the Azure NetApp Files service. The App Registration should use either:

**  The Owner or Contributor role link:https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles[predefined by Azure^]

** A link:https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles-portal[custom Contributor role] at the subscription level (`assignableScopes`) with the following permissions that are limited to only what Astra Trident requires. After creating the custom role, link:https://learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal[assign the role using the Azure portal^].
+
[source,JSON]
----
{
    "id": "/subscriptions/<subscription-id>/providers/Microsoft.Authorization/roleDefinitions/<role-definition-id>",
    "properties": {
        "roleName": "custom-role-with-limited-perms",
        "description": "custom role providing limited permissions",
        "assignableScopes": [
            "/subscriptions/<subscription-id>"
        ],
        "permissions": [
            {
                "actions": [
                    "Microsoft.NetApp/netAppAccounts/capacityPools/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/write",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/write",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/delete",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/write",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/snapshots/delete",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/subvolumes/read",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/subvolumes/write",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/subvolumes/delete",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/subvolumes/GetMetadata/action",
                    "Microsoft.NetApp/netAppAccounts/capacityPools/volumes/MountTargets/read",
                    "Microsoft.Network/virtualNetworks/read",
                    "Microsoft.Network/virtualNetworks/subnets/read",
                    "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/read",
                    "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/write",
                    "Microsoft.Features/featureProviders/subscriptionFeatureRegistrations/delete",
                    "Microsoft.Features/features/read",
                    "Microsoft.Features/operations/read",
                    "Microsoft.Features/providers/features/read",
                    "Microsoft.Features/providers/features/register/action",
                    "Microsoft.Features/providers/features/unregister/action",
                    "Microsoft.Features/subscriptionFeatureRegistrations/read"
                ],
                "notActions": [],
                "dataActions": [],
                "notDataActions": []
            }
        ]
    }
}
----

* The Azure `location` that contains at least one link:https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-delegate-subnet[delegated subnet^]. As of Trident 22.01, the `location` parameter is a required field at the top level of the backend configuration file. Location values specified in virtual pools are ignored.

== Additional requirements for SMB volumes

* A Kubernetes cluster with a Linux controller node and at least one Windows worker node running Windows Server 2019. Astra Trident supports SMB volumes mounted to pods running on Windows nodes only.

* At least one Astra Trident secret containing your Active Directory credentials so Azure NetApp Files can authenticate to Active Directory. To generate secret `smbcreds`:
+
----
kubectl create secret generic smbcreds --from-literal username=user --from-literal password='pw'
----

* A CSI proxy configured as a Windows service. To configure a `csi-proxy`, refer to link:https://github.com/kubernetes-csi/csi-proxy[GitHub: CSI Proxy^] or link:https://github.com/Azure/aks-engine/blob/master/docs/topics/csi-proxy-windows.md[GitHub: CSI Proxy for Windows^] for Kubernetes nodes running on Windows.

== Additional requirements for NFS Subvolumes

* A parent Azure NetApp Files volume. This volume is created in the desired subscription, VNet, and Azure location.

A parent volume can be created using the ANF volume create API, as shown below.

[source,SHELL]
----
#Login to your azure account from the CLI and generate token
az login
BEARER=$(az account get-access-token)
TOKEN=$(echo $BEARER | jq ".accessToken" -r)
#Replace {vars}
curl -X PUT -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.NetApp/netAppAccounts/{accountName}/capacityPools/{poolName}/volumes/{volumeName}?api-version=2021-10-01 -d '{
    "location": "{location}",
    "properties": {
        "serviceLevel": "Ultra",
        "creationToken": "{volumeName}",
        "usageThreshold": 107374182400,
        "exportPolicy": {
                    "rules": [
                        {
                            "ruleIndex": 1,
                            "unixReadOnly": false,
                            "unixReadWrite": true,
                            "cifs": false,
                            "nfsv3": true,
                            "nfsv41": false,
                            "allowedClients": "0.0.0.0/0",
                            "kerberos5ReadOnly": false,
                            "kerberos5ReadWrite": false,
                            "kerberos5iReadOnly": false,
                            "kerberos5iReadWrite": false,
                            "kerberos5pReadOnly": false,
                            "kerberos5pReadWrite": false,
                            "hasRootAccess": true,
                            "chownMode": "Restricted"
                        }
                    ]
                },
        "protocolTypes": [
                    "NFSv3"
                ],
        "subnetId": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworks/<vNetName>/subnets/<subnetName>",
        "enableSubvolumes": "Enabled"
    }
}'
----

`filePoolVolumes` is set to the name of the parent volume in a subvolume backend's definition.
