---
sidebar: sidebar
permalink: trident-use/anf.html
keywords: trident backend, azure netapp files, smb volumes, smb, windows, drivers, access modes, rwo, rwx, rwp, rwop, file system, aks, managed identities, azure
summary: You can configure Azure NetApp Files as the backend for Astra Trident. You can attach NAS and SMB volumes using an Azure NetApp Files backend.
---

= Configure an Azure NetApp Files backend
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You can configure Azure NetApp Files as the backend for Astra Trident. You can attach NFS and SMB volumes using an Azure NetApp Files backend. Astra Trident also supports credential management using managed Identities for Azure Kubernetes Services (AKS) clusters.

== Azure NetApp Files driver details
Astra Trident provides the following Azure NetApp Files storage drivers to communicate with the cluster. Supported access modes are: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2", options="header"]
|===
|Driver
|Protocol
|volumeMode
|Access modes supported
|File systems supported

|`azure-netapp-files`
a|NFS
SMB
a|Filesystem
a|RWO, ROX, RWX, RWOP
a|`nfs`, `smb`

|===

=== Considerations

* The Azure NetApp Files service does not support volumes smaller than 100 GB. Astra Trident automatically creates 100-GB volumes if a smaller volume is requested.

* Astra Trident supports SMB volumes mounted to pods running on Windows nodes only.

== Managed identities for AKS
Astra Trident supports link:https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview[managed identities^] for Azure Kubernetes Services clusters. To take advantage of streamlined credential management offered by managed identities, you must have: 

* A Kubernetes cluster deployed using AKS
* Managed identities configured on the AKS kubernetes cluster
* Astra Trident installed that includes the `cloudProvider` to specify `Azure`. 
+
[role="tabbed-block"]
====
.Trident operator
--
To install Astra Trident using the Trident operator, edit `tridentorchestrator_cr.yaml` to set `cloudProvider` to `"Azure"`. For example:

----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  windows: false #true for installation on Windows node
  cloudProvider: "Azure"
----
--

.Helm
The following example installs Astra Trident sets `cloudProvider` to `Azure` using the environment variable `$CP` on a Windows node:
--
----
helm install trident trident-operator-23.10.0-custom.tgz --create-namespace --namespace trident --set operatorImage=balasubmacr.azurecr.io/trident-operator:23.10.0-custom-linux-amd64 --set tridentImage=balasubmacr.azurecr.io/trident:23.10.0-custom --set imagePullPolicy=Always --set tridentLogLevel=trace --set cloudProvider=$CP --set windows=$ENABLE_WIN
----

--
.`tridentctl`
The following example installs Astra Trident sets set the `cloudProvider` flag to `Azure`:
--
----
tridentctl install --cloud-provider="Azure"  --windows -n trident
----
====

