---
sidebar: sidebar
permalink: trident-use/anf.html
keywords: trident backend, azure netapp files, smb, windows, sub volumes
summary: You can configure Azure NetApp Files as the backend for Astra Trident. You can attach NAS and SMB volumes using an Azure NetApp Files backend.
---

= Configure an Azure NetApp Files backend
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You can configure Azure NetApp Files as the backend for Astra Trident. You can attach NFS and SMB volumes using an Azure NetApp Files backend.

== Azure NetApp Files driver details
Astra Trident provides the following Azure NetApp Files storage drivers to communicate with the cluster. Supported access modes are: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2", options="header"]
|===
|Driver
|Protocol
|volumeMode
|Access modes supported
|File systems supported

|`azure-netapp-files`
a|NFS
SMB
a|Filesystem
a|RWO, ROX, RWX, RWOP
a|`nfs`, `smb`

|`azure-netapp-files-subvolume`
a|NFS
SMB
a|Filesystem
a|RWO, RWOP
a|`xfs`,`ext3`, `ext4`

|===

== Azure NetApp Files storage drivers
Astra Trident offers two storage drivers for Azure NetApp Files:

`azure-netapp-files`::
Creates an Azure Netapp Files volume for each PVC provisioned. This driver is best suited for high-performance workloads that require large volumes.

`azure-netapp-files-subvolume`::
Creates an Azure NetApp Files _sub volume_ for each PVC provisioned. A sub volume is a storage volume contained within a parent Azure NetApp Files volume. 
+
This driver is best suited for bursty workloads, since throughput is independent of volume size. Faster volume creation times and smaller volumes characterize this driver.
+
WARNING: Volumes created with the `azure-netapp-files-subvolume` driver can be used with RWO access mode only.

== Considerations

* The `azure-netapp-files-subvolume` driver can provision volumes as small as 20 MiB. 

* The `storagePrefix` for `azure-netapp-files-subvolume` backends can be 10 characters or less.

* The `azure-netapp-files` driver does not support volumes smaller than 100 GB. Astra Trident automatically creates 100-GB volumes if a smaller volume is requested.

* Astra Trident supports SMB volumes mounted to pods running on Windows nodes only.

* Astra Trident does not support Windows ARM architecture.
