---
sidebar: sidebar
permalink: trident-use/anf.html
keywords: trident backend, azure netapp files, smbvolumes, smb, windows, sub volumes
summary: You can configure Azure NetApp Files as the backend for Astra Trident. You can attach NAS and SMB volumes using an Azure NetApp Files backend.
---

= Configure an Azure NetApp Files backend
:hardbreaks:
:icons: font
:imagesdir: ../media/

You can configure Azure NetApp Files as the backend for Astra Trident. You can attach NFS and SMB volumes using an Azure NetApp Files backend.

Trident offers two storage drivers for Azure NetApp Files:

The `azure-netapp-files` driver creates an Azure Netapp Files volume for each PVC provisioned.
The `azure-netapp-files-subvolume` driver creates an Azure NetApp Files sub volume for each PVC provisioned. A sub volume is a storage volume contained within a parent Azure NetApp Files volume.

`azure-netapp-files` is suited for high performance workloads that require large volumes.
`azure-netapp-files` is best suited for bursty workloads, since throughput is independent of volume size. Faster volume creation times and smaller volumes characterize this driver.

* link:anf-prep.html[Preparation]
* link:anf-examples.html[Configuration options and examples]

== Considerations

* The `azure-netapp-files-subvolume` driver can provision volumes as small as 20 MiB.

* Volumes created with the `azure-netapp-files-subvolume` driver MUST be used with RWO access mode.

* The `storagePrefix` for `azure-netapp-files-subvolume` backends can be 10 characters or less.

* The `azure-netapp-files` driver does not support volumes smaller than 100 GB. Astra Trident automatically creates 100-GB volumes if a smaller volume is requested.

* Astra Trident supports SMB volumes mounted to pods running on Windows nodes only.

* Astra Trident does not support Windows ARM architecture.
