---
sidebar: sidebar
permalink: trident-use/backends.html
keywords: backends, storage system, anf, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, fsx
summary: A backend defines the relationship between Trident and a storage system. It tells Trident how to communicate with that storage system and how Trident should provision volumes from it. 
---

= Configure backends
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
A backend defines the relationship between Trident and a storage system. It tells Trident how to communicate with that storage system and how Trident should provision volumes from it. 

Trident automatically offers up storage pools from backends that match the requirements defined by a storage class. Learn how to configure the backend for your storage system.

* link:anf.html[Configure an Azure NetApp Files backend^]
* link:gcnv.html[Configure a Google Cloud NetApp Volumes backend^]
* link:element.html[Configure a NetApp HCI or SolidFire backend^]
* link:ontap-nas.html[Configure a backend with ONTAP or Cloud Volumes ONTAP NAS drivers^]
* link:ontap-san.html[Configure a backend with ONTAP or Cloud Volumes ONTAP SAN drivers^]
* link:trident-fsx.html[Use Trident with Amazon FSx for NetApp ONTAP^]

