---
sidebar: sidebar
permalink: trident-use/gcnv-examples.html
keywords: trident backend, google cloud netapp files, nfs volumes, nfs, windows
summary: Learn about NFS and NFS backend configuration options for Google Cloud NetApp Files and review configuration examples.
---

= Azure NetApp Files backend configuration options and examples
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Learn about NFS backend configuration options for Google Cloud NetApp Files and review configuration examples. 

?? need to review this entire section

== Backend configuration options

Each backend provisions volumes in a single Google Cloud region. To create volumes in other regions, you can define additional backends. 

[cols="1, 2, 1",options="header"]
|===
|Parameter |Description |Default
|`version` | |Always 1

|`storageDriverName` | Name of the storage driver |"google-cloud-netapp-files"

|`backendName`  |Custom name or the storage backend |Driver name + "_" + part of API key

|`storageClass` |Optional parameter used to specify the CVS service type. 

Use `software` to select the CVS service type. Otherwise, Astra Trident assumes CVS-Performance service type (`hardware`). |

|`storagePools` | CVS service type only. Optional parameter used to specify storage pools for volume creation. |

|`projectNumber` |Google Cloud account project number. The value is found on the Google Cloud portal home page. |

|`hostProjectNumber` |Required if using a shared VPC network. In this scenario, `projectNumber` is the service project, and `hostProjectNumber` is the host project.|

|`apiRegion` |The Google Cloud region where Astra Trident creates Cloud Volumes Service volumes. When creating cross-region Kubernetes clusters, volumes created in an `apiRegion` can be used in workloads scheduled on nodes across multiple Google Cloud regions. 

Cross-region traffic incurs an additional cost.|

|`apiKey` |API key for the Google Cloud service account with the `netappcloudvolumes.admin` role. 

It includes the JSON-formatted contents of a Google Cloud service account's private key file (copied verbatim into the backend configuration file). |

|`proxyURL` |Proxy URL if proxy server required to connect to CVS account. The proxy server can either be an HTTP proxy or an HTTPS proxy. 

For an HTTPS proxy, certificate validation is skipped to allow the usage of self-signed certificates in the proxy server. 

Proxy servers with authentication enabled are not supported. |

|`nfsMountOptions` |Fine-grained control of NFS mount options. |"nfsvers=3"

|`limitVolumeSize`  |Fail provisioning if the requested volume size is above this value. |"" (not enforced by default)

| `serviceLevel` |The CVS-Performance or CVS service level for new volumes. 

CVS-Performance values are `standard`, `premium`, or `extreme`.

CVS values are `standardsw` or `zoneredundantstandardsw`. 

|CVS-Performance default is "standard".

CVS default is "standardsw". 

|`network` |Google Cloud network used for Cloud Volumes Service volumes. |"default"

|`debugTraceFlags` |Debug flags to use when troubleshooting. Example, `\{"api":false, "method":true}`. 

Do not use this unless you are troubleshooting and require a detailed log dump. |null

|`allowedTopologies` | To enable cross-region access, your StorageClass definition for `allowedTopologies` must include all regions. 

For example:
`- key: topology.kubernetes.io/region
  values:
  - us-east1
  - europe-west1`
|
|===

=== Required permissions and resources

If you receive a “No capacity pools found” error when creating a PVC, it is likely your app registration doesn't have the required permissions and resources (subnet, virtual network, capacity pool) associated. If debug is enabled, Astra Trident will log the Google Cloud resources discovered when the backend is created. Verify an appropriate role is being used.

The values for `resourceGroups`, `netappAccounts`, `capacityPools`, `virtualNetwork`, and `subnet` can be specified using short or fully-qualified names. Fully-qualified names are recommended in most situations as short names can match multiple resources with the same name.  

The `resourceGroups`, `netappAccounts`, and `capacityPools` values are filters that restrict the set of discovered resources to those available to this storage backend and may be specified in any combination. Fully-qualified names follow this format:

[cols=2,options="header"]
|===
|Type |Format
|Resource group |<resource group>
|NetApp account |<resource group>/<netapp account>
|Capacity pool |<resource group>/<netapp account>/<capacity pool>
|Virtual network |<resource group>/<virtual network>
|Subnet |<resource group>/<virtual network>/<subnet>
|===

== Volume provisioning options

You can control default volume provisioning in the `defaults` section of the configuration file. 

[cols=",,",options="header",]
|===
|Parameter |Description |Default
|`exportRule` |The export rules for new volumes. Must be a comma-separated list of any combination of IPv4 addresses or IPv4 subnets in CIDR notation. |"0.0.0.0/0"
|`snapshotDir` |Access to the `.snapshot` directory | "false"
|`snapshotReserve` |Percentage of volume reserved for snapshots |"" (accept CVS default of 0)
|`size` |The size of new volumes. 

CVS-Performance minimum is 100 GiB. 

CVS minimum is 1 GiB. 

|CVS-Performance service type defaults to "100GiB". 

CVS service type does not set a default but requires a 1 GiB minimum.  
|===

== Example configurations
The following examples show basic configurations that leave most parameters to default. This is the easiest way to define a backend.

.Minimal configuration
[%collapsible%closed]
====
This is the absolute minimum backend configuration. With this configuration, Astra Trident discovers all of your NetApp accounts, capacity pools, and subnets delegated to Google Cloud NetApp Files in the configured location, and places new volumes on one of those pools and subnets randomly. Because `nasType` is omitted, the `nfs` default applies and the backend will provision for NFS volumes. 

This configuration is ideal when you are just getting started with Google Cloud NetApp Files and trying things out, but in practice you are going to want to provide additional scoping for the volumes you provision. 

----
---
version: 1
storageDriverName: google-cloud-netapp-files
subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
tenantID: 68e4f836-edc1-fake-bff9-b2d865ee56cf
clientID: dd043f63-bf8e-fake-8076-8de91e5713aa
clientSecret: SECRET
location: eastus
----
====

.Cloud identity for GKE
[%collapsible%closed]
====
This backend configuration omits `tenantID`, `clientID`, and `clientSecret`, which are optional when using a cloud identity.

----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-anf-1
  namespace: trident
spec:
  version: 1
  storageDriverName: google-cloud-netapp-files 
  capacityPools: ["ultra-pool"]
  resourceGroups: ["aks-ami-eastus-rg"]
  netappAccounts: ["smb-na"]
  virtualNetwork: eastus-prod-vnet
  subnet: eastus-anf-subnet
  location: eastus
  subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
----
====

.Specific service level configuration with capacity pool filters
[%collapsible%closed]
====
This backend configuration places volumes in Azure's `eastus` location in an `Ultra` capacity pool. Astra Trident automatically discovers all of the subnets delegated to Azure NetApp Files in that location and places a new volume on one of them randomly.

----
---
version: 1
storageDriverName: azure-netapp-files
subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
tenantID: 68e4f836-edc1-fake-bff9-b2d865ee56cf
clientID: dd043f63-bf8e-fake-8076-8de91e5713aa
clientSecret: SECRET
location: eastus
serviceLevel: Ultra
capacityPools:
- application-group-1/account-1/ultra-1
- application-group-1/account-1/ultra-2
----
====

.Advanced configuration
[%collapsible%closed]
====
This backend configuration further reduces the scope of volume placement to a single subnet, and also modifies some volume provisioning defaults.

----
---
version: 1
storageDriverName: google-cloud-netapp-files
subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
tenantID: 68e4f836-edc1-fake-bff9-b2d865ee56cf
clientID: dd043f63-bf8e-fake-8076-8de91e5713aa
clientSecret: SECRET
location: eastus
serviceLevel: Ultra
capacityPools:
- application-group-1/account-1/ultra-1
- application-group-1/account-1/ultra-2
virtualNetwork: my-virtual-network
subnet: my-subnet
networkFeatures: Standard
nfsMountOptions: vers=3,proto=tcp,timeo=600
limitVolumeSize: 500Gi
defaults:
  exportRule: 10.0.0.0/24,10.0.1.0/24,10.0.2.100
  snapshotDir: 'true'
  size: 200Gi
  unixPermissions: '0777'

----
====

.Virtual pool configuration
[%collapsible%closed]
====
This backend configuration defines multiple storage pools in a single file. This is useful when you have multiple capacity pools supporting different service levels and you want to create storage classes in Kubernetes that represent those. Virtual pool labels were used to differentiate the pools based on `performance`. 

----
---
version: 1
storageDriverName: google-cloud-netapp-files
subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
tenantID: 68e4f836-edc1-fake-bff9-b2d865ee56cf
clientID: dd043f63-bf8e-fake-8076-8de91e5713aa
clientSecret: SECRET
location: eastus
resourceGroups:
- application-group-1
networkFeatures: Basic
nfsMountOptions: vers=3,proto=tcp,timeo=600
labels:
  cloud: gcp
storage:
- labels:
    performance: gold
  serviceLevel: Ultra
  capacityPools:
  - ultra-1
  - ultra-2
  networkFeatures: Standard
- labels:
    performance: silver
  serviceLevel: Premium
  capacityPools:
  - premium-1
- labels:
    performance: bronze
  serviceLevel: Standard
  capacityPools:
  - standard-1
  - standard-2

----
====

.Supported topologies configuration
[%collapsible%closed]
====
Astra Trident facilitates provisioning of volumes for workloads based on regions and availability zones. The `supportedTopologies` block in this backend configuration is used to provide a list of regions and zones per backend. The region and zone values specified here must match the region and zone values from the labels on each Kubernetes cluster node. These regions and zones represent the list of permissible values that can be provided in a storage class. For storage classes that contain a subset of the regions and zones provided in a backend, Astra Trident will create volumes in the mentioned region and zone.
For more information, refer to link:../trident-use/csi-topology.html[Use CSI Topology].

----
---
version: 1
storageDriverName: google-cloud-netapp-files
subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
tenantID: 68e4f836-edc1-fake-bff9-b2d865ee56cf
clientID: dd043f63-bf8e-fake-8076-8de91e5713aa
clientSecret: SECRET
location: eastus
serviceLevel: Ultra
capacityPools:
- application-group-1/account-1/ultra-1
- application-group-1/account-1/ultra-2
supportedTopologies:
- topology.kubernetes.io/region: eastus
  topology.kubernetes.io/zone: eastus-1
- topology.kubernetes.io/region: eastus
  topology.kubernetes.io/zone: eastus-2
----
====

== Storage class definitions 
The following `StorageClass` definitions refer to the storage pools above. 

=== Example definitions using `parameter.selector` field
Using `parameter.selector` you can specify for each `StorageClass` the virtual pool that is used to host a volume. The volume will have the aspects defined in the chosen pool.

----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold
provisioner: csi.trident.netapp.io
parameters:
  selector: "performance=gold"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: silver
provisioner: csi.trident.netapp.io
parameters:
  selector: "performance=silver"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bronze
provisioner: csi.trident.netapp.io
parameters:
  selector: "performance=bronze"
allowVolumeExpansion: true
----

.Using different secrets per namespace
[%collapsible%closed]
====
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: anf-sc-smb
provisioner: csi.trident.netapp.io
parameters:
  backendType: "google-cloud-netapp-files"
  trident.netapp.io/nasType: "smb"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: ${pvc.namespace}
----
====

.Using different secrets per volume
[%collapsible%closed]
====
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: anf-sc-smb
provisioner: csi.trident.netapp.io
parameters:
  backendType: "azure-netapp-files"
  trident.netapp.io/nasType: "smb"
  csi.storage.k8s.io/node-stage-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-stage-secret-namespace: ${pvc.namespace}
----
====

[NOTE]
`nasType: smb` filters for pools which support SMB volumes. `nasType: nfs` or `nasType: null` filters for NFS pools.

== Create the backend

After you create the backend configuration file, run the following command:

----
tridentctl create backend -f <backend-file>
----

If the backend creation fails, something is wrong with the backend configuration. You can view the logs to determine the cause by running the following command:

----
tridentctl logs
----

After you identify and correct the problem with the configuration file, you can run the create command again.
