---
sidebar: sidebar
permalink: trident-use/ontap-san.html
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system
summary: Learn about configuring an ONTAP backend with ONTAP SAN drivers.
---

= ONTAP SAN driver overview
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Learn about configuring an ONTAP backend with ONTAP and Cloud Volumes ONTAP SAN drivers.

== ONTAP SAN driver details
Trident provides the following SAN storage drivers to communicate with the ONTAP cluster. Supported access modes are: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

//IMPORTANT: If you are using Astra Control for protection, recovery, and mobility, read <<Astra Control driver compatibility>>. 

[cols="2, 1, 1, 2, 2", options="header"]
|===
|Driver
|Protocol
|volumeMode
|Access modes supported
|File systems supported

|`ontap-san`
a|iSCSI
SCSI over FC
a|Block
a|RWO, ROX, RWX, RWOP
a|No filesystem; raw block device

|`ontap-san`
a|iSCSI
SCSI over FC
a|Filesystem
a|RWO, RWOP

ROX and RWX are not available in Filesystem volume mode.
a|`xfs`, `ext3`, `ext4`

|`ontap-san`
a|NVMe/TCP

Refer to <<Additional considerations for NVMe/TCP>>.
a|Block
a|RWO, ROX, RWX, RWOP
a|No filesystem; raw block device

|`ontap-san`
a|NVMe/TCP

Refer to <<Additional considerations for NVMe/TCP>>.
a|Filesystem
a|RWO, RWOP

ROX and RWX are not available in Filesystem volume mode.
a|`xfs`, `ext3`, `ext4`

|`ontap-san-economy`
a|iSCSI
a|Block
a|RWO, ROX, RWX, RWOP
a|No filesystem; raw block device

|`ontap-san-economy`
a|iSCSI
a|Filesystem
a|RWO, RWOP

ROX and RWX are not available in Filesystem volume mode.
a|`xfs`, `ext3`, `ext4`
|===


//=== Astra Control driver compatibility
//Astra Control provides seamless protection, disaster recovery, and mobility (moving volumes between Kubernetes clusters) for volumes created with the `ontap-nas`, `ontap-nas-flexgroup`, and `ontap-san` drivers. Refer to link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites[Astra Control replication prerequisites^] for details.

[WARNING]
====

* Use `ontap-san-economy` only if persistent volume usage count is expected to be higher than link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html[supported ONTAP volume limits^]. 
* Use `ontap-nas-economy` only if persistent volume usage count is expected to be  higher than link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html[supported ONTAP volume limits^] and the `ontap-san-economy` driver cannot be used. 
* Do not use use `ontap-nas-economy` if you anticipate the need for data protection, disaster recovery, or mobility.
====

== User permissions

Trident expects to be run as either an ONTAP or SVM administrator, typically using the `admin` cluster user or a `vsadmin` SVM user, or a user with a different name that has the same role. For Amazon FSx for NetApp ONTAP deployments, Trident expects to be run as either an ONTAP or SVM administrator, using the cluster `fsxadmin` user or a `vsadmin` SVM user, or a user with a different name that has the same role. The `fsxadmin` user is a limited replacement for the cluster admin user.

NOTE: If you use the `limitAggregateUsage` parameter, cluster admin permissions are required. When using Amazon FSx for NetApp ONTAP with Trident, the `limitAggregateUsage` parameter will not work with the `vsadmin` and `fsxadmin` user accounts. The configuration operation will fail if you specify this parameter.

While it is possible to create a more restrictive role within ONTAP that a Trident driver can use, we don't recommend it. Most new releases of Trident will call additional APIs that would have to be accounted for, making upgrades difficult and error-prone.

== Additional considerations for NVMe/TCP
Trident supports the non-volatile memory express (NVMe) protocol using the `ontap-san` driver including:

* IPv6
* Snapshots and clones of NVMe volumes
* Resizing an NVMe volume
* Importing an NVMe volume that was created outside of Trident so that its lifecycle can be managed by Trident
* NVMe-native multipathing
* Graceful or ungraceful shutdown of the K8s nodes (24.06)

Trident does not support:

* DH-HMAC-CHAP that is supported by natively by NVMe
* Device mapper (DM) multipathing
* LUKS encryption
