---
sidebar: sidebar
permalink: trident-use/ontap-auth.html
keywords: trident backend, AFF, FAS, ONTAP Select, Cloud, Amazon FSx for NetApp ONTAP, drivers, ONTAP drivers, credential based, certificate based, authentication
summary: Learn about authenticating an ONTAP backend.
---

= Authenticate an ONTAP backend
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn about authenticating an ONTAP backend.

Authentication
Trident offers two modes of authenticating an ONTAP backend.

Credential-based: The username and password to an ONTAP user with the required permissions. It is recommended to use a pre-defined security login role, such as admin or vsadmin to ensure maximum compatibility with ONTAP versions.
Certificate-based: Trident can also communicate with an ONTAP cluster using a certificate installed on the backend. Here, the backend definition must contain Base64-encoded values of the client certificate, key, and the trusted CA certificate if used (recommended).
Users can also choose to update existing backends, opting to move from credential-based to certificate-based, and vice-versa. If both credentials and certificates are provided, Trident will default to using certificates while issuing a warning to remove the credentials from the backend definition.

Credential-based Authentication
Trident requires the credentials to an SVM-scoped/Cluster-scoped admin to communicate with the ONTAP backend. It is recommended to make use of standard, pre-defined roles such as admin or vsadmin. This ensures forward compatibility with future ONTAP releases that may expose feature APIs to be used by future Trident releases. A custom security login role can be created and used with Trident, but is not recommended.

A sample backend definition will look like this:

{
  "version": 1,
  "backendName": "ExampleBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "secret",
}
Keep in mind that the backend definition is the only place the credentials are stored in plaintext. Once the backend is created, usernames/passwords are encoded with Base64 and stored as Kubernetes secrets. The creation/updation of a backend is the only step that requires knowledge of the credentials. As such, it is an admin-only operation, to be performed by the Kubernetes/Storage administrator.

Certificated-based Authentication
Trident 21.01 introduces a new feature: authenticating ONTAP backends using certificates. New and existing backends can use a certificate and communicate with the ONTAP backend. Three parameters are required in the backend definition.

clientCertificate: Base64-encoded value of client certificate.
clientPrivateKey: Base64-encoded value of associated private key.
trustedCACertificate: Base64-encoded value of trusted CA certificate. If using a trusted CA, this parameter must be provided. This can be ignored if no trusted CA is used.
