---
sidebar: sidebar
permalink: trident-use/trident-fsx-storageclass-pvc.html
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident
summary: Using Trident with Amazon FSx for NetApp ONTAP, you can ensure that your Kubernetes clusters running in Amazon Elastic Kubernetes Service (EKS) can provision block and file persistent volumes backed by ONTAP.
---

= Configure a storage class and PVC
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Configure a Kubernetes StorageClass object and create the storage class to instruct Trident how to provision volumes. Create a PersistentVolumeClaim (PVC) that uses the configured Kubernetes StorageClass to request access to the PV. You can then mount the PV to a pod.

== Create a storage class

=== Configure a Kubernetes StorageClass object
The https://kubernetes.io/docs/concepts/storage/storage-classes/[Kubernetes StorageClass object^] object identifies Trident as the provisioner that is used for that class and instructs Trident how to provision a volume. Use this example to setup Storageclass for volumes using NFS (Refer to Trident Attribute section below for the full list of attributes):

[source,YAML]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-gold
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  snapshots: "true"
----

To provision NFSv3 volumes on AWS Bottlerocket, add the required `mountOptions` to the storage class:

[source,YAML]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-gold
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  media: "ssd"
  provisioningType: "thin"
  snapshots: "true"
mountOptions:
  - nfsvers=3
  - nolock
----

Refer to link:../trident-reference/objects.html[Kubernetes and Trident objects] for details on how storage classes interact with the `PersistentVolumeClaim` and parameters for controlling how Trident provisions volumes. 

=== Create a storage class

.Steps
. This is a Kubernetes object, so use `kubectl` to create it in Kubernetes.
+
[source,console]
----
kubectl create -f storage-class-ontapnas.yaml
----

. You should now see a *basic-csi* storage class in both Kubernetes and Trident, and Trident should have discovered the pools on the backend.
+
[source,console]
----
kubectl get sc basic-csi
----
----
NAME         PROVISIONER             AGE
basic-csi    csi.trident.netapp.io   15h

----

== Create the PVC

A https://kubernetes.io/docs/concepts/storage/persistent-volumes[_PersistentVolumeClaim_^] (PVC) is a request for access to the PersistentVolume on the cluster. 

The PVC can be configured to request storage of a certain size or access mode. Using the associated StorageClass, the cluster administrator can control more than PersistentVolume size and access mode--such as performance or service level. 

After you create the PVC, you can mount the volume in a pod.

=== Sample manifests

.PersistentVolumeClaim sample manifests
[%collapsible]
====
These examples show basic PVC configuration options. 

.PVC with RWX access
This example shows a basic PVC with RWX access that is associated with a StorageClass named `basic-csi`.
[source,YAML]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ontap-gold
----

.PVC using iSCSI example
This example shows a basic PVC for iSCSI with RWO access that is associated with a StorageClass named `protection-gold`.
[source,YAML]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: pvc-san
spec:
accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 1Gi
storageClassName: protection-gold
----
====

=== Create the PV and PVC
.Steps

. Create the PVC.
+
[source,console]
----
kubectl create -f pvc.yaml
----
. Verify the PVC status.
+
[source,console]
----
kubectl get pvc
----
----
NAME        STATUS VOLUME     CAPACITY ACCESS MODES STORAGECLASS AGE
pvc-storage Bound  pv-name 2Gi      RWO                       5m
----

Refer to link:../trident-reference/objects.html[Kubernetes and Trident objects] for details on how storage classes interact with the `PersistentVolumeClaim` and parameters for controlling how Trident provisions volumes. 

== Trident attributes

These parameters determine which Trident-managed storage pools should be utilized to provision volumes of a given type.

[cols=",,,,,",options="header",]
|===
|Attribute |Type |Values |Offer |Request |Supported by |media^1^ |string |hdd, hybrid, ssd |Pool contains media of this type; hybrid means both |Media type specified |ontap-nas, ontap-nas-economy, ontap-nas-flexgroup, ontap-san, solidfire-san

|provisioningType |string |thin, thick |Pool supports this provisioning method |Provisioning method specified |thick: all ontap; thin: all ontap & solidfire-san

|backendType |string a| ontap-nas, ontap-nas-economy, ontap-nas-flexgroup, ontap-san, solidfire-san, gcp-cvs, azure-netapp-files, ontap-san-economy |Pool belongs to this type of backend |Backend specified |All drivers

|snapshots |bool |true, false |Pool supports volumes with snapshots |Volume with snapshots enabled |ontap-nas, ontap-san, solidfire-san, gcp-cvs

|clones |bool |true, false |Pool supports cloning volumes |Volume with clones enabled |ontap-nas, ontap-san, solidfire-san, gcp-cvs

|encryption |bool |true, false |Pool supports encrypted volumes |Volume with encryption enabled |ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, ontap-san

|IOPS |int |positive integer |Pool is capable of guaranteeing IOPS in this range |Volume guaranteed these IOPS |solidfire-san
|===

^1^: Not supported by ONTAP Select systems
