---
sidebar: sidebar
permalink: trident-use/trident-fsx-storage-backend.html
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident
summary: Using Trident with Amazon FSx for NetApp ONTAP, you can ensure that your Kubernetes clusters running in Amazon Elastic Kubernetes Service (EKS) can provision block and file persistent volumes backed by ONTAP.
---

= Configure the Storage Backend
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]

== ONTAP SAN and NAS driver integration

To create a storage backend, you need to create a configuration file in either JSON or YAML format. The file needs to specify the type of storage you want (NAS or SAN), the file system, and SVM to get it from and how to authenticate with it. The following example shows how to define NAS-based storage and using an AWS secret to store the credentials to the SVM you want to use:

[role="tabbed-block"]
====

.YAML
--
[source,YAML]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas
  namespace: trident
spec:
  version: 1
  storageDriverName: ontap-nas
  backendName: tbc-ontap-nas
  svm: svm-name
  aws: 
    fsxFilesystemID: fs-xxxxxxxxxx
  credentials: 
    name: "arn:aws:secretsmanager:us-west-2:xxxxxxxx:secret:secret-name"
    type: awsarn
----
--

.JSON
--
[source,JSON]
----
{
  "apiVersion": "trident.netapp.io/v1",
  "kind": "TridentBackendConfig",
  "metadata": {
    "name": "backend-tbc-ontap-nas"
    "namespace": "trident"
  },
  "spec": {
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "tbc-ontap-nas",
    "svm": "svm-name",
    "aws": {
      "fsxFilesystemID": "fs-xxxxxxxxxx"
    },
    "managementLIF": null,
    "credentials": {
      "name": "arn:aws:secretsmanager:us-west-2:xxxxxxxx:secret:secret-name",
      "type": "awsarn"
    }
  }
}

----
--

====

Run the following commands to create and validate the Trident Backend Configuration (TBC):

* Create trident backend configuration (TBC) from yaml file and run the following command:
+
[source,console]
----
kubectl create -f backendconfig.yaml -n trident 
----
+
----
tridentbackendconfig.trident.netapp.io/backend-tbc-ontap-nas created
----
* Validate the trident backend configuration (TBC) was created successfully:
+
[source,console]
---- 
Kubectl get tbc -n trident
----
+
----
NAME                         BACKEND NAME         BACKEND UUID                           PHASE   STATUS

backend-tbc-ontap-nas        tbc-ontap-nas        933e0071-66ce-4324-b9ff-f96d916ac5e9   Bound   Success
----

== FSx for ONTAP driver details

You can integrate Trident with Amazon FSx for NetApp ONTAP using the following drivers:

* `ontap-san`: Each PV provisioned is a LUN within its own Amazon FSx for NetApp ONTAP volume. Recommended for block storage.
* `ontap-nas`: Each PV provisioned is a full Amazon FSx for NetApp ONTAP volume. Recommended for NFS and SMB.
* `ontap-san-economy`: Each PV provisioned is a LUN with a configurable number of LUNs per Amazon FSx for NetApp ONTAP volume.
* `ontap-nas-economy`: Each PV provisioned is a qtree, with a configurable number of qtrees per Amazon FSx for NetApp ONTAP volume.
* `ontap-nas-flexgroup`: Each PV provisioned is a full Amazon FSx for NetApp ONTAP FlexGroup volume.

For driver details, refer to link:../trident-use/ontap-nas.html[NAS drivers] and link:../trident-use/ontap-san.html[SAN drivers].

Once the configuration file has been created, run this command to create it within your EKS:
[source,console]
----
kubectl create -f configuration_file
----

To verify the status, run this command:
[source,console]
----
kubectl get tbc -n trident
----

----
NAME                    BACKEND NAME            BACKEND UUID                           PHASE   STATUS
backend-fsx-ontap-nas   backend-fsx-ontap-nas   7a551921-997c-4c37-a1d1-f2f4c87fa629   Bound   Success
----


== Backend advanced configuration and examples

See the following table for the backend configuration options:

[cols=3,options="header"]
|===
|Parameter |Description |Example

|`version` 
| 
|Always 1

|`storageDriverName` 
| Name of the storage driver 
|`ontap-nas`, `ontap-nas-economy`, `ontap-nas-flexgroup`, `ontap-san`, `ontap-san-economy`

|`backendName`  
|Custom name or the storage backend 
| Driver name + “_” + dataLIF

|`managementLIF` 
|IP address of a cluster or SVM management LIF 

A fully-qualified domain name (FQDN) can be specified.

Can be set to use IPv6 addresses if Trident was installed using the IPv6 flag. IPv6 addresses must be defined in square brackets, such as [28e8:d9fb:a825:b7bf:69a8:d02f:9e7b:3555]. 

If you provide the `fsxFilesystemID` under the `aws` field, you need not to provide the `managementLIF` because Trident retrieves the SVM `managementLIF` information from AWS. So, you must provide credentials for a user under the SVM (For example: vsadmin) and the user must have the `vsadmin` role.
|“10.0.0.1”, “[2001:1234:abcd::fefe]”

|`dataLIF` 
|IP address of protocol LIF. 

*ONTAP NAS drivers*: NetApp recommends specifying dataLIF. If not provided, Trident fetches dataLIFs from the SVM. You can specify a fully-qualified domain name (FQDN) to be used for the NFS mount operations, allowing you to create a round-robin DNS to load-balance across multiple dataLIFs. Can be changed after initial setting. Refer to <<Update `dataLIF` after initial configuration>>. 

*ONTAP SAN drivers*: Do not specify for iSCSI. Trident uses ONTAP Selective LUN Map to discover the iSCI LIFs needed to establish a multi path session. A warning is generated if dataLIF is explicitly defined.

Can be set to use IPv6 addresses if Trident was installed using the IPv6 flag. IPv6 addresses must be defined in square brackets, such as [28e8:d9fb:a825:b7bf:69a8:d02f:9e7b:3555].  

|

|`autoExportPolicy`	
|Enable automatic export policy creation and updating [Boolean]. 

Using the `autoExportPolicy` and `autoExportCIDRs` options, Trident can manage export policies automatically. 
|`false`

|`autoExportCIDRs` 
|List of CIDRs to filter Kubernetes' node IPs against when `autoExportPolicy` is enabled. 

Using the `autoExportPolicy` and `autoExportCIDRs` options, Trident can manage export policies automatically.	
|"[“0.0.0.0/0”, “::/0”]"

|`labels` 
|Set of arbitrary JSON-formatted labels to apply on volumes 
|""

|`clientCertificate`	
|Base64-encoded value of client certificate. Used for certificate-based auth 
|""

|`clientPrivateKey`	
|Base64-encoded value of client private key. Used for certificate-based auth	
|""

|`trustedCACertificate` 
|Base64-encoded value of trusted CA certificate. Optional. Used for certificate-based authentication.  
|""

|`username` 
|Username to connect to the cluster or SVM. Used for credential-based authentication. For example, vsadmin.
|

|`password` 
|Password to connect to the cluster or SVM. Used for credential-based authentication. 
|

|`svm` 
|Storage virtual machine to use 
|Derived if an SVM managementLIF is specified.

|`storagePrefix` 
|Prefix used when provisioning new volumes in the SVM. 

Cannot be modified after creation. To update this parameter, you will need to create a new backend.
|`trident`

|`limitAggregateUsage` |*Do not specify for Amazon FSx for NetApp ONTAP.* 

The provided `fsxadmin` and `vsadmin` do not contain the permissions required to retrieve aggregate usage and limit it using Trident.

|Do not use.

|`limitVolumeSize` 
|Fail provisioning if requested volume size is above this value. 

Also restricts the maximum size of the volumes it manages for qtrees and LUNs, and the `qtreesPerFlexvol` option allows customizing the maximum number of qtrees per FlexVol volume 

|“” (not enforced by default)

|`lunsPerFlexvol` 
|Maximum LUNs per Flexvol volume, must be in range [50, 200]. 

SAN only. 
|"`100`"

|`debugTraceFlags` 
|Debug flags to use when troubleshooting. Example, {“api”:false, “method”:true} 

Do not use `debugTraceFlags` unless you are troubleshooting and require a detailed log dump.
|null

|`nfsMountOptions`	
|Comma-separated list of NFS mount options. 

The mount options for Kubernetes-persistent volumes are normally specified in storage classes, but if no mount options are specified in a storage class, Trident will fall back to using the mount options specified in the storage backend's configuration file. 

If no mount options are specified in the storage class or the configuration file, Trident will not set any mount options on an associated persistent volume.	
|""

| `nasType` | Configure NFS or SMB volumes creation. 

Options are `nfs`, `smb`, or null. 

*Must set to `smb` for SMB volumes.* Setting to null defaults to NFS volumes. 
|`nfs`

|`qtreesPerFlexvol`	
|Maximum Qtrees per FlexVol volume, must be in range [50, 300]	
|`"200"`

|`smbShare` 
|You can specify one of the following: the name of an SMB share created using the Microsoft Management Console or ONTAP CLI or a name to allow Trident to create the SMB share.
 
This parameter is required for Amazon FSx for ONTAP backends.


|`smb-share`

|`useREST` 
|Boolean parameter to use ONTAP REST APIs.

When set to `true`, Trident will use ONTAP REST APIs to communicate with the backend. 

This feature requires ONTAP 9.11.1 and later. In addition, the ONTAP login role used must have access to the `ontap` application. This is satisfied by the pre-defined `vsadmin` and `cluster-admin` roles.
|`false`

|`aws`| You can specify the following in the configuration file for AWS FSx for ONTAP:
- `fsxFilesystemID`: Specify the ID of the AWS FSx file system.
- `apiRegion`: AWS API region name. 
- `apikey`: AWS API key.
- `secretKey`: AWS secret key.

| ``
``


`""`
`""`
`""`

|`credentials` |Specify the FSx SVM credentials to store in AWS Secret Manager.
- `name`: Amazon Resource Name (ARN) of the secret, which contains the credentials of SVM.
- `type`: Set to `awsarn`. 
Refer to link:https://docs.aws.amazon.com/secretsmanager/latest/userguide/create_secret.html[Create an AWS Secrets Manager secret^] for more information.| 

|===

== Backend configuration options for provisioning volumes

You can control default provisioning using these options in the `defaults` section of the configuration. For an example, see the configuration examples below.

[cols=3,options="header"]
|===
|Parameter |Description |Default
|`spaceAllocation` |Space-allocation for LUNs |`true`

|`spaceReserve` |Space reservation mode; “none” (thin) or “volume” (thick) |`none`

|`snapshotPolicy` |Snapshot policy to use |`none`

|`qosPolicy` |QoS policy group to assign for volumes created. Choose one of qosPolicy or adaptiveQosPolicy per storage pool or backend. 

Using QoS policy groups with Trident requires ONTAP 9.8 or later. 

You should use a non-shared QoS policy group and ensuring the policy group is applied to each constituent individually. A shared QoS policy group enforces the ceiling for the total throughput of all workloads.

|“”

|`adaptiveQosPolicy` |Adaptive QoS policy group to assign for volumes created. Choose one of qosPolicy or adaptiveQosPolicy per storage pool or backend. 

Not supported by ontap-nas-economy. 
|“”

|`snapshotReserve` |Percentage of volume reserved for snapshots	“0” |If `snapshotPolicy` is `none`, `else` “”

|`splitOnClone` |Split a clone from its parent upon creation |`false`

|`encryption` |Enable NetApp Volume Encryption (NVE) on the new volume; defaults to `false`. NVE must be licensed and enabled on the cluster to use this option. 

If NAE is enabled on the backend, any volume provisioned in Trident will be NAE enabled. 

For more information, refer to: link:../trident-reco/security-reco.html[How Trident works with NVE and NAE]. |`false`

|`luksEncryption` 
| Enable LUKS encryption. Refer to link:../trident-reco/security-reco.html#Use-Linux-Unified-Key-Setup-(LUKS)[Use Linux Unified Key Setup (LUKS)]. 

SAN only. 
| ""


|`tieringPolicy` 
|Tiering policy to use	`none` 
|

|`unixPermissions`	|Mode for new volumes. 

*Leave empty for SMB volumes.*	
|“"

|`securityStyle` |Security style for new volumes. 

NFS supports `mixed` and `unix` security styles. 

SMB supports `mixed` and `ntfs` security styles. 

|NFS default is `unix`.

SMB default is `ntfs`.

|===


== Prepare to provision SMB volumes
You can provision SMB volumes using the `ontap-nas` driver. Before you complete <<ONTAP SAN and NAS driver integration>> complete the following steps. 

.Before you begin
Before you can provision SMB volumes using the `ontap-nas` driver, you must have the following. 

* A Kubernetes cluster with a Linux controller node and at least one Windows worker node running Windows Server 2019. Trident supports SMB volumes mounted to pods running on Windows nodes only.

* At least one Trident secret containing your Active Directory credentials. To generate secret `smbcreds`:
+
----
kubectl create secret generic smbcreds --from-literal username=user --from-literal password='password'
----

* A CSI proxy configured as a Windows service. To configure a `csi-proxy`, refer to link:https://github.com/kubernetes-csi/csi-proxy[GitHub: CSI Proxy^] or link:https://github.com/Azure/aks-engine/blob/master/docs/topics/csi-proxy-windows.md[GitHub: CSI Proxy for Windows^] for Kubernetes nodes running on Windows.

.Steps

. Create SMB shares. You can create the SMB admin shares in one of two ways either using the link:https://learn.microsoft.com/en-us/troubleshoot/windows-server/system-management-components/what-is-microsoft-management-console[Microsoft Management Console^] Shared Folders snap-in or using the ONTAP CLI. To create the SMB shares using the ONTAP CLI:
.. If necessary, create the directory path structure for the share.
+
The `vserver cifs share create` command checks the path specified in the -path option during share creation. If the specified path does not exist, the command fails.

.. Create an SMB share associated with the specified SVM:
+
[source,console]
----
vserver cifs share create -vserver vserver_name -share-name share_name -path path [-share-properties share_properties,...] [other_attributes] [-comment text]
----

.. Verify that the share was created:
+
[source,console]
----
vserver cifs share show -share-name share_name
----
+
NOTE: Refer to link:https://docs.netapp.com/us-en/ontap/smb-config/create-share-task.html[Create an SMB share^] for full details.

. When creating the backend, you must configure the following to specify SMB volumes. For all FSx for ONTAP backend configuration options, refer to link:trident-fsx-examples.html[FSx for ONTAP configuration options and examples].
+
[cols=3,options="header"]
|===
|Parameter |Description | Example

|`smbShare`
|You can specify one of the following: the name of an SMB share created using the Microsoft Management Console or ONTAP CLI or a name to allow Trident to create the SMB share.
 
This parameter is required for Amazon FSx for ONTAP backends.

| `smb-share` 

|`nasType`
| *Must set to `smb`.* If null, defaults to `nfs`.
|`smb`

|`securityStyle` 
|Security style for new volumes. 

*Must be set to `ntfs` or `mixed` for SMB volumes.*
|`ntfs` or `mixed` for SMB volumes

|`unixPermissions`
|Mode for new volumes. *Must be left empty for SMB volumes.*
|""
|===
