---
sidebar: sidebar
permalink: trident-use/trident-fsx-storageclass-pvc.html
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident
summary: Using Astra Trident with Amazon FSx for NetApp ONTAP, you can ensure that your Kubernetes clusters running in Amazon Elastic Kubernetes Service (EKS) can provision block and file persistent volumes backed by ONTAP.
---

= Configure a storage class and PVC
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Configure a Kubernetes StorageClass object and create the storage class to instruct Astra Trident how to provision volumes. Create a PersistentVolume (PV) and a PersistentVolumeClaim (PVC) that uses the configured Kubernetes StorageClass to request access to the PV. You can then mount the PV to a pod.

== Create a storage class

=== Configure a Kubernetes StorageClass object
The https://kubernetes.io/docs/concepts/storage/storage-classes/[Kubernetes StorageClass object^] identifies Astra Trident as the provisioner that is used for that class instructs Astra Trident how to provision a volume. For example:

----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-gold
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  media: "ssd"
  provisioningType: "thin"
  snapshots: "true"
----

Refer to link:../trident-reference/objects.html[Kubernetes and Trident objects] for details on how storage classes interact with the `PersistentVolumeClaim` and parameters for controlling how Astra Trident provisions volumes. 

=== Create a storage class

.Steps
. This is a Kubernetes object, so use `kubectl` to create it in Kubernetes.
+
----
kubectl create -f sample-input/storage-class-basic-csi.yaml
----

. You should now see a *basic-csi* storage class in both Kubernetes and Astra Trident, and Astra Trident should have discovered the pools on the backend.
+
----
kubectl get sc basic-csi
NAME         PROVISIONER             AGE
basic-csi    csi.trident.netapp.io   15h

----

== Create the PV and PVC

A link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/[_PersistentVolume_^] (PV) is a physical storage resource provisioned by the cluster administrator on a Kubernetes cluster. The https://kubernetes.io/docs/concepts/storage/persistent-volumes[_PersistentVolumeClaim_^] (PVC) is a request for access to the PersistentVolume on the cluster. 

The PVC can be configured to request storage of a certain size or access mode. Using the associated StorageClass, the cluster administrator can control more than PersistentVolume size and access mode--such as performance or service level. 

After you create the PV and PVC, you can mount the volume in a pod.

=== Sample manifests

.PersistentVolume sample manifest
[%collapsible]
====
This sample manifest shows a basic PV of 10Gi that is associated with StorageClass `basic-csi`.
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
  labels:
    type: local
spec:
  storageClassName: basic-csi
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/my/host/path"
----
====

.PersistentVolumeClaim sample manifests
[%collapsible]
====
These examples show basic PVC configuration options. 

.PVC with RWO access
This example shows a basic PVC with RWO access that is associated with a StorageClass named `basic-csi`.
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----

.PVC with NVMe/TCP
This example shows a basic PVC for NVMe/TCP with RWO access that is associated with a StorageClass named `protection-gold`.
----
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: pvc-san-nvme
spec:
accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 300Mi
storageClassName: protection-gold
----
====

.Pod manifest samples
[%collapsible]
====
These examples show basic configurations to attach the PVC to a pod. 

.Basic configuration
----
kind: Pod
apiVersion: v1
metadata:
  name: pv-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
       claimName: basic
  containers:
    - name: pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/my/mount/path"
          name: pv-storage
----

====

=== Create the PV and PVC


.Steps
. Create the PV.
+
----
kubectl create -f pv.yaml
----
. Verify the PV status.
+
----
kubectl get pv
NAME        CAPACITY  ACCESS MODES  RECLAIM POLICY  STATUS    CLAIM  STORAGECLASS  REASON  AGE
pv-storage  4Gi       RWO           Retain          Available                              7s
----
. Create the PVC.
+
----
kubectl create -f pvc.yaml
----
. Verify the PVC status.
+
----
kubectl get pvc
NAME        STATUS VOLUME     CAPACITY ACCESS MODES STORAGECLASS AGE
pvc-storage Bound  pv-name 2Gi      RWO                       5m
----

Refer to link:../trident-reference/objects.html[Kubernetes and Trident objects] for details on how storage classes interact with the `PersistentVolumeClaim` and parameters for controlling how Astra Trident provisions volumes. 

== Astra Trident attributes

These parameters determine which Astra Trident-managed storage pools should be utilized to provision volumes of a given type.

[cols=",,,,,",options="header",]
|===
|Attribute |Type |Values |Offer |Request |Supported by |media^1^ |string |hdd, hybrid, ssd |Pool contains media of this type; hybrid means both |Media type specified |ontap-nas, ontap-nas-economy, ontap-nas-flexgroup, ontap-san, solidfire-san

|provisioningType |string |thin, thick |Pool supports this provisioning method |Provisioning method specified |thick: all ontap; thin: all ontap & solidfire-san

|backendType |string a| ontap-nas, ontap-nas-economy, ontap-nas-flexgroup, ontap-san, solidfire-san, gcp-cvs, azure-netapp-files, ontap-san-economy |Pool belongs to this type of backend |Backend specified |All drivers

|snapshots |bool |true, false |Pool supports volumes with snapshots |Volume with snapshots enabled |ontap-nas, ontap-san, solidfire-san, gcp-cvs

|clones |bool |true, false |Pool supports cloning volumes |Volume with clones enabled |ontap-nas, ontap-san, solidfire-san, gcp-cvs

|encryption |bool |true, false |Pool supports encrypted volumes |Volume with encryption enabled |ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, ontap-san

|IOPS |int |positive integer |Pool is capable of guaranteeing IOPS in this range |Volume guaranteed these IOPS |solidfire-san
|===

^1^: Not supported by ONTAP Select systems