---
sidebar: sidebar
permalink: trident-use/trident-fsx-iam-role.html
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident
summary: Using Trident with Amazon FSx for NetApp ONTAP, you can ensure that your Kubernetes clusters running in Amazon Elastic Kubernetes Service (EKS) can provision block and file persistent volumes backed by ONTAP.
---

= Create an IAM role and AWS Secret 
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]

You can configure Kubernetes pods to access AWS resources by authenticating as an AWS IAM role instead of by providing explicit AWS credentials.

[NOTE]
To authenticate using an AWS IAM role, you must have a Kubernetes cluster deployed using EKS.

== Create AWS Secret Manager secret

This example creates an AWS Secret Manager secret to store Trident CSI credentials:

`aws secretsmanager create-secret --name trident-secret --description "Trident CSI credentials" --secret-string "{\"username\":\"vsadmin\",\"password\":\"<svmpassword>\"}"`

== Create IAM Policy

The following examples creates an IAM policy using the AWS CLI:

`aws iam create-policy --policy-name AmazonFSxNCSIDriverPolicy --policy-document file://policy.json --description "This policy grants access to Trident CSI to FSxN and Secret manager"`

*Policy JSON file*:
----
policy.json:
{
    "Statement": [
        {
            "Action": [
                "fsx:DescribeFileSystems",
                "fsx:DescribeVolumes",
                "fsx:CreateVolume",
                "fsx:RestoreVolumeFromSnapshot",
                "fsx:DescribeStorageVirtualMachines",
                "fsx:UntagResource",
                "fsx:UpdateVolume",
                "fsx:TagResource",
                "fsx:DeleteVolume"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": "secretsmanager:GetSecretValue",
            "Effect": "Allow",
            "Resource": "arn:aws:secretsmanager:<aws-region>:<aws-account-id>:secret:<aws-secret-manager-name>*"
        }
    ],
    "Version": "2012-10-17"
}
----

== Create an IAM role for the service account

[role="tabbed-block"]
====

.EKS cluster

--
The following example creates an IAM role for service account in EKS: 

`eksctl create iamserviceaccount --name trident-controller --namespace trident --cluster <my-cluster> --role-name <AmazonEKS_FSxN_CSI_DriverRole> --role-only --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonFSxNCSIDriverPolicy --approve`
--

.AWS CLI

*Create an IAM role:*

--
`aws iam create-role --role-name trident-controller \ --assume-role-policy-document file://trust-relationship.json`

*trust-relationship.json file:*
----
{ 
    "Version": "2012-10-17", 
    "Statement": [ 
        { "Effect": "Allow", 
        "Principal": { 
            "Federated": "arn:aws:iam::<account_id>:oidc-provider/<oidc_provider>" 
        }, 
        "Action": "sts:AssumeRoleWithWebIdentity", 
        "Condition": { 
            "StringEquals": { 
                "<oidc_provider>:aud": "sts.amazonaws.com", 
                "<oidc_provider>:sub": "system:serviceaccount:trident:trident-controller" 
            } 
        } 
    } 
   ] 
}
----

* <*account_id*> -  Your AWS account ID
* <*oidc_provider*> - The OIDC of your EKS cluster. You can obtain the oidc_provider by running:
`aws eks describe-cluster --name my-cluster --query "cluster.identity.oidc.issuer" \ --output text | sed -e "s/^https:\/\///"`

*Attach the IAM role with the IAM policy*:

Once the role has been created, the second step is to attach the policy that was created in the step above to the role using this command:

`aws iam attach-role-policy --role-name my-role \ --policy-arn=arn:aws:<IAM policy>`
--

====



[role="tabbed-block"]
====

.EKS cluster

--
The following example commands install the Astra Trident EKS add-on:

`eksctl create addon --name aws-ebs-csi-driver --cluster <cluster_name> \ --service-account-role-arn arn:aws:iam::<account_id>:role/<role_name> --force`
--

.Management console

--

. Open the Amazon EKS console at https://console.aws.amazon.com/eks/home#/clusters.
. On the left navigation pane, click *Clusters*.
. Click the name of the cluster that you want to configure the NetApp Trident CSI add-on for.
. Click *Add-ons* and then click *Get more add-ons*.
. On the *Select add-ons* page, do the following:
.. In the AWS Marketplace EKS-addons section, select the *Astra Trident by NetApp* check box.
.. Click *Next*.
. On the *Configure selected add-ons* settings page, do the following:
.. Select the *Version* you would like to use.
.. For *Select IAM role*, leave at *Not set*.
.. Expand the *Optional configuration settings*, follow the *Add-on configuration schema* and set the configurationValues parameter on the *Configuration values* section to the role-arn you created on the previous step (value should be in the following format: `eks.amazonaws.com/role-arn: arn:aws:iam::464262061435:role/AmazonEKS_FSXN_CSI_DriverRole`). If you select Override for the Conflict resolution method, one or more of the settings for the existing add-on can be overwritten with the Amazon EKS add-on settings. If you don't enable this option and there's a conflict with your existing settings, the operation fails. You can use the resulting error message to troubleshoot the conflict. Before selecting this option, make sure that the Amazon EKS add-on doesn't manage settings that you need to self-manage.
+
NOTE: When you configure the optional parameter `cloudIdentity`, ensure that you specify `cloudProvider` while installing Trident using the EKS add-on.
+
. Choose *Next*.
. On the *Review and add* page, choose *Create*. 
+
After the add-on installation is complete, you see your installed add-on.
--
====