---
sidebar: sidebar
permalink: trident-use/trident-fsx-storageclass-pvc.html
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident
summary: Using Trident with Amazon FSx for NetApp ONTAP, you can ensure that your Kubernetes clusters running in Amazon Elastic Kubernetes Service (EKS) can provision block and file persistent volumes backed by ONTAP.
---

= Configure a storage class and PVC
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
The https://kubernetes.io/docs/concepts/storage/storage-classes/[Kubernetes StorageClass object^] identifies a provisioner and instructs the provisioner how to provision volumes.  This section shows you how to configure a Kubernetes StorageClass object that specifies Trident as the provisioner. Following that, this sections includes instructions on how to create a PersistentVolumeClaim (PVC) that uses the configured Kubernetes StorageClass to request a PV. If successful, you can then mount the PV to a pod.

== Create a StorageClass Object
There are two ways to configure a StorageClass for use with Trident and FSx for ONTAP:
- Creating a StorageClass with the required parameters to trigger automatic backend configuration.
- Create the Trident backend and then a StorageClass separately.

=== Configure a Kubernetes StorageClass object with automatic backend configuration support for FSx for ONTAP
Trident supports automatic backend configuration for AWS FSx for NetApp ONTAP (FSxN). When you create a StorageClass that includes the required FSxN parameters, Trident automatically creates the corresponding backend and a VolumeSnapshotClass.

=== Understand how automatic backend configuration works
Trident derives backend configuration from the StorageClass definition.
When you apply the StorageClass, Trident validates the required parameters, creates the backend, and annotates the StorageClass with status.

Trident creates the VolumeSnapshotClass only once. Trident reuses the same VolumeSnapshotClass for subsequent StorageClasses.

=== Specify required StorageClass parameters
To trigger automatic backend creation, define the required parameters in the StorageClass `parameters` section.

[cols="2,1,1,3", options="header"]
|===
|Parameter |Required |Type |Description
|`fsxFilesystemID` |Yes |string |FSx for NetApp ONTAP filesystem ID
|`storageDriverName` |Yes |string |Trident storage driver (for example, `ontap-nas` or `ontap-san`)
|`credentialsName` |Yes |string |Name of the Kubernetes Secret that contains FSx for ONTAP credentials
|===

=== Specify optional parameters
You can pass optional backend parameters through the StorageClass. Define all optional values as strings in the StorageClass `parameters` section. For a complete list of backend parameters, see:
xref:trident-fsx-storage-backend.html#backend-advanced-configuration-and-examples[FSx for NetApp ONTAP backend configuration].

=== Create a StorageClass
The following example shows a StorageClass that triggers automatic backend configuration.

[source,yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-fsx-demo
  annotations:
    description: "Demo StorageClass for FSx for NetApp ONTAP"
provisioner: csi.trident.netapp.io
parameters:
  fsxFilesystemID: "fs-0abc123"
  storageDriverName: "ontap-nas"
  credentialsName: trident-fsx-credentials
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
----

After you apply the StorageClass, Trident creates the backend automatically. You can then create PersistentVolumeClaims that reference this StorageClass.

=== Verify backend configuration status
Trident records the result of backend creation in StorageClass annotations.

[cols="2,2", options="header"]
|===
|Annotation |Description
|`trident.netapp.io/configuratorStatus` |Configuration result (`Success` or `Failure`)
|`trident.netapp.io/configuratorMessage` |Detailed status or error message
|`trident.netapp.io/configuratorName` |Name of the internal configurator resource
|`trident.netapp.io/managed` |Indicates the StorageClass is managed by Trident
|`trident.netapp.io/additionalStoragePools` |Storage pools created for this backend
|===

To verify status, run:

[source,bash]
----
kubectl get storageclass ontap-fsx-demo -o yaml
----

Confirm that `trident.netapp.io/configuratorStatus` is set to `Success`.
If the value is `Failure`, review `trident.netapp.io/configuratorMessage` for the error.

== Add additional FSxN file systems
If you need additional storage capacity while continuing to use the same StorageClass, add additional FSxN file system IDs.

Edit the StorageClass and add the following annotation:

[source,yaml]
----
metadata:
  annotations:
    trident.netapp.io/additionalFsxNFileSystemID: '["fs-03cc1a718cddd6e248"]'
----

After you apply the change, Trident updates the backend configuration and updates the StorageClass annotations.

=== Operational considerations and limitations

* Deleting a StorageClass that as the automatic backend configuration usually deletes the associated Trident backend. This can disrupt storage connectivity and break running workloads. Validate the impact before you delete a managed StorageClass.

* Automatic backend configuration is supported only for AWS FSx for NetApp ONTAP.

== Create a Kubernetes StorageClass without automatic backend configuration
If you decide you want to create the Trident backend and StorageClass separately follow these steps.

=== Configure just a Storage Class
You can use this example to setup StorageClass for volumes using NFS (Refer to Trident Attribute section below for the full list of attributes):

[source,YAML]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-gold
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  snapshots: "true"
----

Use this example to setup StorageClass for volumes using iSCSI:

[source,YAML]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-gold
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  provisioningType: "thin"
  snapshots: "true"
----

To provision NFSv3 volumes on AWS Bottlerocket, add the required `mountOptions` to the storage class:

[source,YAML]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-gold
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  media: "ssd"
  provisioningType: "thin"
  snapshots: "true"
mountOptions:
  - nfsvers=3
  - nolock
----

Refer to link:../trident-reference/objects.html[Kubernetes and Trident objects] for details on how storage classes interact with the `PersistentVolumeClaim` and parameters for controlling how Trident provisions volumes. 

=== Create a storage class
Once you have configured the StorageClass, you can create it in Kubernetes.

.Steps
. This is a Kubernetes object, so use `kubectl` to create it in Kubernetes.
+
[source,console]
----
kubectl create -f storage-class-ontapnas.yaml
----

. You should now see a *basic-csi* storage class in both Kubernetes and Trident, and Trident should have discovered the pools on the backend.
+
[source,console]
----
kubectl get sc basic-csi
----
----
NAME         PROVISIONER             AGE
basic-csi    csi.trident.netapp.io   15h

----

== Create the PVC

A https://kubernetes.io/docs/concepts/storage/persistent-volumes[_PersistentVolumeClaim_^] (PVC) is a request for access to the PersistentVolume on the cluster. 

The PVC can be configured to request storage of a certain size or access mode. Using the associated StorageClass, the cluster administrator can control more than PersistentVolume size and access mode--such as performance or service level. 

Once you have created the Trident backend and StorageClass you are ready to create a PVC. Once the PVC has been crated, you can mount the volume in a pod.

=== Sample manifests

.PersistentVolumeClaim sample manifests
[%collapsible]
====
These examples show basic PVC configuration options. 

.PVC with RWX access
This example shows a basic PVC with RWX access that is associated with a StorageClass named `basic-csi`.
[source,YAML]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ontap-gold
----

.PVC using iSCSI example
This example shows a basic PVC for iSCSI with RWO access that is associated with a StorageClass named `protection-gold`.
[source,YAML]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: pvc-san
spec:
accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 1Gi
storageClassName: protection-gold
----
====

=== Create PVC
.Steps

. Create the PVC.
+
[source,console]
----
kubectl create -f pvc.yaml
----
. Verify the PVC status.
+
[source,console]
----
kubectl get pvc
----
----
NAME        STATUS VOLUME     CAPACITY ACCESS MODES STORAGECLASS AGE
pvc-storage Bound  pv-name 2Gi      RWO                       5m
----

Refer to link:../trident-reference/objects.html[Kubernetes and Trident objects] for details on how storage classes interact with the `PersistentVolumeClaim` and parameters for controlling how Trident provisions volumes. 

== Trident attributes

These parameters determine which Trident-managed storage pools should be utilized to provision volumes of a given type.

[cols=",,,,,",options="header",]
|===
|Attribute |Type |Values |Offer |Request |Supported by |media^1^ |string |hdd, hybrid, ssd |Pool contains media of this type; hybrid means both |Media type specified |ontap-nas, ontap-nas-economy, ontap-nas-flexgroup, ontap-san, solidfire-san

|provisioningType |string |thin, thick |Pool supports this provisioning method |Provisioning method specified |thick: all ontap; thin: all ontap & solidfire-san

|backendType |string a| ontap-nas, ontap-nas-economy, ontap-nas-flexgroup, ontap-san, solidfire-san, azure-netapp-files, ontap-san-economy |Pool belongs to this type of backend |Backend specified |All drivers

|snapshots |bool |true, false |Pool supports volumes with snapshots |Volume with snapshots enabled |ontap-nas, ontap-san, solidfire-san

|clones |bool |true, false |Pool supports cloning volumes |Volume with clones enabled |ontap-nas, ontap-san, solidfire-san

|encryption |bool |true, false |Pool supports encrypted volumes |Volume with encryption enabled |ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, ontap-san

|IOPS |int |positive integer |Pool is capable of guaranteeing IOPS in this range |Volume guaranteed these IOPS |solidfire-san
|===

^1^: Not supported by ONTAP Select or FSx for ONTAP systems
