---
sidebar: sidebar
permalink: trident-use/vol-group-snapshots.html
keywords: volumes, on-demand volume group snapshots, csi, csi snapshots, create snapshots, backends, kubernetes, create PVCs, PVCs, snapshot, volume snapshot, import snapshot, recover data
summary: Kubernetes volume snapshots of Persistent Volumes (PVs) enable point-in-time copies of volumes. You can create a snapshot of a volume created using Trident, import a snapshot created outside of Trident, create a new volume from an existing snapshot, and recover volume data from snapshots.  
---

= Work with volume group snapshots
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Kubernetes volume group snapshots of Persistent Volumes (PVs) NetApp Trident provides the ability to create snapshots of multiple volumes ( a group of volume snapshots). This volume group snapshot represents copies from multiple volumes that are taken at the same point-in-time. 

== Create volume group snapshots
Volume group snapshot is supported with the `ontap-san` driver. *<<needs review>>*
.Before you begin

* Ensure that your Kubernetes version is K8s 1.32 or higher.
* You must have an external snapshot controller and Custom Resource Definitions (CRDs) to work with snapshots. This is the responsibility of the Kubernetes orchestrator (for example: Kubeadm, GKE, OpenShift). 
+
If your Kubernetes distribution does not include the external snapshot controller and CRDs, refer to <<Deploy a volume snapshot controller>>.
+
NOTE: Don't create a snapshot controller if creating on-demand volume group snapshots in a GKE environment. GKE uses a built-in, hidden snapshot controller.
+
* In the snapshot controller YAML, set the `CSIVolumeGroupSnapshot` feature gate to 'true' to ensure that volume group snapshot is enabled.
* Create the required storage classes before creating a volume group snapshot.
* Ensure that all PVCs/volumes are be on the same SVM to be able to create VolumeGroupSnapshot. 

.Steps
* Create a VolumeGroupSnapshotClass prior to creating a VolumeGroupSnapshot. For more information, refer to link:../trident-reference/objects.html[VolumeGroupSnapshotClass].
+
[source,yaml]
----
apiVersion: groupsnapshot.storage.k8s.io/v1beta1
kind: VolumeGroupSnapshotClass
metadata:
  name: csi-group-snap-class
  annotations:
    kubernetes.io/description: "Trident group snapshot class"
driver: csi.trident.netapp.io
deletionPolicy: Delete
----
* Create a PVC with required label using existing storage classes.
+
The following example creates the PVC using `pvc1-group-snap` as the data source and label `consistentGroupSnapshot: groupA`.
[source,yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1-group-snap
  labels:
    consistentGroupSnapshot: groupA
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: sc1-1
----
* Create a VolumeGroupSnapshot with the same label (`consistentGroupSnapshot: groupA`) specified in the PVC.
+
This example creates volume group snapshot:
[source,yaml]
----
apiVersion: groupsnapshot.storage.k8s.io/v1beta1
kind: VolumeGroupSnapshot
metadata:
  name: "vgs1"
  namespace: trident
spec:
  volumeGroupSnapshotClassName: csi-group-snap-class
  source:
    selector:
      matchLabels:
        consistentGroupSnapshot: groupA
----

== Import a volume group snapshot

To import a pre-existing volume group snapshot into Kubernetes, you must also import the corresponding individual volume snapshots.

Identify the individual volume snapshot handles, manually construct a VolumeSnapshotContent object first, then create a VolumeSnapshot object pointing to the VolumeSnapshotContent object. Repeat this for every individual volume snapshot.

Then manually create a VolumeGroupSnapshotContent object, specifying the volumeGroupSnapshotHandle and individual volumeSnapshotHandles already existing on the storage system.

.Before you begin 
Trident must have created or imported the group snapshot's parent volume.

.Steps
. *Cluster admin:* Create a `VolumeGroupSnapshotContent` object specifying the `volumeGroupSnapshotHandle` and individual `volumeSnapshotHandles` already existing on the storage system.
+
The following example creates a `VolumeGroupSnapshotContent` object:
+
[source,yaml]
----
apiVersion: groupsnapshot.storage.k8s.io/v1beta1
kind: VolumeGroupSnapshotContent
metadata:
  name: test-group-content
spec:
  deletionPolicy: Delete
  driver: hostpath.csi.k8s.io
  source:
    groupSnapshotHandles:
      volumeGroupSnapshotHandle: e8779136-a93e-11ef-9549-66940726f2fd
      volumeSnapshotHandles:
      - e8779147-a93e-11ef-9549-66940726f2fd
      - e8783cd0-a93e-11ef-9549-66940726f2fd
  volumeGroupSnapshotRef:
    name: test-group-snapshot
    namespace: test-namespace
----
. *Cluster admin:* Create the `VolumeGroupSnapshot` CR that references the `VolumeGroupSnapshotContent` object. This requests access to use the `VolumeGroupSnapshot` in a given namespace.
+
.Example
The following example creates a `VolumeGroupSnapshot` CR named `test-group-snapshot` that references the `VolumeGroupSnapshotContent` named `test-group-content`.
+
[source,yaml]
----
apiVersion: groupsnapshot.storage.k8s.io/v1beta1
kind: VolumeGroupSnapshot
metadata:
  name: test-group-snapshot
  namespace: test-namespace
spec:
  source:
    volumeGroupSnapshotContentName: test-group-content
----
. *Internal processing (no action required):* The external snapshotter recognizes the newly created `VolumeGroupSnapshotContent` and runs the `ListSnapshots` call. Trident creates the `TridentSnapshot`. 
* The external snapshotter sets the `VolumeSnapshotContent` to `readyToUse` and the `VolumeSnapshot` to `true`. 
* Trident returns `readyToUse=true`. 

. *Any user:* Create a `PersistentVolumeClaim` from a new VolumeSnapshot object that is part of a VolumeGroupSnapshot.
+
.Example
The following example creates a PVC referencing the `VolumeSnapshot` named `import-snap`. 
+
[source,yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-restored-snap
  namespace: test-namespace
spec:
  storageClassName: test-snap-sc
  dataSource:
    name: snapshot-0962a745b2bf930bb385b7b50c9b08af471f1a16780726de19429dd9c94eaca0
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 100Mi
----

== Recover volume data using a group snapshot

Use the volume snapshot restore ONTAP CLI to to restore a volume to a state recorded in a prior snapshot. 

----
cluster1::*> volume snapshot restore -vserver vs0 -volume vol3 -snapshot vol3_snap_archive
----

NOTE: When you restore a snapshot copy, the existing volume configuration is overwritten. Changes made to volume data after the snapshot copy was created are lost.

== In-place volume restoration from a snapshot

*<<Review this section>>*

== Delete a PV with associated group snapshots

When deleting a group volume snapshot, you can delete VolumeGroupSnapshots as a whole, not individual snapshots in the group.

== Deploy a volume snapshot controller

If your Kubernetes distribution does not include the snapshot controller and CRDs, you can deploy them as follows.

.Steps

. Create volume snapshot CRDs.
+
----
cat snapshot-setup.sh
----
+
[source,sh]
----
#!/bin/bash
# Create volume snapshot CRDs
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-6.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-6.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-6.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
----
+
. Create the snapshot controller. 
+
[source,console]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-6.1/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
----
+
[source,console]
----
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-6.1/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
----
+
NOTE: If necessary, open `deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml` and update `namespace` to your namespace.
+
. In the `rbac-snapshot-controller.yaml` YAML in Trident, set the `CSIVolumeGroupSnapshot` feature gate to 'true' to ensure that volume group snapshot is enabled.

== Related links

* link:../trident-concepts/vol-group-snapshots.html[Volume snapshots groups]
* link:../trident-reference/objects.html[VolumeSnapshotClass]
* link:../trident-concepts/snapshots.html[Volume snapshots]
