---
sidebar: sidebar
permalink: trident-use/vol-custom-name.html
keywords: volumes, volume name, custom volume name, on-demand volume snapshots, expand volumes, iscsci volumes, nfs volumes, expand, expansion,
summary: Astra Trident supports assigning meaningful names and metadata to the volumes created so that it is easier to identify, monitor manage and easily map the the volumes to respective Kubernetes resources(PVCs).
---

= Customize volume names
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Astra Trident supports assigning meaningful names and metadata to the volumes created to identify, monitor manage and easily map the the volumes to respective Kubernetes resources(PVCs). You can defile custom name templates for volume names and metadata at the backend level and volumes created, imported, or cloned adhere to the name templates.

== Before you begin

Customizable volume names and metadata are compatible with ONTAP on-premises drivers and support the following operations:

1. Customizable volume names support volume create, import, and clone operations.
2. Only the name of the NAS-economy volume complies with the template in the case of NAS-economy volumes.
3. In the case of SAN Economy, only the LUN name complies with the template.
4. Pool volume names for NAS-economy and SAN Economy do not comply with the template as they are transparent to Astra rident users.

== Limitations

1. Customizable volume names are compatible with ONTAP on-premises drivers only.
2. Customizing volume names does not apply to existing volumes.
3. In the case of volume imports, the metadata is updated only if the existing volume has metadata in a specific format. Example: `{"provisioning":{"Cluster":"ClusterA", "PVC": "pvcname"}}`.
4. In the case of volume imports, the virtual storage pool is not applied to imported volume.

== Key behaviors or customizable volume names

. If a failure occurs during the creation or update of a backend, the creation of backend must fail. However, if a failure is observed during volume creation, Astra Trident will fall back to the old naming method.
. If the input templates do not contain uniqueness volume names, Astra Trident will modify the template to ensure that it has unique volume names.
. When you supplies a name template, Astra Trident does not apply the storage prefix. If a storage prefix is necessary, you must incorporate it into the name template.
+
NOTE: Astra Trident does not support the use of a slice operator with the storage prefix.
. If the custom name for a NAS economy volume exceeds 64 characters in length, Astra Trident will fall back to the old naming method. For the other ONTAP drivers if the volume name exceeds the name limit, the volume creation process fails.
. If the name template is correct but the corresponding value is not provided, the phrase `no_value` will be included as part of the volume name.

== Example templates

Custom name templates can be defined at the root level and at the pool level.

.Root level template

----
{
   "version": 1,
   "storageDriverName": "ontap-nas",
   "backendName": "ontap-nfs-backend",
   "managementLIF": "<ip address>",
   "svm": "svm0",
   "username": "<admin>",
   "password": "<password>",
   "defaults": {
                 "nameTemplate": "{{.volume.Name}}_{{.labels.labelname}}_{{.volume.Namespace}}_{{.volume.RequestName}}"
    },
    "labels": {"labelname": "ClusterA", "PVC": "{{.volume.Namespace}}_{{.volume.RequestName}}"}
}

----

.Pool level template

----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "backendName": "ontap-nfs-backend",
  "managementLIF": "<ip address>",
  "svm": "svm0",
 "username": "<admin>",
  "password": "<password>",
  "useREST": true,
  "storage": [
  {
                "labels":{"type":"pool", "template": "{{ .volume.Name }}"},
                "defaults":
                {
                                "nameTemplate": "pool_{{.labels.labelname}}_{{.volume.Namespace}}_{{.volume.RequestName}}"
                }
   },
  ]
}
----
