---
sidebar: sidebar
permalink: trident-use/vol-provision.html
keywords: volumes, pvc, pv, persistentvolume, persistentvolumeclaim, mount, pod, provision
summary: Create a PersistentVolume (PV) and a PersistentVolumeClaim (PVC) that uses the configured Kubernetes StorageClass to request access to the PV. You can then mount the PV to a pod. 
---

= Provision a volume
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Create a PersistentVolumeClaim (PVC) that uses the configured Kubernetes StorageClass to request access to the PV. You can then mount the PV to a pod. 

== Overview
A https://kubernetes.io/docs/concepts/storage/persistent-volumes[_PersistentVolumeClaim_^] (PVC) is a request for access to the PersistentVolume on the cluster. 

The PVC can be configured to request storage of a certain size or access mode. Using the associated StorageClass, the cluster administrator can control more than PersistentVolume size and access mode--such as performance or service level. 

After you create the PVC you can mount the volume in a pod.

== Create the PVC


.Steps

. Create the PVC.
+
----
kubectl create -f pvc.yaml
----
. Verify the PVC status.
+
----
kubectl get pvc
----
----
NAME        STATUS  VOLUME     CAPACITY   ACCESS MODES  STORAGECLASS AGE
pvc-storage Bound   pv-name    1Gi        RWO                  5m
----
. Mount the volume in a pod.
+
----
kubectl create -f pv-pod.yaml
----
+
NOTE: You can monitor the progress using `kubectl get pod --watch`.
. Verify that the volume is mounted on `/my/mount/path`.
+
----
kubectl exec -it task-pv-pod -- df -h /my/mount/path
----
. You can now delete the Pod. The Pod application will no longer exist, but the volume will remain. 
+
----
kubectl delete pod pv-pod
----

=== Sample manifests

.PersistentVolumeClaim sample manifests
[%collapsible]
====
These examples show basic PVC configuration options. 

.PVC with RWO access
This example shows a basic PVC with RWO access that is associated with a StorageClass named `basic-csi`.
[source,yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----

.PVC with NVMe/TCP
This example shows a basic PVC for NVMe/TCP with RWO access that is associated with a StorageClass named `protection-gold`.
[source,yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: pvc-san-nvme
spec:
accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 300Mi
storageClassName: protection-gold
----
====

.Pod manifest samples
[%collapsible]
====
These examples show basic configurations to attach the PVC to a pod. 

.Basic configuration
[source,yaml]
----
kind: Pod
apiVersion: v1
metadata:
  name: pv-pod
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
       claimName: pvc-storage
  containers:
    - name: pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/my/mount/path"
          name: storage
----


.Basic NVMe/TCP configuration
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  volumes:
    - name: basic-pvc
      persistentVolumeClaim:
        claimName: pvc-san-nvme
  containers:
    - name: task-pv-container
      image: nginx
      volumeMounts:
        - mountPath: "/my/mount/path"
          name: basic-pvc
----
====


Refer to link:../trident-reference/objects.html[Kubernetes and Trident objects] for details on how storage classes interact with the `PersistentVolumeClaim` and parameters for controlling how Trident provisions volumes. 



// Create a PVC for a volume that uses the storage class that you just created.

// See `sample-input/pvc-basic-csi.yaml` for an example. Make sure the storage class name matches the one that you created.
// ----
// kubectl create -f sample-input/pvc-basic-csi.yaml

// kubectl get pvc --watch
// NAME      STATUS    VOLUME                                     CAPACITY   ACCESS MODES  STORAGECLASS   AGE
// basic     Pending                                                                       basic          1s
// basic     Pending   pvc-3acb0d1c-b1ae-11e9-8d9f-5254004dfdb7   0                        basic          5s
// basic     Bound     pvc-3acb0d1c-b1ae-11e9-8d9f-5254004dfdb7   1Gi        RWO           basic          7s
