---
sidebar: sidebar
permalink: trident-use/worker-node-prep.html
keywords: storage class, manage storage class, storage classes, kubernetes storage classes, worker node, nfs, iscsi, kubernetes clusters
summary: All of the worker nodes in the Kubernetes cluster need to be able to mount the volumes that you have provisioned for your pods. If you are using the ontap-nas, ontap-nas-economy, ontap-nas-flexgroup driver for one of your backends, your worker nodes need the NFS tools. Otherwise they require the iSCSI tools.
---

= Prepare the worker node
:hardbreaks:
:icons: font
:imagesdir: ../media/

All of the worker nodes in the Kubernetes cluster need to be able to mount the volumes that you have provisioned for your pods. If you are using the `ontap-nas`, `ontap-nas-economy`, or `ontap-nas-flexgroup` driver for one of your backends, your worker nodes need the NFS tools. Otherwise they require the iSCSI tools.

Recent versions of RedHat CoreOS have both NFS and iSCSI installed by default.

WARNING: You should always reboot your worker nodes after installing the NFS or iSCSI tools, or else attaching volumes to containers might fail.

== Node service discovery

Beginning in 22.07, Astra Trident automatically detects if the node is capable of running iSCSI or NFS services. Astra Trident creates events for the node to identify the services discovered. You can review these events using the command:

----
kubectl get event -A --field-selector involvedObject.name=<Kubernetes node name>
----

Trident also identifies services enabled for each node on the Trident node CR. To view the discovered services, use the command:

----
tridentctl get node -o wide -n <Trident namespace>
----

NOTE: Node service discovery identifies discovered services but does not guarantee services are properly configured. Conversely, the absence of a discovered service does not guarantee the volume mount will fail. 

== NFS volumes

[%header,cols=3*]
|===
|Protocol
|Operating system
|Commands

|NFS
a|RHEL/CentOS
a|`sudo yum install -y nfs-utils`

|NFS
a|Ubuntu/Debian
a|`sudo apt-get install -y nfs-common`

|===

NOTE: You should ensure that the NFS service is started up during boot time.

== iSCSI volumes

Consider the following when using iSCSI volumes:

* Each node in the Kubernetes cluster must have a unique IQN. *This is a necessary prerequisite*.
* If using RHCOS version 4.5 or later, or RHEL or CentOS version 8.2 or later with the `solidfire-san` driver, ensure that the CHAP authentication algorithm is set to MD5 in `/etc/iscsi/iscsid.conf`.
+
----
sudo sed -i 's/^\(node.session.auth.chap_algs\).*/\1 = MD5/' /etc/iscsi/iscsid.conf
----
* When using worker nodes that run RHEL/RedHat CoreOS with iSCSI PVs, make sure to specify the `discard` mountOption in the StorageClass to perform inline space reclamation. See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems[RedHat’s documentation^].

[%header,cols=3*]
|===
|Protocol
|Operating system
|Commands

|iSCSI
a|RHEL/CentOS
a|
. Install the following system packages:
+
`sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath`
. Check that iscsi-initiator-utils version is 6.2.0.874-2.el7 or later:
+
`rpm -q iscsi-initiator-utils`
. Set scanning to manual:
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`
. Enable multipathing:
+
`sudo mpathconf --enable --with_multipathd y --find_multipaths n`
+
NOTE: Ensure `etc/multipath.conf` contains `find_multipaths no` under `defaults`.

. Ensure that `iscsid` and `multipathd` are running:
+
`sudo systemctl enable --now iscsid multipathd`
. Enable and start `iscsi`:
+
`sudo systemctl enable --now iscsi`

|iSCSI
a|Ubuntu/Debian
a|
. Install the following system packages:
+
`sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools`
. Check that open-iscsi version is 2.0.874-5ubuntu2.10 or later (for bionic) or 2.0.874-7.1ubuntu6.1 or later (for focal):
+
`dpkg -l open-iscsi`
. Set scanning to manual:
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`
. Enable multipathing:
+
`sudo tee /etc/multipath.conf <<-'EOF'
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart`
+
NOTE: Ensure `etc/multipath.conf` contains `find_multipaths no` under `defaults`.

. Ensure that `open-iscsi` and `multipath-tools` are enabled and running:
+
`sudo systemctl status multipath-tools`
`sudo systemctl enable --now open-iscsi.service`
`sudo systemctl status open-iscsi`

|===

NOTE: For Ubuntu 18.04, you must discover target ports with `iscsiadm` before starting `open-iscsi` for the iSCSI daemon to start. You can alternatively modify the `iscsi` service to start `iscsid` automatically.
