---
sidebar: sidebar
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry
summary: You can deploy the Trident operator and install Trident using Helm. This process applies to installations where the container images required by Trident are stored in a private registry.   
---

= Deploy Trident operator using Helm (Offline mode)
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You can deploy the Trident operator and install Trident using Helm. This process applies to installations where the container images required by Trident are stored in a private registry. If you do not have a private image registry, use the link:kubernetes-deploy-helm.html[process for standard deployment].

== Critical information about Trident 25.06
*You must read the following critical information about Trident.*

// Start snippet: collapsible block (open on page load)
.*Critical information about Trident*
[%collapsible%open]
====
=======
* Kubernetes 1.33 is now supported in Trident. Upgrade Trident prior to upgrading Kubernetes.
* Trident strictly enforces the use of multipathing configuration in SAN environments, with a recommended value of `find_multipaths: no` in multipath.conf file. 
+
Use of non-multipathing configuration or use of `find_multipaths: yes` or `find_multipaths: smart` value in multipath.conf file will result in mount failures. Trident has recommended the use of `find_multipaths: no` since the 21.07 release.
====
// End snippet

== Deploy the Trident operator and install Trident using Helm

Using the Trident link:https://netapp.github.io/trident-helm-chart[Helm Chart^] you can deploy the Trident operator and install Trident in one step.  

Review link:../trident-get-started/kubernetes-deploy.html[the installation overview] to ensure you've met installation prerequisites and selected the correct installation option for your environment.

.Before you begin

In addition to the link:../trident-get-started/kubernetes-deploy.html#before-you-deploy[deployment prerequisites] you need link:https://v3.helm.sh/[Helm version 3^].

IMPORTANT: When installing Trident in a private repository, if you are using the `imageRegistry` switch to specify the repository location, do not use `/netapp/` in the repository path.

.Steps

. Add the Trident Helm repository:
+
[source,console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----

. Use `helm install` and specify a name for your deployment and image registry location. Your link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions[Trident and CSI images] can be located in one registry or different registries, but all CSI images must be located in the same registry. In the examples, `100.2506.0` is the version of Trident you are installing. 
+
[role="tabbed-block"]
====

.Images in one registry
--
[source,console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--

.Images in different registries
--
[source,console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --set operatorImage=<your-registry>/trident-operator:25.06.0 --set tridentAutosupportImage=<your-registry>/trident-autosupport:25.06 --set tridentImage=<your-registry>/trident:25.06.0 --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
====
// end tabbed area
+
NOTE: If you already created a namespace for Trident, the `--create-namespace` parameter will not create an additional namespace.

You can use `helm list` to review installation details such as name, namespace, chart, status, app version, and revision number.


== Pass configuration data during install

There are two ways to pass configuration data during the install:

[cols=2,options="header"]
|===
|Option
|Description

|`--values` (or `-f`)
a|Specify a YAML file with overrides. This can be specified multiple times and the rightmost file will take precedence.

|`--set`
a|Specify overrides on the command line.

|===

For example, to change the default value of `debug`, run the following command where `100.2506.0` is the version of Trident you are installing:
[source,console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----

To add the nodePrep value, run the following command: 
[source,console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set nodePrep={iscsi}
----

== Configuration options
This table and the `values.yaml` file, which is part of the Helm chart, provide the list of keys and their default values.

WARNING: Do not remove the default affinity from the values.yaml file. When you want to provide a custom affinity, extend the default affinity.

[cols=3,options="header"]
|===
|Option
|Description
|Default

|`nodeSelector` 
|Node labels for pod assignment
|

|`podAnnotations`
|Pod annotations
|

|`deploymentAnnotations`
|Deployment annotations
|

|`tolerations`
|Tolerations for pod assignment
|

|`affinity`
|Affinity for pod assignment
a| 
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux 
----

WARNING: Do not remove the default affinity from the values.yaml file. When you want to provide a custom affinity, extend the default affinity.

|`tridentControllerPluginNodeSelector`
|Additional node selectors for pods. Refer to link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods[Understanding controller pods and node pods] for details.
|

|`tridentControllerPluginTolerations`
|Overrides Kubernetes tolerations for pods. Refer to link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods[Understanding controller pods and node pods] for details. 
|

|`tridentNodePluginNodeSelector`
|Additional node selectors for pods. Refer to link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods[Understanding controller pods and node pods] for details. 
|

|`tridentNodePluginTolerations`
|Overrides Kubernetes tolerations for pods. Refer to link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods[Understanding controller pods and node pods] for details. 
|

|`imageRegistry`
|Identifies the registry for the `trident-operator`, `trident`, and other images. Leave empty to accept the default.

IMPORTANT: When installing Trident in a private repository, if you are using the `imageRegistry` switch to specify the repository location, do not use `/netapp/` in the repository path.
|""

|`imagePullPolicy`
|Sets the image pull policy for the `trident-operator`.
|`IfNotPresent`

|`imagePullSecrets`
|Sets the image pull secrets for the `trident-operator`, `trident`, and other images.
|

|`kubeletDir`
|Allows overriding the host location of kubelet's internal state.
|`"/var/lib/kubelet"`

|`operatorLogLevel`
|Allows the log level of the Trident operator to be set to: `trace`, `debug`, `info`, `warn`, `error`, or `fatal`.
|`"info"`

|`operatorDebug`
| Allows the log level of the Trident operator to be set to debug.
|`true`

|`operatorImage`
|Allows the complete override of the image for `trident-operator`.
|""

|`operatorImageTag`
|Allows overriding the tag of the `trident-operator` image.
|""

|`tridentIPv6`
|Allows enabling Trident to work in IPv6 clusters.
|`false`

|`tridentK8sTimeout`
a|Overrides the default 180-second timeout for most Kubernetes API operations (if non-zero, in seconds).

NOTE: The `tridentK8sTimeout` parameter is applicable only for Trident installation. 
|`180`

|`tridentHttpRequestTimeout`
|Overrides the default 90-second timeout for the HTTP requests, with `0s` being an infinite duration for the timeout. Negative values are not allowed.
|`"90s"`

|`tridentSilenceAutosupport`
|Allows disabling Trident periodic AutoSupport reporting.
|`false`

|`tridentAutosupportImageTag`
|Allows overriding the tag of the image for Trident AutoSupport container.
|`<version>`

|`tridentAutosupportProxy`
|Enables Trident AutoSupport container to phone home via an HTTP proxy.
|""

|`tridentLogFormat`
|Sets the Trident logging format (`text` or `json`).
|`"text"`

|`tridentDisableAuditLog`
|Disables Trident audit logger.
|`true`

|`tridentLogLevel`
|Allows the log level of Trident to be set to: `trace`, `debug`, `info`, `warn`, `error`, or `fatal`.
|`"info"`

|`tridentDebug`
|Allows the log level of Trident to be set to `debug`.
|`false`

|`tridentLogWorkflows`
|Allows specific Trident workflows to be enabled for trace logging or log suppression.
|""

|`tridentLogLayers`
|Allows specific Trident layers to be enabled for trace logging or log suppression.
|""

|`tridentImage`
|Allows the complete override of the image for Trident.
|""

|`tridentImageTag`
|Allows overriding the tag of the image for Trident.
|""

|`tridentProbePort`
|Allows overriding the default port used for Kubernetes liveness/readiness probes.
|""

|`windows`
|Enables Trident to be installed on Windows worker node.
|`false`

|`enableForceDetach`
|Allows enabling the force detach feature.
|`false`

|`excludePodSecurityPolicy`
|Excludes the operator pod security policy from creation.
|`false`

|`nodePrep`
a|Enables Trident to prepare the nodes of the Kubernetes cluster to manage volumes using the specified data storage protocol.
*Currently, `iscsi` is the only value supported.*

NOTE: Beginning with OpenShift 4.19, the minimum Trident version supported for this feature is 25.06.1.
|

|===
