---
sidebar: sidebar
permalink: trident-get-started/kubernetes-deploy-helm.html
keywords: deploy, astra trident, operator, helm, helm chart, configuration, values, standard, registry
summary: You can deploy the Trident operator and install Astra Trident using Helm. This process applies to installations where the container images required by Astra Trident are not stored in a private registry.
---

= Deploy Trident operator using Helm (Standard mode)
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You can deploy the Trident operator and install Astra Trident using Helm. This process applies to installations where the container images required by Astra Trident are not stored in a private registry. If you do have a private image registry, use the link:kubernetes-deploy-helm-mirror.html[process for offline deployment].

== Critical information about Astra Trident 24.02
*You must read the following critical information about Astra Trident.*

// Start snippet: collapsible block (open on page load)
.*Critical information about Astra Trident*
[%collapsible%open]
====
* Kubernetes 1.27 is now supported in Trident. Upgrade Trident prior to upgrading Kubernetes.
* Astra Trident strictly enforces the use of multipathing configuration in SAN environments, with a recommended value of `find_multipaths: no` in multipath.conf file. 
+
Use of non-multipathing configuration or use of `find_multipaths: yes` or `find_multipaths: smart` value in multipath.conf file will result in mount failures. Trident has recommended the use of `find_multipaths: no` since the 21.07 release.
====
// End snippet

== Deploy the Trident operator and install Astra Trident using Helm
Using the Trident link:https://artifacthub.io/packages/helm/netapp-trident/trident-operator[Helm Chart^] you can deploy the Trident operator and install Trident in one step. 

Review link:../trident-get-started/kubernetes-deploy.html[the installation overview] to ensure you've met installation prerequisites and selected the correct installation option for your environment.

.Before you begin

In addition to the link:../trident-get-started/kubernetes-deploy.html#before-you-deploy[deployment prerequisites] you need link:https://v3.helm.sh/[Helm version 3^].

.Steps

. Add the Astra Trident Helm repository:
+
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----

. Use `helm install` and specify a name for your deployment as in the following example where `100.2402.0` is the version of Astra Trident you are installing. 
+
----
helm install <name> netapp-trident/trident-operator --version 100.2402.0 --create-namespace --namespace <trident-namespace>
----
+
NOTE: If you already created a namespace for Trident, the `--create-namespace` parameter will not create an additional namespace.

You can use `helm list` to review installation details such as name, namespace, chart, status, app version, and revision number.


== Pass configuration data during install

There are two ways to pass configuration data during the install:

[cols=2,options="header"]
|===
|Option
|Description

|`--values` (or `-f`)
a|Specify a YAML file with overrides. This can be specified multiple times and the rightmost file will take precedence.

|`--set`
a|Specify overrides on the command line.

|===

For example, to change the default value of `debug`, run the following `--set` command where `100.2402.0` is the version of Astra Trident you are installing:

----
helm install <name> netapp-trident/trident-operator --version 100.2402.0  --create-namespace --namespace trident --set tridentDebug=true
----

== Configuration options
This table and the `values.yaml` file, which is part of the Helm chart, provide the list of keys and their default values. 

[cols="1,2,1",options="header"]
|===
|Option
|Description
|Default

|`nodeSelector` 
|Node labels for pod assignment
|

|`podAnnotations`
|Pod annotations
|

|`deploymentAnnotations`
|Deployment annotations
|

|`tolerations`
|Tolerations for pod assignment
|

|`affinity`
|Affinity for pod assignment
|

|`tridentControllerPluginNodeSelector`
|Additional node selectors for pods. Refer to <<Understanding controller pods and node pods>> for details. 
|

|`tridentControllerPluginTolerations`
|Overrides Kubernetes tolerations for pods. Refer to <<Understanding controller pods and node pods>> for details. 
|

|`tridentNodePluginNodeSelector`
|Additional node selectors for pods. Refer to <<Understanding controller pods and node pods>> for details. 
|

|`tridentNodePluginTolerations`
|Overrides Kubernetes tolerations for pods. Refer to <<Understanding controller pods and node pods>> for details. 
|

|`imageRegistry`
|Identifies the registry for the `trident-operator`, `trident`, and other images.  Leave empty to accept the default.
|`""`

|`imagePullPolicy`
|Sets the image pull policy for the `trident-operator`.
|`IfNotPresent`

|`imagePullSecrets`
|Sets the image pull secrets for the `trident-operator`, `trident`, and other images.
|

|`kubeletDir`
|Allows overriding the host location of kubelet's internal state.
|`"/var/lib/kubelet"`

|`operatorLogLevel`
|Allows the log level of the Trident operator to be set to: `trace`, `debug`, `info`, `warn`, `error`, or `fatal`.
|`"info"`

|`operatorDebug`
| Allows the log level of the Trident operator to be set to debug.
|`true`

|`operatorImage`
|Allows the complete override of the image for `trident-operator`.
|`""`

|`operatorImageTag`
|Allows overriding the tag of the `trident-operator` image.
|`""`

|`tridentIPv6`
|Allows enabling Astra Trident to work in IPv6 clusters.
|`false`

|`tridentK8sTimeout`
|Overrides the default 30-second timeout for most Kubernetes API operations (if non-zero, in seconds).
|`0`

|`tridentHttpRequestTimeout`
|Overrides the default 90-second timeout for the HTTP requests, with `0s` being an infinite duration for the timeout. Negative values are not allowed.
|`"90s"`

|`tridentSilenceAutosupport`
|Allows disabling Astra Trident periodic AutoSupport reporting.
|`false`

|`tridentAutosupportImageTag`
|Allows overriding the tag of the image for Astra Trident AutoSupport container.
|`<version>`

|`tridentAutosupportProxy`
|Allows Astra Trident AutoSupport container to phone home via an HTTP proxy.
|`""`

|`tridentLogFormat`
|Sets the Astra Trident logging format (`text` or `json`).
|`"text"`

|`tridentDisableAuditLog`
|Disables Astra Trident audit logger.
|`true`

|`tridentLogLevel`
|Allows the log level of Astra Trident to be set to: `trace`, `debug`, `info`, `warn`, `error`, or `fatal`.
|`"info"`

|`tridentDebug`
|Allows the log level of Astra Trident to be set to `debug`.
|`false`

|`tridentLogWorkflows`
|Allows specific Astra Trident workflows to be enabled for trace logging or log suppression.
|`""`

|`tridentLogLayers`
|Allows specific Astra Trident layers to be enabled for trace logging or log suppression.
|`""`

|`tridentImage`
|Allows the complete override of the image for Astra Trident.
|`""`

|`tridentImageTag`
|Allows overriding the tag of the image for Astra Trident.
|`""`

|`tridentProbePort`
|Allows overriding the default port used for Kubernetes liveness/readiness probes.
|`""`

|`windows`
|Allows Astra Trident to be installed on Windows worker node.
|`false`

|`enableForceDetach`
|Allows enabling the force detach feature.
|`false`

|`excludePodSecurityPolicy`
|Excludes the operator pod security policy from creation.
|`false`

|`cloudProvider` | Set to `"Azure"` when using managed identities or a cloud identity on an AKS cluster. Set to "AWS" when using a cloud identity on an EKS cluster. |`""` 

|`cloudIdentity` |Set to workload identity ("azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx") when using cloud identity on an AKS cluster. Set to AWS IAM role ("'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/astratrident-role'") when using cloud identity on an EKS cluster.|`""`

|`iscsiSelfHealingInterval` |The interval at which the iSCSI self-healing is invoked.|`5m0s`

|`iscsiSelfHealingWaitTime` |The duration after which iSCSI self-healing initiates an attempt to resolve a stale session by performing a logout and subsequent login.|`7m0s`

|===

=== Understanding controller pods and node pods
Astra Trident runs as a single controller pod, plus a node pod on each worker node in the cluster. The node pod must be running on any host where you want to potentially mount an Astra Trident volume. 

Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/[node selectors^] and link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[tolerations and taints^] are used to constrain a pod to run on a specific or preferred node. Using the`ControllerPlugin` and `NodePlugin`, you can specify constraints and overrides.

* The controller plugin handles volume provisioning and management, such as snapshots and resizing. 
* The node plugin handles attaching the storage to the node.