##Trident protect provides filesystem freeze and unfreeze capabilities for KubeVirt virtual machines during data protection operations to ensure data consistency. The configuration method and default behavior for VM freeze operations varies across Trident protect versions, with newer releases offering simplified configuration through Helm chart parameters.##

NOTE: During restore operations, any `VirtualMachineSnapshots` created for a virtual machine (VM) are not restored.

//astractl-35903 update

.##Trident protect 25.10 and newer##
[%collapsible%open]
====
Trident protect automatically freezes and unfreezes KubeVirt filesystems during data protection operations to ensure consistency. Beginning with Trident protect 25.10, you can disable this behavior using the `vm.freeze` parameter during Helm chart installation. The parameter is enabled by default.

[source,console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --set vm.freeze=false --version 100.2510.0 --create-namespace --namespace trident-protect
----
//ASTRACTL-36239 update: Added --set vm.freeze=false to the helm install command above.
====

.Trident protect 24.10.1 to 25.06
[%collapsible]
====
Beginning with Trident protect 24.10.1, Trident protect automatically freezes and unfreezes KubeVirt filesystems during data protection operations. Optionally, you can disable this automatic behavior using the following command:

[source,console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----
====
.Trident protect 24.10
[%collapsible]
====
Trident protect 24.10 does not automatically ensure a consistent state for KubeVirt VM filesystems during data protection operations. If you want to protect your KubeVirt VM data using Trident protect 24.10, you need to manually enable the freeze/unfreeze functionality for the filesystems before the data protection operation. This ensures that the filesystems are in a consistent state.

You can configure Trident protect 24.10 to manage the freezing and unfreezing of the VM filesystem during data protection operations by link:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html[configuring virtualization^] and then using the following command:
[source,console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
====
