== Namespace annotations and labels during restore and failover operations

During restore and failover operations, labels and annotations in the destination namespace are made to match the labels and annotations in the source namespace. Any labels or annotations from the source namespace that don't exist in the destination namespace are added, and any keys that already exist are overwritten.

You can prevent specific annotations in the destination namespace from being overwritten by setting the Kubernetes environment variable `RESTORE_SKIP_NAMESPACE_ANNOTATIONS` before you perform the restore or failover operation. For example:

[source,console]
-----
k set env deploy/trident-protect-controller-manager RESTORE_SKIP_NAMESPACE_ANNOTATIONS=<annotation_key_to skip_1>,<annotation_key_to skip_2>
-----

If you installed Trident protect using Helm with the `--create-namespace` flag, special treatment is given to the `name` label key. During the restore or failover process, Trident protect copies this label to the destination namespace, but updates the value to the destination namespace value if the value from source matches the source namespace. If this value doesn't match the source namespace it is copied to the destination namespace with no changes. 

=== Example
In the following example, there are two namespaces with different annotations and labels. You can see the state of the destination namespace before and after the restore or failover operation, and how the annotations and labels are combined or overwritten in the destination namespace.

==== Before the restore or failover operation
The following table illustrates the state of the example source and destination namespaces before the restore or failover operation:

[cols="1,2a,2a" options="header"]
|===
|Namespace |Annotations |Labels

|Namespace ns-1 (source)
|
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"
|
* environment=production
* compliance=hipaa
* name=ns-1

|Namespace ns-2 (destination)
|
* annotation.one/key: "true"
* annotation.three/key: "false"
|
* role=database
|===

==== After the restore operation
The following table illustrates the state of the example destination namespace after the restore or failover operation. Some keys have been added, some have been overwritten, and the `name` label has been updated to match the destination namespace:

[cols="1,2a,2a" options="header"]
|===
|Namespace |Annotations |Labels

|Namespace ns-2 (destination)
|
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"
* annotation.three/key: "false"
|
* name=ns-2
* compliance=hipaa
* environment=production
* role=database
|===