== Namespace annotations and labels during restore and failover operations

During restore and failover operations, labels and annotations in the destination namespace are made to match the labels and annotations in the source namespace. Labels or annotations from the source namespace that don't exist in the destination namespace are added, and any labels or annotations that already exist are overwritten to match the value from the source namespace. Labels or annotations that exist only on the destination namespace remain unchanged.

NOTE: If you use RedHat OpenShift, it's important to note the critical role of namespace annotations in OpenShift environments. Namespace annotations ensure that restored pods adhere to the appropriate permissions and security configurations defined by OpenShift security context constraints (SCCs) and can access volumes without permission issues. For more information, refer to the https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/authentication_and_authorization/managing-pod-security-policies[OpenShift security context constraints documentation^].

You can prevent specific annotations in the destination namespace from being overwritten by setting the Kubernetes environment variable `RESTORE_SKIP_NAMESPACE_ANNOTATIONS` before you perform the restore or failover operation. For example:

[source,console]
-----
kubectl set env -n trident-protect deploy/trident-protect-controller-manager RESTORE_SKIP_NAMESPACE_ANNOTATIONS=<annotation_key_to_skip_1>,<annotation_key_to_skip_2>
-----

If you installed the source application using Helm with the `--create-namespace` flag, special treatment is given to the `name` label key. During the restore or failover process, Trident protect copies this label to the destination namespace, but updates the value to the destination namespace value if the value from source matches the source namespace. If this value doesn't match the source namespace it is copied to the destination namespace with no changes. 

=== Example
The following example presents a source and destination namespace, each with different annotations and labels. You can see the state of the destination namespace before and after the operation, and how the annotations and labels are combined or overwritten in the destination namespace.

==== Before the restore or failover operation
The following table illustrates the state of the example source and destination namespaces before the restore or failover operation:

[cols="1,2a,2a" options="header"]
|===
|Namespace |Annotations |Labels

|Namespace ns-1 (source)
|
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"
|
* environment=production
* compliance=hipaa
* name=ns-1

|Namespace ns-2 (destination)
|
* annotation.one/key: "true"
* annotation.three/key: "false"
|
* role=database
|===

==== After the restore operation
The following table illustrates the state of the example destination namespace after the restore or failover operation. Some keys have been added, some have been overwritten, and the `name` label has been updated to match the destination namespace:

[cols="1,2a,2a" options="header"]
|===
|Namespace |Annotations |Labels

|Namespace ns-2 (destination)
|
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"
* annotation.three/key: "false"
|
* name=ns-2
* compliance=hipaa
* environment=production
* role=database
|===