---
sidebar: sidebar
permalink: trident-get-started/intro.html
keywords: product overview, Trident, fsx, element, google cloud, cvs, architecture, test drive, node pod, controller pod, pods, csi, sidecar
summary: Trident is a fully supported open source project maintained by NetApp. It has been designed to help you meet your containerized application's persistence demands using industry-standard interfaces, such as the Container Storage Interface (CSI).
---

= Learn about Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Trident is a fully-supported open source project maintained by NetApp. It has been designed to help you meet your containerized application's persistence demands using industry-standard interfaces, such as the Container Storage Interface (CSI).

== What is Trident?
Netapp Trident enables consumption and management of storage resources across all popular NetApp storage platforms, in the public cloud or on premises, including ONTAP (AFF, FAS, Select, Cloud, Amazon FSx for NetApp ONTAP), Element software (NetApp HCI, SolidFire), Azure NetApp Files service, and Cloud Volumes Service on Google Cloud. 

Trident is a Container Storage Interface (CSI) compliant dynamic storage orchestrator that natively integrates with link:https://kubernetes.io/[Kubernetes^]. Trident runs as a single Controller Pod plus a Node Pod on each worker node in the cluster. Refer to link:../trident-get-started/architecture.html[Trident architecture] for details. 

Trident also provides direct integration with the Docker ecosystem for NetApp storage platforms. The NetApp Docker Volume Plugin (nDVP) supports the provisioning and management of storage resources from the storage platform to Docker hosts. Refer to link:../trident-docker/deploy-docker.html[Deploy Trident for Docker] for details.

NOTE: If this is your first time using Kubernetes, you should familiarize yourself with the link:https://kubernetes.io/docs/home/[Kubernetes concepts and tools^].

== Take the Trident test drive
To take a test drive, request access to the "Easily Deploy and Clone Persistent Storage for Containerized Workloads" link:https://www.netapp.com/us/try-and-buy/test-drive/index.aspx[NetApp Test Drive^] using a ready-to-use lab image. The test drive provides a sandbox environment with a three-node Kubernetes cluster and Trident installed and configured. This is a great way to familiarize yourself with Trident and explore its features.

Another option is the link:https://kubernetes.io/docs/setup/independent/install-kubeadm/[kubeadm Install Guide] provided by Kubernetes.

NOTE: Don't use a Kubernetes cluster that you build using these instructions in a production environment. Use the production deployment guides provided by your distribution for production-ready clusters.

== Kubernetes integration with NetApp products
The NetApp portfolio of storage products integrates with many aspects of a Kubernetes cluster, providing advanced data management capabilities, which enhance the functionality, capability, performance, and availability of the Kubernetes deployment.

.Amazon FSx for NetApp ONTAP
[%collapsible%closed]
====

link:https://www.netapp.com/aws/fsx-ontap/[Amazon FSx for NetApp ONTAP^] is a fully managed AWS service that lets you launch and run file systems powered by the NetApp ONTAP storage operating system. 
====

.Azure NetApp Files
[%collapsible%closed]
====

https://www.netapp.com/azure/azure-netapp-files/[Azure NetApp Files^] is an enterprise-grade Azure file share service, powered by NetApp. You can run your most demanding file-based workloads in Azure natively, with the performance and rich data management you expect from NetApp.
====

.Cloud Volumes ONTAP
[%collapsible%closed]
====

link:https://www.netapp.com/cloud-services/cloud-volumes-ontap/[Cloud Volumes ONTAP^] is a software-only storage appliance that runs the ONTAP data management software in the cloud. 
====

.Cloud Volumes Service for Google Cloud
[%collapsible%closed]
====

link:https://bluexp.netapp.com/google-cloud-netapp-volumes?utm_source=GitHub&utm_campaign=Trident[NetApp Cloud Volumes Service for Google Cloud^] is a cloud native file service that provides NAS volumes over NFS and SMB with all-flash performance. 
====

.Element software
[%collapsible%closed]
====

https://www.netapp.com/data-management/element-software/[Element^] enables the storage administrator to consolidate workloads by guaranteeing performance and enabling a simplified and streamlined storage footprint. 
====

.NetApp HCI
[%collapsible%closed]
====

link:https://docs.netapp.com/us-en/hci/docs/concept_hci_product_overview.html[NetApp HCI^] simplifies the management and scale of the datacenter by automating routine tasks and enabling infrastructure administrators to focus on more important functions.

Trident can provision and manage storage devices for containerized applications directly against the underlying NetApp HCI storage platform.
====

.NetApp ONTAP
[%collapsible%closed]
====

link:https://docs.netapp.com/us-en/ontap/index.html[NetApp ONTAP^] is the NetApp multiprotocol, unified storage operating system that provides advanced data management capabilities for any application. 

ONTAP systems have all-flash, hybrid, or all-HDD configurations and offer many different deployment models, including engineered hardware (FAS and AFF), white-box (ONTAP Select), and cloud-only (Cloud Volumes ONTAP). Trident supports these ONTAP deployment models.
====