---
sidebar: sidebar
permalink: trident-get-started/known-issues.html
keywords: bugs, known issues, problems, fixed  issues
summary: Known issues identify problems that might prevent you from using the product successfully.
---

= Known issues and fixed issues
:hardbreaks:
:icons: font
:imagesdir: ../media/

Known issues identify problems that might prevent you from using the product successfully.

* When using a backend across multiple Trident instances, each backend configuration file should have a different `storagePrefix` value for ONTAP backends or use a different `TenantName` for SolidFire backends. Trident cannot detect volumes that other instances of Trident have created. Attempting to create an existing volume on either ONTAP or SolidFire backends succeeds, because Trident treats volume creation as an idempotent operation. If `storagePrefix` or `TenantName` do not differ, there might be name collisions for volumes created on the same backend.

* When installing Trident (using `tridentctl` or the Trident Operator) and using `tridentctl` to manage Trident, you should ensure the `KUBECONFIG` environment variable is set. This is necessary to indicate the Kubernetes cluster that `tridentctl` should work against. When working with multiple Kubernetes environments, you should ensure that the `KUBECONFIG` file is sourced accurately.

* To perform online space reclamation for iSCSI PVs, the underlying OS on the worker node might require mount options to be passed to the volume. This is true for RHEL/RedHat CoreOS instances, which require the `discard` https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems[mount option^]; ensure that the discard mountOption is included in your https://kubernetes.io/docs/concepts/storage/storage-classes/[`StorageClass`^] to support online block discard.

* If you have more than one instance of Trident per Kubernetes cluster, Trident cannot communicate with other instances and cannot discover other volumes that they have created, which leads to unexpected and incorrect behavior if more than one instance runs within a cluster. There should be only one instance of Trident per Kubernetes cluster.

* If Trident-based `StorageClass` objects are deleted from Kubernetes while Trident is offline, Trident does not remove the corresponding storage classes from its database when it comes back online. You should delete these storage classes using `tridentctl` or the REST API.

* If a user deletes a PV provisioned by Trident before deleting the corresponding PVC, Trident does not automatically delete the backing volume. You should remove the volume via `tridentctl` or the REST API.

* ONTAP cannot concurrently provision more than one FlexGroup at a time unless the set of aggregates are unique to each provisioning request.

* When using Trident over IPv6, you should specify `managementLIF` and `dataLIF` in the backend definition within square brackets. For example, ``[fd20:8b1e:b258:2000:f816:3eff:feec:0]``.

* If using the `solidfire-san` driver with OpenShift 4.5, ensure that the underlying worker nodes use MD5 as the CHAP authentication algorithm. See Worker node Preparation for instructions.

== Fixed issues

* When using Trident 20.07.1 for non-CSI deployments [Kubernetes 1.11 - 1.13], you might observe existing igroups being cleared of all existing IQNs. This has been fixed in the 20.10 release of Trident. This can only be observed when Trident initializes a backend/restarts if scheduled on a new node.
+
TIP: We recommend that you upgrade to 20.10.

* An upstream Kubernetes bug that could be encountered when rapidly attaching/detaching volumes is fixed with Trident 20.07.1 and the v2.0.1 release of the CSI external-provisioner sidecar. Trident v20.07.1 will use the 2.0.1 release of the external-provisioner sidecar for all Kubernetes clusters running 1.17 and later. If you are using Kubernetes 1.16 or earlier, you should upgrade your Kubernetes cluster to 1.17 or later.

* A previously identified issue with updating the storage prefix for a Trident backend is resolved with Trident 20.07.1. You can work with backends that use an empty storage prefix ("") or one that includes ``"-"``.

* Trident 20.07.1 using the 2.0.1 release of the CSI external-provisioner sidecar enforces a blank fsType (fsType="") for volumes that do not have the fsType in their StorageClass. When working with Kubernetes 1.17 or later, upgrading to Trident 20.07.1 would enable you to provide a blank fsType for NFS volumes. For iSCSI volumes, if you are enforcing an fsGroup using a Security Context, you are required to set the fsType on your StorageClass.

* Trident 20.07.1 improves the resiliency for iSCSI volumes. The v20.07.0 release implements multiple additional checks that eliminate accidental deletions from occurring.

* The bug where Trident creates multiple unintended secrets when it attempts to patch Trident service accounts is fixed in 20.07.1.
