---
sidebar: sidebar
permalink: trident-get-started/kubernetes-deploy-tridentctl.html
keywords: deploy, astra trident, methods, tridentctl, windows
summary: You can deploy Astra Trident by using `tridentctl`.
---

= Deploy with `tridentctl`
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You can install Astra Trident using `tridentctl`. This process applies to installations where Trident and CSI images are located in a `docker.io` and `registry.k8s.io` or a private, mirrored registry. To customize your `tridentctl` deployment, refer to  link:kubernetes-customize-deploy-tridentctl.html[Customize tridentctl deployment].

== Critical information about Astra Trident 22.10
*You must read the following critical information about Astra Trident 22.10.*

// Start snippet: collapsible block (open on page load)
.*Critical information about Astra Trident 22.10*
[%collapsible%open]
====
* Kubernetes 1.25 is now supported in Trident. You must upgrade to Astra Trident 22.10 prior to upgrading to Kubernetes 1.25.
* Astra Trident strictly enforces the use of multipathing configuration in SAN environments, with a recommended value of `find_multipaths: no` in multipath.conf file. 
+
Use of non-multipathing configuration or use of `find_multipaths: yes` or `find_multipaths: smart` value in multipath.conf file will result in mount failures. Trident has recommended the use of `find_multipaths: no` since the 21.07 release.
====
// End snippet

.Before you begin 

Before you begin installation, log in to the Linux host and verify it is managing a working, link:requirements.html[supported Kubernetes cluster^] and that you have the necessary privileges.

NOTE: With OpenShift, use `oc` instead of `kubectl` in all of the examples that follow, and log in as *system:admin* first by running `oc login -u system:admin` or `oc login -u kube-admin`.

[%collapsible%open]
====
. Verify your Kubernetes version:
+
----
kubectl version
----

. Verify cluster administrator privileges:
+
----
kubectl auth can-i '*' '*' --all-namespaces
----

. Verify you can launch a pod that uses an image from Docker Hub and reach your storage system over the pod network:
+
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----
====

== Step 1: Download the Trident installer package 

The Astra Trident installer package creates a Trident pod, configures the CRD objects that are used to maintain its state, and initializes the CSI sidecars to perform actions such as provisioning and attaching volumes to the cluster hosts. Download and extract the latest version of the Trident installer from link:https://github.com/NetApp/trident/releases/latest[the _Assets_ section on GitHub^]. Update _<trident-installer-XX.XX.X.tar.gz>_ in the example with your selected Astra Trident version. 

----
wget https://github.com/NetApp/trident/releases/download/v22.10.0/<trident-installer-XX.XX.X.tar.gz>
tar -xf <trident-installer-XX.XX.X.tar.gz>
cd trident-installer
----

== Step 2: Install Astra Trident

Install Astra Trident in the desired namespace by executing the `tridentctl install` command. You can add additional arguments to specify image registry location. 

NOTE: To enable Astra Trident to run on Windows nodes, add the `--windows` flag to the install command: `$ ./tridentctl install --windows -n trident`.

[role="tabbed-block"]
====

.Standard mode 
--
----
./tridentctl install -n trident
----
--

.Trident and CSI images in one mirrored registry
--
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:23.01 --trident-image <your-registry>/trident:23.01.0
----
--

.Trident and CSI images in different mirrored registries
--
You must append `sig-storage` to the `imageRegistry` to use different registry locations. 
----
./tridentctl install -n trident --image-registry <your-registry>/sig-storage --autosupport-image <your-registry>/netapp/trident-autosupport:22.10 --trident-image <your-registry>/netapp/trident:23.01.0
----
--

====

Your installation status should look something like this. 
----
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-csi-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=23.01.0
INFO Trident installation succeeded.
....
----

== Verify the installation

You can verify your installation using pod creation status or `tridentctl`. 

=== Using pod creation status

You can confirm if the Astra Trident installation completed by reviewing the status of the created pods:

----
kubectl get pods -n trident

NAME                           READY   STATUS    RESTARTS   AGE
trident-csi-679648bd45-cv2mx   4/4     Running   0          5m29s
trident-csi-vgc8n              2/2     Running   0          5m29s
----

NOTE: If the installer does not complete successfully or `trident-csi-<generated id>` does not have a *Running* status, the platform was not installed. Use `-d` to  link:../troubleshooting.html#troubleshooting-an-unsuccessful-trident-deployment-using-tridentctl[turn on debug mode] and troubleshoot the issue. 

=== Using `tridentctl`

You can use `tridentctl` to check the version of Astra Trident installed.

----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 23.01.0        | 23.01.0        |
+----------------+----------------+
----

== What's next

Now you can link:kubernetes-postdeployment.html[create create a backend and storage class, provision a volume, and mount the volume in a pod].
