---
sidebar: sidebar
permalink: trident-get-started/kubernetes-deploy.html
keywords: deploy, astra trident, methods, operator, tridentctl, helm, tanzu, vmware
summary: You can install Astra Trident using the Trident operator (manually or using Helm) or with `tridentctl`. This topic provides important information for selecting the right installation process for you. 
---

= Learn about Astra Trident installation
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
To ensure Astra Trident can be installed in a wide variety of environments and organizations, NetApp offers multiple installation options. You can install Astra Trident using the Trident operator (manually or using Helm) or with `tridentctl`. This topic provides important information for selecting the right installation process for you. 

== Critical information about Astra Trident 22.10
*You must read the following critical information about Astra Trident 22.10.*

// Start snippet: collapsible block (open on page load)
.*Critical information about Astra Trident 22.10*
[%collapsible%open]
====
* Kubernetes 1.25 is now supported in Trident. You must upgrade to Astra Trident 22.10 prior to upgrading to Kubernetes 1.25.
* Astra Trident strictly enforces the use of multipathing configuration in SAN environments, with a recommended value of `find_multipaths: no` in multipath.conf file. 
+
Use of non-multipathing configuration or use of `find_multipaths: yes` or `find_multipaths: smart` value in multipath.conf file will result in mount failures. Trident has recommended the use of `find_multipaths: no` since the 21.07 release.
====
// End snippet


== Before you begin

Regardless of your installation path, you must have: 

* Full privileges to a supported Kubernetes cluster running a supported version of Kubernetes and feature requirements enabled. Review the link:requirements.html[requirements] for details.
* Access to a supported NetApp storage system.
* Capability to mount volumes from all of the Kubernetes worker nodes.
* A Linux host with `kubectl` (or `oc`, if you are using OpenShift) installed and configured to manage the Kubernetes cluster that you want to use.
* The `KUBECONFIG` environment variable set to point to your Kubernetes cluster configuration.
* If you are using Kubernetes with Docker Enterprise, https://docs.docker.com/ee/ucp/user-access/cli/[follow their steps to enable CLI access^].

TIP: If you have not familiarized yourself with the link:../trident-concepts/intro.html[basic concepts^], now is a great time to do that.

== Choose your installation method
Select the installation method that's right for you. You should also review the considerations for link:kubernetes-deploy.html#move-between-installation-methods[moving between methods] before making your decision. 

=== Using the Trident operator

Whether deploying manually or using Helm, the Trident operator is a great way to simplify installation and dynamically manage Astra Trident resources. You can even link:../trident-get-started/kubernetes-customize-deploy.html[customize your Trident operator deployment] using the attributes in the `TridentOrchestrator`. 

The benefits of using the Trident operator include:

.*Astra Trident object creation*
[%collapsible]
====
The Trident operator automatically creates the following objects for your Kubernetes version. 
* ServiceAccount for the operator
* ClusterRole and ClusterRoleBinding to the ServiceAccount
* Dedicated PodSecurityPolicy (for Kubernetes 1.25 and earlier)
* The operator itself
====

.*Self-healing capability*
[%collapsible]
====
You can monitor an Astra Trident installation and actively take measures to address issues, such as when the deployment is deleted or if it is modified accidentally. A `trident-operator-<generated-id>` pod is created that associates a `TridentOrchestrator` CR with an Astra Trident installation. This ensures there is only one instance of Astra Trident in the cluster and controls its setup, making sure the installation is idempotent. When changes are made to the installation (such as, deleting the deployment or node daemonset), the operator identifies them and fixes them individually.
====

.*Easy updates to existing installations*
[%collapsible]
====
You can easily update an existing deployment with the operator. You only need to edit the `TridentOrchestrator` CR to make updates to an installation.
For example, consider a scenario where you need to enable Astra Trident to generate debug logs.

To do this, patch your `TridentOrchestrator` to set `spec.debug` to `true`:
----
kubectl patch torc <trident-orchestrator-name> -n trident --type=merge -p '{"spec":{"debug":true}}'
----

After `TridentOrchestrator` is updated, the operator processes the updates and patches the existing installation. This might triggers the creation of new pods to modify the installation accordingly.
====

.*Automatic Kubernetes upgrade handling*
[%collapsible]
====
When the Kubernetes version of the cluster is upgraded to a supported version, the operator updates an existing Astra Trident installation automatically and changes it to ensure that it meets the requirements of the Kubernetes version.

NOTE: If the cluster is upgraded to an unsupported version, the operator prevents installing Astra Trident. If Astra Trident has already been installed with the operator, a warning is displayed to indicate that Astra Trident is installed on an unsupported Kubernetes version.
====

.*Kubernetes cluster management using BlueXP (formerly Cloud Manager)*
[%collapsible]
====
With link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/concept-kubernetes.html[Astra Trident using BlueXP^], you can upgrade to the latest version of Astra Trident, add and manage storage classes and connect them to Working Environments, and back up persistent volumes using Cloud Backup Service. BlueXP supports Astra Trident deployment using the Trident operator, either manually or using Helm. 
====

=== Using `tridenctl`

If you have an existing deployment that must be upgraded or if you are looking to highly customize your deployment, you should consider link:kubernetes-deploy-tridentctl.html[installaing using tridentctl]. This is the conventional method of deploying Astra Trident.

You can link:kubernetes-customize-deploy-tridentctl.html[customize your `tridentctl` installation] to generate the manifests for Trident resources. This includes the deployment, daemonset, service account, and the cluster role that Astra Trident creates as part of its installation.

NOTE: Beginning with the 22.04, AES keys will no longer be regenerated every time Astra Trident is installed. With this release, Astra Trident will install a new secret object that persists across installations. This means, `tridentctl` in 22.04 can uninstall previous versions of Trident, but earlier versions cannot uninstall 22.04 installations.
 Select the appropriate installation _method_.   

== Choose your installation mode
Determine your deployment process based on the _installation mode_ (Standard, Offline, or Remote) required by your organization.

// start tabbed area

[role="tabbed-block"]
====

.Standard installation
--
This is the easiest way to install Astra Trident and works for most environments that do not impose network restrictions. Standard installation mode uses default registries to store required Trident (`docker.io`) and CSI (`registry.k8s.io`) images. 

When you use standard mode, the Astra Trident installer: 

* Fetches the container images over the Internet
* Creates a deployment or node daemonset, which spins up Astra Trident pods on all the eligible nodes in the Kubernetes cluster
--

.Offline installation
--
Offline installation mode might be required in an air-gapped or secure location. In this scenario, you can create a single private, mirrored registry or two mirrored registries to store required Trident and CSI images.

NOTE: Regardless of your registry configuration, CSI images must reside in one registry. 
--

.Remote installation
--
Here is a high-level overview of the remote installation process:

* Deploy the appropriate version of `kubectl` on the remote machine from where you want to deploy Astra Trident.
* Copy the configuration files from the Kubernetes cluster and set the `KUBECONFIG` environment variable on the remote machine.
* Initiate a `kubectl get nodes` command to verify that you can connect to the required Kubernetes cluster.
* Complete the deployment from the remote machine by using the standard installation steps.
--
====

== Select the process based on your method and mode

After you've made your decisions, select the appropriate process. 

[cols=2,options="header"]
|===
|Method
|Installation mode

|Trident operator (manually)
a|link:kubernetes-deploy-operator.html[Standard installation]

link:kubernetes-deploy-operator-mirror.html[Offline installation]

|Trident operator (Helm)
a|link:kubernetes-deploy-helm.html[Standard installation]

link:kubernetes-deploy-helm-mirror.html[Offline installation]


|`tridentctl`
a|link:kubernetes-deploy-tridentctl.html[Standard or offline installation]

|===

== Moving between installation methods

You can decide to change your installation method. Before doing so, consider the following:

* Always use the same method for installing and uninstalling Astra Trident. If you have deployed with `tridentctl`, you should use the appropriate version of the `tridentctl` binary to uninstall Astra Trident. Similarly, if you are deploying with the operator, you should edit the `TridentOrchestrator` CR and set `spec.uninstall=true` to uninstall Astra Trident.

* If you have an operator-based deployment that you want to remove and use instead `tridentctl` to deploy Astra Trident, you should first edit `TridentOrchestrator` and set `spec.uninstall=true` to uninstall Astra Trident. Then delete `TridentOrchestrator` and the operator deployment. You can then install using `tridentctl`.

* If you have a manual operator-based deployment, and you want to use Helm-based Trident operator deployment, you should manually uninstall the operator first, and then perform the Helm install. This enables Helm to deploy the Trident operator with the required labels and annotations. If you do not do this, your Helm-based Trident operator deployment will fail with label validation error and annotation validation error. If you have a `tridentctl`-based deployment, you can use Helm-based deployment without running into issues.

== Other known configuration options

When installing Astra Trident on VMWare Tanzu Portfolio products:

* The cluster must support privileged workloads.
* The `--kubelet-dir` flag should be set to the location of kubelet directory. By default, this is `/var/vcap/data/kubelet`.
+
Specifying the kubelet location using `--kubelet-dir` is known to work for Trident Operator, Helm, and `tridentctl` deployments.
