---
sidebar: sidebar
permalink: trident-get-started/kubernetes-deploy-tridentctl.html
keywords: deploy, trident, methods, tridentctl
summary: You can deploy Trident by using `tridentctl`.
---

= Deploy with `tridentctl`
:hardbreaks:
:icons: font
:imagesdir: ../media/

You can deploy Trident by using `tridentctl`.

TIP: If you have not already familiarized yourself with the basic concepts <insert link>, now is a great time to do that.

.What you'll need

To deploy Trident by using the operator, the following prerequisites should be met:

* You have full privileges to a supported Kubernetes cluster.
* You have access to a supported NetApp storage system.
* You have the capability to mount volumes from all of the Kubernetes worker nodes.
* You have a Linux host with `kubectl` (or `oc`, if you are using OpenShift) installed and configured to manage the Kubernetes cluster that you want to use.
* You have set the `KUBECONFIG` environment variable to point to your Kubernetes cluster configuration.
* You have enabled the feature gates required by Trident. (INSERT LINK TO FEATURE REQUIREMENTS TOPIC.)
* If you are using Kubernetes with Docker Enterprise, https://docs.docker.com/ee/ucp/user-access/cli/[follow their steps to enable CLI access].

Got all that? Great! Let's get started.

== Step 1: Qualify your Kubernetes cluster

The first thing you need to do is log into the Linux host and verify that it is managing a _working_, supported Kubernetes cluster <insert link to Supported frontends (orchestrators)> that you have the necessary privileges to.

NOTE: With OpenShift, you use `oc` instead of `kubectl` in all of the
examples that follow, and you should log in as *system:admin* first by running `oc login -u system:admin` or `oc login -u kube-admin`.

[source,console]
----
# Are you running a supported Kubernetes server version?
kubectl version

# Are you a Kubernetes cluster administrator?
kubectl auth can-i '*' '*' --all-namespaces

# Can you launch a pod that uses an image from Docker Hub and can reach your
# storage system over the pod network?
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----

Identify your Kubernetes server version. You will use it when you
install Trident.

== Step 2: Download and extract the installer

NOTE: The Trident installer creates a Trident pod, configures the CRD objects that are used to maintain its state, and initializes the CSI sidecars that perform actions, such as provisioning and attaching volumes to the cluster hosts.

You can download the latest version of the
https://github.com/NetApp/trident/releases/latest[Trident installer bundle^] from the _Downloads_ section, and extract it.

For example, if the latest version is 21.04.0:

[source,console]
----
wget https://github.com/NetApp/trident/releases/download/v21.04.0/trident-installer-21.04.0.tar.gz
tar -xf trident-installer-21.04.0.tar.gz
cd trident-installer
----

== Step 3: Install Trident

Install Trident in the desired namespace by executing the
`tridentctl install <install>` command. The installation procedure
slightly differs depending on the version of Kubernetes being used.

=== Install Trident on Kubernetes 1.13

On Kubernetes 1.13, there are a couple of options when installing
Trident:

* Install Trident in the desired namespace by executing the
`tridentctl install` command with the `--csi` flag. The CSI interface is
https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/[first included in Kubernetes 1.13^], and requires activating
feature gates <insert link to Feature Requirements>. The output when
installing is similar to that shown below for Kubernetes 1.14 and above.
* If for some reason the feature gates required by Trident cannot be enabled, you can install Trident without the `--csi` flag. This configures Trident to work in its traditional format without using the CSI specification.

=== Install Trident on Kubernetes 1.14 and above

Install Trident in the desired namespace by executing the
`tridentctl install` command.

[source,console]
----
$ ./tridentctl install -n trident
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-csi-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=21.04.0
INFO Trident installation succeeded.
....
----

It will look like this when the installer is complete. Depending on the
number of nodes in your Kubernetes cluster, you might observe more pods:
[source,console]
----
$ kubectl get pod -n trident
NAME                           READY   STATUS    RESTARTS   AGE
trident-csi-679648bd45-cv2mx   4/4     Running   0          5m29s
trident-csi-vgc8n              2/2     Running   0          5m29s

$ ./tridentctl -n trident version
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 21.04.0        | 21.04.0        |
+----------------+----------------+
----

If that's what you see, you can ahead and continue to the post-deployment tasks.

However, if the installer does not complete successfully or you don't
see a *Running* `trident-csi-<generated id>`, then Trident had a problem and the platform was _not_ installed. See the link:../troubleshooting.html[Troubleshooting^] section.

=== Step 2: Download and set up the operator

NOTE: Beginning with 21.01, the Trident Operator is cluster scoped. Using the Trident operator to install Trident requires creating the `TridentOrchestrator` Custom Resource Definition (CRD) and defining other resources. You should perform these steps to set up the operator before you can install Trident.

. Download the latest version of the https://github.com/NetApp/trident/releases/latest[Trident installer bundle] from the _Downloads_ section and extract it.
+
[source,console]
----
wget https://github.com/NetApp/trident/releases/download/v21.04/trident-installer-21.04.tar.gz
tar -xf trident-installer-21.04.tar.gz
cd trident-installer
----

. Use the appropriate CRD manifest to create the `TridentOrchestrator`
CRD. You then create a `TridentOrchestrator` Custom Resource later on to instantiate a Trident install by the operator.
+
[source,console]
----
# Is your Kubernetes version < 1.16?
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_pre1.16.yaml

# If not, your Kubernetes version must be 1.16 and above
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----

. After the `TridentOrchestrator` CRD is created, create the following resources required for the operator deployment:
* A ServiceAccount for the operator
* A ClusterRole and ClusterRoleBinding to the ServiceAccount
* A dedicated PodSecurityPolicy
* The operator itself
+
The Trident installer contains manifests for defining these resources. By default, the operator is deployed in the `trident` namespace. If the `trident` namespace does not exist, use the following manifest to create one.
+
[source,console]
----
$ kubectl apply -f deploy/namespace.yaml
----

. To deploy the operator in a namespace other than the
default `trident` namespace, you should update the
`serviceaccount.yaml`, `clusterrolebinding.yaml` and `operator.yaml` manifests and generate your `bundle.yaml`.
+
[source,console]
----
# Have you updated the yaml manifests? Generate your bundle.yaml
# using the kustomization.yaml
kubectl kustomize deploy/ > deploy/bundle.yaml

# Create the resources and deploy the operator
kubectl create -f deploy/bundle.yaml
----

. Verify the status of the operator after you have deployed:
+
[source,console]
----
$ kubectl get deployment -n <operator-namespace>
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
trident-operator   1/1     1            1           3m

$ kubectl get pods -n <operator-namespace>
NAME                              READY   STATUS             RESTARTS   AGE
trident-operator-54cb664d-lnjxh   1/1     Running            0          3m
----

The operator deployment successfully creates a pod running on one of the worker nodes in your cluster.

IMPORTANT: There should only be *one instance* of the operator in a Kubernetes cluster. Do not create multiple deployments of the Trident operator.

=== Step 3: Create `TridentOrchestrator` and install Trident

You are now ready to install Trident using the operator! This will require creating `TridentOrchestrator`. The Trident installer comes with example definitions for creating `TridentOrchestrator`. This kicks off a Trident installation in the `trident` namespace.
[source,console]
----
$ kubectl create -f deploy/crds/tridentorchestrator_cr.yaml
tridentorchestrator.trident.netapp.io/trident created

$ kubectl describe torc trident
Name:        trident
Namespace:
Labels:      <none>
Annotations: <none>
API Version: trident.netapp.io/v1
Kind:        TridentOrchestrator
...
Spec:
  Debug:     true
  Namespace: trident
Status:
  Current Installation Params:
    IPv6:                      false
    Autosupport Hostname:
    Autosupport Image:         netapp/trident-autosupport:21.04
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:                     true
    Enable Node Prep:          false
    Image Pull Secrets:
    Image Registry:
    k8sTimeout:           30
    Kubelet Dir:          /var/lib/kubelet
    Log Format:           text
    Silence Autosupport:  false
    Trident Image:        netapp/trident:21.04.0
  Message:                  Trident installed  Namespace:                trident
  Status:                   Installed
  Version:                  v21.04.0
Events:
    Type Reason Age From Message ---- ------ ---- ---- -------Normal
    Installing 74s trident-operator.netapp.io Installing Trident Normal
    Installed 67s trident-operator.netapp.io Trident installed
----

The Trident operator enables you to customize the manner in which Trident is installed by using the attributes in the `TridentOrchestrator` spec. See link:kubernetes-customize-deploy.html[Customize your Trident deployment^].

The Status of `TridentOrchestrator` indicates if the installation was successful and displays the version of Trident installed.
[width="100%",cols="20%,80%",options="header",]
|===
|Status |Description
|Installing |The operator is installing Trident using this
`TridentOrchestrator` CR.

|Installed |Trident has successfully installed.

|Uninstalling |The operator is uninstalling Trident, since
`spec.uninstall=true`.

|Uninstalled |Trident is uninstalled.

|Failed |The operator could not install, patch, update or uninstall
Trident; the

| |operator will automatically try to recover from this state. If this

| |state persists you will require troubleshooting.

|Updating |The operator is updating an existing Trident installation.

|Error |The `TridentOrchestrator` is not used. Another one already
exists.
|===

During the installation, the status of `TridentOrchestrator` changes from `Installing` to `Installed`. If you observe the `Failed` status and the operator is unable to recover by itself, you should  check the logs of the operator. See the link:../troubleshooting.html[Troubleshooting^] section.

You can confirm if the Trident installation completed by taking a look
at the pods that have been created:

[source,console]
----
$ kubectl get pod -n trident
NAME                                READY   STATUS    RESTARTS   AGE
trident-csi-7d466bf5c7-v4cpw        5/5     Running   0           1m
trident-csi-mr6zc                   2/2     Running   0           1m
trident-csi-xrp7w                   2/2     Running   0           1m
trident-csi-zh2jt                   2/2     Running   0           1m
trident-operator-766f7b8658-ldzsv   1/1     Running   0           3m
----
You can also use `tridentctl` to check the version of Trident installed.

[source,console]
----
$ ./tridentctl -n trident version
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 21.04.0        | 21.04.0        |
+----------------+----------------+
----
Now you can go ahead and create a Trident backend. See link:kubernetes-postdeployment.html[post-deployment tasks^].
