---
sidebar: sidebar
permalink: trident-get-started/kubernetes-customize-deploy.html
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator, smb, windows
summary: The Trident operator enables you to customize the manner in which Astra Trident is installed by using the attributes in the `TridentOrchestrator` spec.
---

= Customize Trident operator installation
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
The Trident operator allows you to customize Astra Trident installation using the attributes in the `TridentOrchestrator` spec.

If you want to customize the installation beyond what `TridentOrchestrator` arguments allow, you should consider using `tridentctl` to generate custom YAML manifests that you can modify as needed.

WARNING: `spec.namespace` is specified in `TridentOrchestrator` to signify which namespace where Astra Trident is installed. This parameter *cannot be updated after Astra Trident is installed*. Attempting to do so causes the `TridentOrchestrator` status to change to `Failed`. Astra Trident is not intended to be migrated across namespaces.

== Configuration options

This table details `TridentOrchestrator` attributes:
[cols=3,options="header"]
|===
|Parameter |Description |Default
|`autosupportImage` |The container image for Autosupport Telemetry |"netapp/trident-autosupport:23.01.0"
|`autosupportProxy` |The address/port of a proxy for sending Autosupport Telemetry |"http://proxy.example.com:8888"
|`controllerPluginNodeSelector` |Additional node selectors for pods running the Trident Controller CSI Plugin.	Follows same format as `pod.spec.nodeSelector`. |No default; optional
|`controllerPluginTolerations` |Overrides tolerations for pods running the Trident Controller CSI Plugin. Follows the same format as `pod.spec.Tolerations`. |No default; optional
|`debug` |Enable debugging for Astra Trident |`false`
|`enableForceDetach` |Works with Kubernetes Non-Graceful Node Shutdown (NGNS) to grant cluster administrators ability to safely migrate workloads with mounted volumes to new nodes should a node become unhealthy. 

*This is an experimental feature in 23.04.* Refer to <<Details about Force Detach>> for important details.  |`false`
|`enableNodePrep` |Manage worker node dependencies automatically (*BETA*) |`false`
|`imagePullPolicy` | Sets the image pull policy for the the Trident operator. Valid values are: 

`Always` to always pull the image. 

`IfNotPresent` to pull the image only if it does not already exist on the node. 

`Never` to never pull the image. |`IfNotPresent`
|`imagePullSecrets` |Secrets to pull images from an internal registry |
|`imageRegistry` |Path to internal registry, of the format `<registry FQDN>[:port][/subpath]` |"k8s.gcr.io/sig-storage (k8s 1.19+) or quay.io/k8scsi"
|`IPv6` |Install Astra Trident over IPv6. |`false`
|`k8sTimeout` |Timeout for Kubernetes operations. |30sec
|`kubeletDir` |Path to the kubelet directory on the host. |“/var/lib/kubelet”
|`logFormat` |Astra Trident logging format to be used [text,json] |"text"
|`namespace` |Namespace in which you are installing install Astra Trident. |"default"
|`nodePluginNodeSelector` |Additional node selectors for pods running the Trident Node CSI Plugin. Follows same format as `pod.spec.nodeSelector`. |No default; optional
|`nodePluginTolerations` |Overrides tolerations for pods running the Trident Node CSI Plugin. Follows the same format as `pod.spec.Tolerations`. |No default; optional
|`silenceAutosupport` |Don't send autosupport bundles to NetApp automatically. |`false`
|`tridentImage` |Astra Trident version image you are installing. |"netapp/trident:21.04"
|`uninstall` |A flag used to uninstall Astra Trident. |`false`
|`windows` | Setting to `true` enables installation on Windows worker nodes. | `false`
|`wipeout` |A list of resources to delete to perform a complete removal of Astra Trident. |
|===
[NOTE] 
For more information on formatting pod parameters, see link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/[Assigning Pods to Nodes^].

=== Details about force detach
Before enabling force detach, you must meet the following conditions: 

* Non-graceful node shutdown (NGNS) must be enabled on the Kubernetes cluster. For more information, refer to link:https://kubernetes.io/docs/concepts/architecture/nodes/#non-graceful-node-shutdown[Kubernetes: Non Graceful node shutdown^]. 
* RWO volume???

WARNING: Because Astra Trident relies on Kubernetes NGNS, do not remove `out-of-service` taints from an unhealthy node until all non-tolerable workloads are rescheduled. Recklessly applying or removing the taint can jeopardize backend data protection.  

When the Kubernetes cluster administrator has applied the `node.kubernetes.io/out-of-service=nodeshutdown:NoExecute` taint to the node and `enableForceDetach` is set to `true`, Astra Trident will determine the node status and:

. Cease input and output for that node on the backend. 
. Mark the Astra Trident node object as `notSafeToPublish`.

When node health is restored and the taint is removed, Astra Trident will:

. Identify and clean dirty publication paths
. Post the cleaned paths back to .... ?????
. Update the node to `safeToPublish`.


== Sample configurations
You can use the attributes mentioned above when defining `TridentOrchestrator` to customize your installation. 

.Example 1: Basic custom configuration
[%collapsible%open]
====
This is an example for a basic custom configuration.

----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----

====

.Example 2: Deploy with node selectors
[%collapsible%open]
====

This example illustrates how Trident can be deployed with node selectors:
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
====

.Example 3: Deploy on Windows worker nodes
[%collapsible%open]
====
This example illustrates deployment on a Windows worker node.

----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  windows: true
----

====