---
sidebar: sidebar
permalink: trident-get-started/kubernetes-deploy.html
keywords: deploy, astra trident, methods, operator, tridentctl, helm, tanzu, vmware
summary: You can install Astra Trident using the Trident operator (manually or using Helm) or with `tridentctl`.
---

= Deployment overview
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You can install Astra Trident using the Trident operator (manually or using Helm) or with `tridentctl`.

== Critical information about Astra Trident 22.10
*You must read the following critical information before upgrading to Astra Trident 22.10.*

[WARNING]
.*Critical information about Astra Trident 22.10*
====
* Kubernetes 1.25 is now supported in Trident. You must upgrade to Astra Trident 22.10 prior to upgrading to Kubernetes 1.25.
* Astra Trident strictly enforces the use of multipathing configuration in SAN environments, with a recommended value of `find_multipaths: no` in multipath.conf file. 
+
Use of non-multipathing configuration or use of `find_multipaths: yes` or `find_multipaths: smart` value in multipath.conf file will result in mount failures. Trident has recommended the use of `find_multipaths: no` since the 21.07 release.
====

== Learn about Astra Trident installation

You can install Astra Trident using the following methods and modes. Review the details for each to decide which method and mode are right for you. 

[cols=2,options="header"]
|===
|Method
|Available modes

|Trident operator (manually or using Helm)
a|Standard and remote

|`tridentctl`
a|Standard, offline, and remote

|===

== Before you install

Before you begin any Astra Trident installation, ensure you have: 

* Full privileges to a supported Kubernetes cluster running a supported version of Kubernetes. Review the link:requirements.html[requirements].
* Access to a supported NetApp storage system.
* Capability to mount volumes from all of the Kubernetes worker nodes.
* A Linux host with `kubectl` (or `oc`, if you are using OpenShift) installed and configured to manage the Kubernetes cluster that you want to use.
* The `KUBECONFIG` environment variable set to point to your Kubernetes cluster configuration.
* link:requirements.html#feature-requirements[Feature requirements required by Astra Trident] enabled.
* If you are using Kubernetes with Docker Enterprise, https://docs.docker.com/ee/ucp/user-access/cli/[follow their steps to enable CLI access^].

TIP: If you have not familiarized yourself with the link:../trident-concepts/intro.html[basic concepts^], now is a great time to do that.

== Choose the right installation method
Select the installation method that's right for you.

=== Using the Trident operator

The Trident operator is a great way to dynamically manage Astra Trident resources and automate the setup phase. You can:

* Deploy the link:kubernetes-deploy-operator.html[Trident operator manually] to install Astra Trident
* Use link:kubernetes-deploy-helm.html[use Helm to deploy the operator and install Astra Trident] in one step
* link:kubernetes-customize-deploy.html[Customize your operator-based deployment]

Benefits of using the Trident operator include:

.*Self-healing capability*
[%collapsible%close]
====
You can monitor an Astra Trident installation and actively take measures to address issues, such as when the deployment is deleted or if it is modified accidentally. When the operator is set up as a deployment, a `trident-operator-<generated-id>` pod is created. This pod associates a `TridentOrchestrator` CR with an Astra Trident installation and always ensures there is only one active `TridentOrchestrator`. In other words, the operator ensures there is only one instance of Astra Trident in the cluster and controls its setup, making sure the installation is idempotent. When changes are made to the installation (such as, deleting the deployment or node daemonset), the operator identifies them and fixes them individually.
====

.*Easy updates to existing installations*
[%collapsible%close]
====
You can easily update an existing deployment with the operator. You only need to edit the `TridentOrchestrator` CR to make updates to an installation.
For example, consider a scenario where you need to enable Astra Trident to generate debug logs.

To do this, patch your `TridentOrchestrator` to set `spec.debug` to `true`:
----
kubectl patch torc <trident-orchestrator-name> -n trident --type=merge -p '{"spec":{"debug":true}}'
----

After `TridentOrchestrator` is updated, the operator processes the updates and patches the existing installation. This might triggers the creation of new pods to modify the installation accordingly.
====

.*Automatic Kubernetes upgrade handling*
[%collapsible%close]
====
When the Kubernetes version of the cluster is upgraded to a supported version, the operator updates an existing Astra Trident installation automatically and changes it to ensure that it meets the requirements of the Kubernetes version.

NOTE: If the cluster is upgraded to an unsupported version, the operator prevents installing Astra Trident. If Astra Trident has already been installed with the operator, a warning is displayed to indicate that Astra Trident is installed on an unsupported Kubernetes version.
====

.*Kubernetes cluster management using BlueXP (formerly Cloud Manager)*
[%collapsible%close]
====
With link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/concept-kubernetes.html[Astra Trident using BlueXP^], you can upgrade to the latest version of Astra Trident, add and manage storage classes and connect them to Working Environments, and back up persistent volumes using Cloud Backup Service. BlueXP supports Astra Trident deployment using the Trident operator, either manually or using Helm. 
====

=== Using `tridenctl`

If you have an existing deployment that must be upgraded or if you are looking to highly customize your deployment, you should consider link:kubernetes-deploy-tridentctl.html[installaing using tridentctl]. This is the conventional method of deploying Astra Trident.

You can link:kubernetes-customize-deploy-tridentctl.html[customize your `tridentctl` installation] to generate the manifests for Trident resources. This includes the deployment, daemonset, service account, and the cluster role that Astra Trident creates as part of its installation.

NOTE: Beginning with the 22.04, AES keys will no longer be regenerated every time Astra Trident is installed. With this release, Astra Trident will install a new secret object that persists across installations. This means, `tridentctl` in 22.04 can uninstall previous versions of Trident, but earlier versions cannot uninstall 22.04 installations.

== Move between installation methods

Before moving between installation methods, consider the following:

* Always use the same method for installing and uninstalling Astra Trident. If you have deployed with `tridentctl`, you should use the appropriate version of the `tridentctl` binary to uninstall Astra Trident. Similarly, if you are deploying with the operator, you should edit the `TridentOrchestrator` CR and set `spec.uninstall=true` to uninstall Astra Trident.

* If you have an operator-based deployment that you want to remove and use instead `tridentctl` to deploy Astra Trident, you should first edit `TridentOrchestrator` and set `spec.uninstall=true` to uninstall Astra Trident. Then delete `TridentOrchestrator` and the operator deployment. You can then install using `tridentctl`.

* If you have a manual operator-based deployment, and you want to use Helm-based Trident operator deployment, you should manually uninstall the operator first, and then perform the Helm install. This enables Helm to deploy the Trident operator with the required labels and annotations. If you do not do this, your Helm-based Trident operator deployment will fail with label validation error and annotation validation error. If you have a `tridentctl`-based deployment, you can use Helm-based deployment without running into issues.

== Learn about the installation modes

There are three modes to install Astra Trident.

=== Standard mode

You can install Astra Trident using standard mode for Trident operator and `tridentctl` methods. This is the easiest way to install Astra Trident and works for most environments that do not impose network restrictions. 

When you use standard mode, the Astra Trident installer: 

* Fetches the container images over the Internet
* Creates a deployment and/or node daemonset, which spins up Astra Trident pods on all the eligible nodes in the Kubernetes cluster

=== Offline mode

To perform an air-gapped deployment, you can use the `--image-registry` flag when invoking `tridentctl install` to point to a private image registry. If deploying with the Trident operator, you can alternatively specify `spec.imageRegistry` in your `TridentOrchestrator`. This registry should contain the https://hub.docker.com/r/netapp/trident/[Trident image^], the https://hub.docker.com/r/netapp/trident-autosupport/[Trident Autosupport image^], and the CSI sidecar images as required by your Kubernetes version.

WARNING: If you are using a private image repository, you should add `/sig-storage` to the end of the private registry URL. When using a private registry for `tridentctl` deployment, you should use `--trident-image` and `--autosupport-image` in conjunction with `--image-registry`. If you are deploying Astra Trident by using the Trident operator, ensure that the orchestrator CR includes `tridentImage` and `autosupportImage` in the installation parameters.

=== Remote mode

Here is a high-level overview of the remote mode process:

* Deploy the appropriate version of `kubectl` on the remote machine from where you want to deploy Astra Trident.
* Copy the configuration files from the Kubernetes cluster and set the `KUBECONFIG` environment variable on the remote machine.
* Initiate a `kubectl get nodes` command to verify that you can connect to the required Kubernetes cluster.
* Complete the deployment from the remote machine by using the standard installation steps.

== Other known configuration options

When installing Astra Trident on VMWare Tanzu Portfolio products:

* The cluster must support privileged workloads.
* The `--kubelet-dir` flag should be set to the location of kubelet directory. By default, this is `/var/vcap/data/kubelet`.
+
Specifying the kubelet location using `--kubelet-dir` is known to work for Trident Operator, Helm, and `tridentctl` deployments.
