---
sidebar: sidebar
permalink: trident-get-started/kubernetes-deploy-operator-mirror.html
keywords: deploy, astra trident, methods, operator, tridentctl, mirrored, registry, registries
summary: You can manually deploy the Trident operator to install Astra Trident. This process applies to installations where Trident and CSI images are located in a private, mirrored registry. 
---

= Manually deploy the Trident operator (mirrored registry)
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
You can manually deploy the Trident operator to install Astra Trident. This process applies to installations where Trident and CSI images are located in a private, mirrored registry. If your images are located in a `docker.io` and `registry.k8s.io`, use the link:kubernetes-deploy-operator.html[process for `docker.io` and `registry.k8s.io`].

== Critical information about Astra Trident 22.10
*You must read the following critical information before upgrading to Astra Trident 22.10.*

[WARNING]
.*Critical information about Astra Trident 22.10*
====
* Kubernetes 1.25 is now supported in Trident. You must upgrade to Astra Trident 22.10 prior to upgrading to Kubernetes 1.25.
* Astra Trident now strictly enforces the use of multipathing configuration in SAN environments, with a recommended value of `find_multipaths: no` in multipath.conf file. 
+
Use of non-multipathing configuration or use of `find_multipaths: yes` or `find_multipaths: smart` value in multipath.conf file will result in mount failures. Trident has recommended the use of `find_multipaths: no` since the 21.07 release.
====

== Deploy the Trident operator manually and install Trident

IMPORTANT: Before you begin, review link:../trident-get-started/kubernetes-deploy.html[the deployment process overview] to ensure you've met installation prerequisites and selected the correct installation option for your environment. 

=== Step 1: Qualify your Kubernetes cluster

.Before you begin
Log in to the Linux host and verify it is managing a working, link:requirements.html[supported Kubernetes cluster^] that you have the necessary privileges to.

NOTE: With OpenShift, use `oc` instead of `kubectl` in all of the examples that follow, and log in as *system:admin* first by running `oc login -u system:admin` or `oc login -u kube-admin`.

.Steps

. Verify your Kubernetes version using the following command:
+
----
kubectl version
----

. Verify cluster administrator privileges using the following command:
+
----
kubectl auth can-i '*' '*' --all-namespaces
----

. Verify if you can launch a pod that uses an image from Docker Hub and reach your storage system over the pod network using the following command:
+
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----

.Results
You have qualified your Kubernetes cluster. 

=== Step 2: Download and set up the operator

.Before you begin
The Trident operator is cluster scoped. Using the Trident operator to install Trident requires creating the `TridentOrchestrator` Custom Resource Definition (CRD) and defining other resources. You should perform these steps to set up the operator before you can install Astra Trident.

.Steps

. Download and extract the latest version of the Trident installer bundle from link:https://github.com/NetApp/trident/releases/latest[the _Assets_ section on GitHub^]. Update _<trident-installer-XX.XX.X.tar.gz>_ in the example with your selected Astra Trident version. 
+
----
wget https://github.com/NetApp/trident/releases/download/v22.10.0/<trident-installer-XX.XX.X.tar.gz>
tar -xf <trident-installer-XX.XX.X.tar.gz>
cd trident-installer
----

. Use the appropriate CRD manifest to create the `TridentOrchestrator` CRD. You will create a `TridentOrchestrator` Custom Resource later on to instantiate an installation by the operator:
+
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----

. After the `TridentOrchestrator` CRD is created, create the following resources required for the operator deployment:
* A ServiceAccount for the operator
* A ClusterRole and ClusterRoleBinding to the ServiceAccount
* A dedicated PodSecurityPolicy
* The operator itself
+
[NOTE]
====
The Trident installer contains manifests for defining these resources. By default, the operator is deployed in the `trident` namespace. If the `trident` namespace does not exist, use `kubectl apply -f deploy/namespace.yaml` to create one.

To deploy the operator in a namespace other than the default `trident` namespace, you should update the `serviceaccount.yaml`, `clusterrolebinding.yaml` and `operator.yaml` manifests and generate your `bundle.yaml` using the `kustomization.yaml`:
----
kubectl kustomize deploy/ > deploy/bundle.yaml
----
====

. Create the resources and deploy the operator:
+
----
kubectl create -f deploy/BUNDLE.yaml
----
+
[NOTE]
=====
Trident provides a bundle file that can be used to install the operator and create associated objects for your Kubernetes version.

* For clusters running Kubernetes 1.24 or lower, use link:https://github.com/NetApp/trident/tree/stable/v22.10/deploy/bundle_pre_1_25.yaml[bundle_pre_1_25.yaml^].

* For clusters running Kubernetes 1.25 or higher, use link:https://github.com/NetApp/trident/tree/stable/v22.10/deploy/bundle_post_1_25.yaml[bundle_post_1_25.yaml^].

=====

. Verify the status of the operator:
+
----
kubectl get deployment -n <operator-namespace>

NAME               READY   UP-TO-DATE   AVAILABLE   AGE
trident-operator   1/1     1            1           3m
----
+
----
kubectl get pods -n <operator-namespace>

NAME                              READY   STATUS             RESTARTS   AGE
trident-operator-54cb664d-lnjxh   1/1     Running            0          3m
----

.Results
The operator deployment successfully creates a pod running on one of the worker nodes in your cluster.

IMPORTANT: There should only be *one instance* of the operator in a Kubernetes cluster. Do not create multiple deployments of the Trident operator.

=== Step 3: Create the `TridentOrchestrator` and install Trident

You can now create the `TridentOrchestrator` and install Astra Trident in the `trident` namespace. Optionally, you can link:kubernetes-customize-deploy.html[customize your Trident installation] using the attributes in the `TridentOrchestrator` spec.

----
kubectl create -f deploy/crds/tridentorchestrator_cr.yaml
tridentorchestrator.trident.netapp.io/trident created 

kubectl describe torc trident

Name:        trident
Namespace:
Labels:      <none>
Annotations: <none>
API Version: trident.netapp.io/v1
Kind:        TridentOrchestrator
...
Spec:
  Debug:     true
  Namespace: trident
Status:
  Current Installation Params:
    IPv6:                      false
    Autosupport Hostname:
    Autosupport Image:         netapp/trident-autosupport:22.10
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:                     true
    Image Pull Secrets:
    Image Registry:
    k8sTimeout:           30
    Kubelet Dir:          /var/lib/kubelet
    Log Format:           text
    Silence Autosupport:  false
    Trident Image:        netapp/trident:21.04.0
  Message:                  Trident installed  Namespace:                trident
  Status:                   Installed
  Version:                  v21.04.0
Events:
    Type Reason Age From Message ---- ------ ---- ---- -------Normal
    Installing 74s trident-operator.netapp.io Installing Trident Normal
    Installed 67s trident-operator.netapp.io Trident installed
----

== Verify the installation

There are several ways to verify your installation. 

=== Using `TridentOrchestrator` status
The status of `TridentOrchestrator` indicates if the installation was successful and displays the version of Trident installed. During the installation, the status of `TridentOrchestrator` changes from `Installing` to `Installed`. If you observe the `Failed` status and the operator is unable to recover by itself, you should  check the logs of the operator. See the link:../troubleshooting.html[troubleshooting^] section.

[cols=2,options="header"]
|===
|Status |Description
|Installing |The operator is installing Astra Trident using this `TridentOrchestrator` CR.

|Installed |Astra Trident has successfully installed.

|Uninstalling |The operator is uninstalling Astra Trident, because
`spec.uninstall=true`.

|Uninstalled |Astra Trident is uninstalled.

|Failed |The operator could not install, patch, update or uninstall
Astra Trident; the operator will automatically try to recover from this state. If this state persists you will require troubleshooting.

|Updating |The operator is updating an existing installation.

|Error |The `TridentOrchestrator` is not used. Another one already
exists.
|===

=== Using pod creation status

You can confirm if the Astra Trident installation completed by taking a look at the pods that have been created:

----
kubectl get pod -n trident

NAME                                READY   STATUS    RESTARTS   AGE
trident-csi-7d466bf5c7-v4cpw        5/5     Running   0           1m
trident-csi-mr6zc                   2/2     Running   0           1m
trident-csi-xrp7w                   2/2     Running   0           1m
trident-csi-zh2jt                   2/2     Running   0           1m
trident-operator-766f7b8658-ldzsv   1/1     Running   0           3m
----

=== Using `tridentctl`

You can use `tridentctl` to check the version of Astra Trident installed.

----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 21.04.0        | 21.04.0        |
+----------------+----------------+
----

== What's next

Now you can link:kubernetes-postdeployment.html[create create a backend and storage class, provision a volume, and mount the volume in a pod].