---
sidebar: sidebar
permalink: trident-get-started/quickstart.html
keywords: kubernetes cluster, simple installation, Kubernetes installation
summary: If you are just getting started with Kubernetes, use the instructions to install Kubernetes to try it out. These instructions provide a bare-bones, single-node cluster that Trident can integrate with for demonstration purposes.
---

= Try it out
:hardbreaks:
:icons: font
:imagesdir: ../media/

NetApp provides a ready-to-use lab image that you can request through link:https://www.netapp.com/us/try-and-buy/test-drive/index.aspx[NetApp Test Drive^]. The Test Drive provides you with a sandbox environment that comes with a three-node Kubernetes cluster and Astra Trident installed and configured. It is a great way to familiarize yourself with Astra Trident and explore its features.

Another option is to see the link:https://kubernetes.io/docs/setup/independent/install-kubeadm/[kubeadm Install Guide] provided by Kubernetes.

NOTE: You should not use the Kubernetes cluster that you build using these instructions in production. Use the production deployment guides provided by your distribution for creating clusters that are production ready.

If this is the first time you're using Kubernetes, familiarize yourself with the concepts and tools link:https://kubernetes.io/docs/home/[here^].
