---
sidebar: sidebar
permalink: trident-get-started/requirements.html
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx
summary: Get started by reviewing the supported frontends, backends, and host configuration.
---

= Requirements
:hardbreaks:
:icons: font
:imagesdir: ../media/

Get started by reviewing the supported frontends, backends, and host configuration.

NOTE: To learn about the ports that Astra Trident uses, see link:../trident-reference/trident-ports.html[here^].

== Supported frontends (orchestrators)

Astra Trident supports multiple container engines and orchestrators, including the following:

* Anthos On-Prem (VMware) and Anthos on bare metal 1.9, 1.10, 1.11
* Kubernetes 1.18 or later (latest: 1.23)
* Mirantis Kubernetes Engine 3.4
* OpenShift 4.7, 4.8, 4.9, 4.10

The Trident operator is supported with these releases:

* Anthos On-Prem (VMware) and Anthos on bare metal 1.9, 1.10, 1.11
* Kubernetes 1.18 or later (latest: 1.23)
* OpenShift 4.7, 4.8, 4.9, 4.10

NOTE: Red Hat OpenShift Container Platform users might observe their initiatorname.iscsi file to be blank if using any version below 4.6.8. This is a bug that has been identified by RedHat to be fixed with OpenShift 4.6.8. See this https://access.redhat.com/errata/RHSA-2020:5259/[bug fix announcement^]. NetApp recommends that you use Astra Trident on OpenShift 4.6.8 and later.

Astra Trident also works with a host of other fully-managed and self-managed Kubernetes offerings, including Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Rancher, and VMWare Tanzu Portfolio.

== Supported backends (storage)

To use Astra Trident, you need one or more of the following supported backends:

* Amazon FSx for NetApp ONTAP
* Azure NetApp Files
* Astra Data Store 22.05 or later
* Cloud Volumes ONTAP
* Cloud Volumes Service for GCP
* FAS/AFF/Select 9.3 or later
* NetApp All SAN Array (ASA)
* NetApp HCI/Element software 11 or later

== Feature requirements

The table below summarizes the features available with this release of
Astra Trident and the versions of Kubernetes it supports.

[cols=3,options="header"]
|===
|Feature
|Kubernetes version
|Feature gates required?

|CSI Trident
a|1.17 and later
a|No

|Volume Snapshots
a|1.17 and later
a|No

|PVC from Volume Snapshots
a|1.17 and later
a|No

|iSCSI PV resize
a|1.17 and later
a|No

|ONTAP Bidirectional CHAP
a|1.17 and later
a|No

|Dynamic Export Policies
a|1.17 and later
a|No

|Trident Operator
a|1.17 and later
a|No

|Auto Worker Node Prep (beta)
a|1.17 and later
a|No

|CSI Topology
a|1.17 and later
a|No

|===

== Tested host operating systems

By default, Astra Trident runs in a container and will, therefore, run on any Linux worker. However, those workers need to be able to mount the volumes that Astra Trident provides using the standard NFS client or iSCSI initiator, depending on the backends you are using.

Though Astra Trident does not officially "support" specific operating systems, the following Linux distributions are known to work:

* RedHat CoreOS (RHCOS) versions as supported by OpenShift Container Platform
* RHEL or CentOS 7.4 or later
* Ubuntu 18.04 or later

The `tridentctl` utility also runs on any of these distributions of Linux.

== Host configuration

Depending on the backend(s) in use, NFS and/or iSCSI utilities should be installed on all of the workers in the cluster. See link:../trident-use/worker-node-prep.html[here^] for more information.

== Storage system configuration

Astra Trident might require some changes to a storage system before a backend configuration can use it. See  link:../trident-use/backends.html[here^] for details.

== Container images and corresponding Kubernetes versions

For air-gapped installations, the following list is a reference of container images needed to install Astra Trident. Use the `tridentctl images` command to verify the list of needed container images.

[cols=2,options="header"]
|===
|Kubernetes version
|Container image

|v1.17.0
a|
* netapp/trident:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (optional)

|v1.18.0
a|
* netapp/trident:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (optional)

|v1.19.0
a|
* netapp/trident:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (optional)

|v1.20.0
a|
* netapp/trident:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (optional)

|v1.21.0
a|
* netapp/trident:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (optional)

|v1.22.0
a|
* netapp/trident:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (optional)

|v1.23.0
a|
* netapp/trident:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (optional)

|===

NOTE: On Kubernetes version 1.20 and later, use the validated `k8s.gcr.io/sig-storage/csi-snapshotter:v4.x` image only if the `v1` version is serving the `volumesnapshots.snapshot.storage.k8s.io` CRD. If the `v1beta1` version is serving the CRD with/without the `v1` version, use the validated `k8s.gcr.io/sig-storage/csi-snapshotter:v3.x` image.
