---
sidebar: sidebar
permalink: trident-get-started/requirements.html
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system
summary: Get started by reviewing the supported frontends, backends, and host configuration.
---

= Requirements
:hardbreaks:
:icons: font
:imagesdir: ../media/

Get started by reviewing the supported frontends, backends, and host configuration.

NOTE: To learn about the ports that Astra Trident uses, see link:../trident-reference/trident-ports.html[here^].

== Supported frontends (orchestrators)

Astra Trident supports multiple container engines and orchestrators, including the following:

* Kubernetes 1.17 or later (latest: 1.22)
* Mirantis Kubernetes Engine 3.4
* OpenShift 4.4, 4.5, 4.6 (4.6.8+), 4.7, 4.8 (latest 4.8)

The Trident operator is supported with these releases:

* Kubernetes 1.17 or later (latest: 1.22)
* OpenShift 4.4, 4.5, 4.6 (4.6.8+), 4.7, 4.8 (latest 4.8)

NOTE: Red Hat OpenShift Container Platform users might observe their initiatorname.iscsi file to be blank if using any version below 4.6.8. This is a bug that has been identified by RedHat to be fixed with OpenShift 4.6.8. See this https://access.redhat.com/errata/RHSA-2020:5259/[bug fix announcement^]. NetApp recommends that you use Astra Trident on OpenShift 4.7 and later.

Astra Trident also works with a host of other fully managed and self-managed Kubernetes offerings, including Google Cloud’s Google Kubernetes Engine (GKE), AWS’s Elastic Kubernetes Services (EKS), Azure’s Azure Kubernetes Service (AKS), and Rancher.

== Supported backends (storage)

To use Astra Trident, you need one or more of the following supported backends:

* Amazon FSx for NetApp ONTAP
* Azure NetApp Files
* Cloud Volumes ONTAP
* Cloud Volumes Service for AWS
* Cloud Volumes Service for GCP
* FAS/AFF/Select 9.3 or later
* NetApp All SAN Array (ASA)
* NetApp HCI/Element software 8 or later

== Feature requirements

The table below summarizes the features available with this release of
Astra Trident and the versions of Kubernetes it supports.

[cols=3,options="header"]
|===
|Feature
|Kubernetes version
|Feature gates required?

|CSI Trident
a|1.17 and later
a|No

|Volume Snapshots
a|1.17 and later
a|No

|PVC from Volume Snapshots
a|1.17 and later
a|No

|iSCSI PV resize
a|1.17 and later
a|No

|ONTAP Bidirectional CHAP
a|1.17 and later
a|No

|Dynamic Export Policies
a|1.17 and later
a|No

|Trident Operator
a|1.17 and later
a|No

|Auto Worker Node Prep (beta)
a|1.17 and later
a|No

|CSI Topology
a|1.17 and later
a|No

|===

== Supported host operating systems

By default, Astra Trident itself runs in a container, therefore it will run on any Linux worker. However, those workers need to be able to mount the volumes that Astra Trident provides using the standard NFS client or iSCSI initiator, depending on the backend(s) you are using.

These are the Linux distributions that are known to work:

* RedHat CoreOS 4.2 and 4.3
* RHEL or CentOS 7.4 or later
* Ubuntu 18.04 or later

The `tridentctl` utility also runs on any of these distributions of Linux.

== Host configuration

Depending on the backend(s) in use, NFS and/or iSCSI utilities should be installed on all of the workers in the cluster. See link:../trident-use/worker-node-prep.html[here^] for more information.

== Storage system configuration

Astra Trident might require some changes to a storage system before a backend configuration can use it. See the link:../trident-use/backends.html[here^] for details.

== Container images and corresponding Kubernetes versions

For air-gapped installations, see the following list for what container images are needed to install Astra Trident:

[cols=2,options="header"]
|===
|Kubernetes version
|Container image

|v1.17.0
a|
* netapp/trident:21.07.0
* netapp/trident-operator:21.07.0
* netapp/trident-autosupport:21.01
* k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
* k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0

|v1.18.0
a|
* netapp/trident:21.07.0
* netapp/trident-operator:21.07.0
* netapp/trident-autosupport:21.01
* k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
* k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.1.0

|v1.19.0
a|
* netapp/trident:21.07.0
* netapp/trident-operator:21.07.0
* netapp/trident-autosupport:21.01
* k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
* k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0

|v1.20.0
a|
* netapp/trident:21.07.0
* netapp/trident-operator:21.07.0
* netapp/trident-autosupport:21.01
* k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
* k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0

|v1.21.0
a|
* netapp/trident:21.07.0
* netapp/trident-operator:21.07.0
* netapp/trident-autosupport:21.01
* k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
* k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0

|===

NOTE: On Kubernetes version 1.20 and later, use the validated `k8s.gcr.io/sig-storage/csi-snapshotter:v4.x` image only if the `v1` version is serving the `volumesnapshots.snapshot.storage.k8s.io` CRD. If the `v1beta1` version is serving the CRD with/without the `v1` version, use the validated `k8s.gcr.io/sig-storage/csi-snapshotter:v3.x` image.
