---
sidebar: sidebar
permalink: trident-get-started/requirements.html
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx
summary: Get started by reviewing the supported frontends, backends, and host configuration.
---

= Requirements
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Get started by reviewing the supported frontends, backends, and host configuration.

NOTE: To learn about the ports that Astra Trident uses, see link:../trident-reference/trident-ports.html[here].

== Critical information about Astra Trident 22.10
*You must read the following critical information before upgrading to Astra Trident 22.10.*

[WARNING]
.*Critical information about Astra Trident 22.10*
====
* Kubernetes 1.25 is now supported in Trident. You must upgrade to Astra Trident 22.10 prior to upgrading to Kubernetes 1.25.
* Astra Trident now strictly enforces the use of multipathing configuration in SAN environments, with a recommended value of `find_multipaths: no` in multipath.conf file. 
+
Use of non-multipathing configuration or use of `find_multipaths: yes` or `find_multipaths: smart` value in multipath.conf file will result in mount failures. Trident has recommended the use of `find_multipaths: no` since the 21.07 release.
====

== Supported frontends (orchestrators)

Astra Trident supports multiple container engines and orchestrators, including the following:

* Anthos On-Prem (VMware) and Anthos on bare metal 1.9, 1.10, 1.11
* Kubernetes 1.20 - 1.25
* Mirantis Kubernetes Engine 3.5
* OpenShift 4.8, 4.9, 4.10, 4.11

The Trident operator is supported with these releases:

* Anthos On-Prem (VMware) and Anthos on bare metal 1.9, 1.10, 1.11
* Kubernetes 1.20 - 1.25
* OpenShift 4.8, 4.9, 4.10, 4.11

Astra Trident also works with a host of other fully-managed and self-managed Kubernetes offerings, including Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Rancher, and VMWare Tanzu Portfolio.

== Supported backends (storage)

To use Astra Trident, you need one or more of the following supported backends:

* Amazon FSx for NetApp ONTAP
* Azure NetApp Files
* Cloud Volumes ONTAP
* Cloud Volumes Service for GCP
* FAS/AFF/Select 9.3 or later
* NetApp All SAN Array (ASA)
* NetApp HCI/Element software 11 or above

== Feature requirements

The table below summarizes the features available with this release of
Astra Trident and the versions of Kubernetes it supports.

[cols=3,options="header"]
|===
|Feature
|Kubernetes version
|Feature gates required?

|CSI Trident

a|1.20 - 1.25
a|No

|Volume Snapshots
a|1.20 - 1.25
a|No

|PVC from Volume Snapshots
a|1.20 - 1.25
a|No

|iSCSI PV resize
a|1.20 - 1.25
a|No

|ONTAP Bidirectional CHAP
a|1.20 - 1.25
a|No

|Dynamic Export Policies
a|1.20 - 1.25
a|No

|Trident Operator
a|1.20 - 1.25
a|No

|Auto Worker Node Prep (beta)
a|1.20 - 1.25
a|No

|CSI Topology
a|1.20 - 1.25
a|No

|===

== Tested host operating systems

By default, Astra Trident runs in a container and will, therefore, run on any Linux worker. However, those workers need to be able to mount the volumes that Astra Trident provides using the standard NFS client or iSCSI initiator, depending on the backends you are using.

Though Astra Trident does not officially "support" specific operating systems, the following Linux distributions are known to work:

* RedHat CoreOS (RHCOS) versions as supported by OpenShift Container Platform
* RHEL or CentOS 7
* Ubuntu 18.04 or later (latest 22.04)

The `tridentctl` utility also runs on any of these distributions of Linux.

== Host configuration

Depending on the backend(s) in use, NFS and/or iSCSI utilities should be installed on all of the workers in the cluster. See link:../trident-use/worker-node-prep.html[here^] for more information.

== Storage system configuration

Astra Trident might require some changes to a storage system before a backend configuration can use it. See  link:../trident-use/backends.html[here^] for details.

== Container images and corresponding Kubernetes versions

For air-gapped installations, the following list is a reference of container images needed to install Astra Trident. Use the `tridentctl images` command to verify the list of needed container images.

[cols=2,options="header"]
|===
|Kubernetes version
|Container image

|v1.20.0
a|
* netapp/trident:22.10.0                      
* netapp/trident-autosupport:22.10                   
* k8s.io/sig-storage/csi-provisioner:v3.3.0           
* k8s.io/sig-storage/csi-attacher:v4.0.0              
* k8s.io/sig-storage/csi-resizer:v1.6.0               
* k8s.io/sig-storage/csi-snapshotter:v3.0.3           
* k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 
* netapp/trident-operator:22.10.0 (optional)  


|v1.21.0
a|
* netapp/trident:22.10.0                      
* netapp/trident-autosupport:22.10                   
* k8s.io/sig-storage/csi-provisioner:v3.3.0           
* k8s.io/sig-storage/csi-attacher:v4.0.0              
* k8s.io/sig-storage/csi-resizer:v1.6.0               
* k8s.io/sig-storage/csi-snapshotter:v3.0.3           
* k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 
* netapp/trident-operator:22.10.0 (optional)  

|v1.22.0
a|
* netapp/trident:22.10.0                      
* netapp/trident-autosupport:22.10                   
* k8s.io/sig-storage/csi-provisioner:v3.3.0           
* k8s.io/sig-storage/csi-attacher:v4.0.0              
* k8s.io/sig-storage/csi-resizer:v1.6.0               
* k8s.io/sig-storage/csi-snapshotter:v3.0.3           
* k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 
* netapp/trident-operator:22.10.0 (optional)  

|v1.23.0
a|
* netapp/trident:22.10.0                      
* netapp/trident-autosupport:22.10                   
* k8s.io/sig-storage/csi-provisioner:v3.3.0           
* k8s.io/sig-storage/csi-attacher:v4.0.0              
* k8s.io/sig-storage/csi-resizer:v1.6.0               
* k8s.io/sig-storage/csi-snapshotter:v3.0.3           
* k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 
* netapp/trident-operator:22.10.0 (optional)  

|v1.24.0
a|
* netapp/trident:22.10.0                      
* netapp/trident-autosupport:22.10                   
* k8s.io/sig-storage/csi-provisioner:v3.3.0           
* k8s.io/sig-storage/csi-attacher:v4.0.0              
* k8s.io/sig-storage/csi-resizer:v1.6.0               
* k8s.io/sig-storage/csi-snapshotter:v3.0.3           
* k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 
* netapp/trident-operator:22.10.0 (optional)  

|v1.25.0
a|
* netapp/trident:22.10.0                      
* netapp/trident-autosupport:22.10                   
* k8s.io/sig-storage/csi-provisioner:v3.3.0           
* k8s.io/sig-storage/csi-attacher:v4.0.0              
* k8s.io/sig-storage/csi-resizer:v1.6.0               
* k8s.io/sig-storage/csi-snapshotter:v3.0.3           
* k8s.io/sig-storage/csi-node-driver-registrar:v2.5.1 
* netapp/trident-operator:22.10.0 (optional)  

|===

NOTE: On Kubernetes version 1.20 and above, use the validated `registry.k8s.gcr.io/sig-storage/csi-snapshotter:v6.x` image only if the `v1` version is serving the `volumesnapshots.snapshot.storage.k8s.gcr.io` CRD. If the `v1beta1` version is serving the CRD with/without the `v1` version, use the validated `registry.k8s.gcr.io/sig-storage/csi-snapshotter:v3.x` image.

