---
sidebar: sidebar
permalink: trident-get-started/requirements.html
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes
summary: Before installing Astra Trident you should review these general system requirements. Specific backends might have additional requirements. 
---

= Requirements
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Before installing Astra Trident you should review these general system requirements. Specific backends might have additional requirements. 

== Critical information about Astra Trident
*You must read the following critical information about Astra Trident.*

// Start snippet: collapsible block (open on page load)
.*Critical information about Astra Trident*
[%collapsible%open]
====
* Kubernetes 1.28 is now supported in Trident. Upgrade Astra Trident prior to upgrading Kubernetes.
* Astra Trident strictly enforces the use of multipathing configuration in SAN environments, with a recommended value of `find_multipaths: no` in multipath.conf file. 
+
Use of non-multipathing configuration or use of `find_multipaths: yes` or `find_multipaths: smart` value in multipath.conf file will result in mount failures. Astra Trident has recommended the use of `find_multipaths: no` since the 21.07 release.
====
// End snippet

== Supported frontends (orchestrators)

Astra Trident supports multiple container engines and orchestrators, including the following:

* Anthos On-Prem (VMware) and Anthos on bare metal 1.12
* Kubernetes 1.23 - 1.28
* Mirantis Kubernetes Engine 3.5
* OpenShift 4.10 - 4.13

The Trident operator is supported with these releases:

* Anthos On-Prem (VMware) and Anthos on bare metal 1.12
* Kubernetes 1.23 - 1.28
* OpenShift 4.10 - 4.13

Astra Trident also works with a host of other fully-managed and self-managed Kubernetes offerings, including Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Rancher, and VMWare Tanzu Portfolio.

WARNING: Before upgrading a Kubernetes cluster from 1.24 to 1.25 or later that has Astra Trident installed, refer to link:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-installation[Upgrade a Helm installation].

== Supported backends (storage)

To use Astra Trident, you need one or more of the following supported backends:

* Amazon FSx for NetApp ONTAP
* Azure NetApp Files
* Cloud Volumes ONTAP
* Cloud Volumes Service for GCP
* FAS/AFF/Select 9.5 or later
* NetApp All SAN Array (ASA)
* NetApp HCI/Element software 11 or above

== Feature requirements

The table below summarizes the features available with this release of Astra Trident and the versions of Kubernetes it supports.

[cols=3,options="header"]
|===
|Feature
|Kubernetes version
|Feature gates required?

|Astra Trident

a|1.23 - 1.28
a|No

|Volume Snapshots
a|1.23 - 1.28
a|No

|PVC from Volume Snapshots
a|1.23 - 1.28
a|No

|iSCSI PV resize
a|1.23 - 1.28
a|No

|ONTAP Bidirectional CHAP
a|1.23 - 1.28
a|No

|Dynamic Export Policies
a|1.23 - 1.28
a|No

|Trident Operator
a|1.23 - 1.28
a|No

|CSI Topology
a|1.23 - 1.28
a|No

|===

== Tested host operating systems

Though Astra Trident does not officially support specific operating systems, the following are known to work:

* RedHat CoreOS (RHCOS) versions as supported by OpenShift Container Platform (AMD64 and ARM64)
* RHEL 8+ (AMD64 and ARM64)
+
NOTE: NVMe/TCP requires RHEL 9 or later.
* Ubuntu 22.04 or later (AMD64 and ARM64)
* Windows Server 2019 (AMD64)

By default, Astra Trident runs in a container and will, therefore, run on any Linux worker. However, those workers need to be able to mount the volumes that Astra Trident provides using the standard NFS client or iSCSI initiator, depending on the backends you are using.

The `tridentctl` utility also runs on any of these distributions of Linux.

== Host configuration

All worker nodes in the Kubernetes cluster must be able to mount the volumes you have provisioned for your pods. To prepare the worker nodes, you must install NFS, iSCSI, or NVMe tools based on your driver selection. 

link:../trident-use/worker-node-prep.html[Prepare the worker node]

== Storage system configuration

Astra Trident might require changes to a storage system before a backend configuration can use it. 

link:../trident-use/backends.html[Configure backends]

== Astra Trident ports

Astra Trident requires access to specific ports for communication. 

link:../trident-reference/ports.html[Astra Trident ports]

== Container images and corresponding Kubernetes versions

For air-gapped installations, the following list is a reference of container images needed to install Astra Trident. Use the `tridentctl images` command to verify the list of needed container images.

[cols=2,options="header"]
|===
|Kubernetes version
|Container image

|v1.23.0
a|
* docker.io/netapp/trident:23.10.0                      
* docker.io/netapp/trident-autosupport:23.10                  
* registry.k8s.io/sig-storage/csi-provisioner:v3.6.0 
* registry.k8s.io/sig-storage/csi-attacher:v4.4.0              
* registry.k8s.io/sig-storage/csi-resizer:v1.9.0               
* registry.k8s.io/sig-storage/csi-snapshotter:v6.3.0           
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0 
* docker.io/netapp/trident-operator:23.10.0 (optional)  

|v1.24.0
a|
* docker.io/netapp/trident:23.10.0                      
* docker.io/netapp/trident-autosupport:23.10                   
* registry.k8s.io/sig-storage/csi-provisioner:v3.6.0 
* registry.k8s.io/sig-storage/csi-attacher:v4.4.0           
* registry.k8s.io/sig-storage/csi-resizer:v1.9.0               
* registry.k8s.io/sig-storage/csi-snapshotter:v6.3.0           
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0 
* docker.io/netapp/trident-operator:23.10.0 (optional)  

|v1.25.0
a|
* docker.io/netapp/trident:23.10.0                      
* docker.io/netapp/trident-autosupport:23.10                  
* registry.k8s.io/sig-storage/csi-provisioner:v3.6.0 
* registry.k8s.io/sig-storage/csi-attacher:v4.4.0              
* registry.k8s.io/sig-storage/csi-resizer:v1.9.0               
* registry.k8s.io/sig-storage/csi-snapshotter:v6.3.0           
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0 
* docker.io/netapp/trident-operator:23.10.0 (optional)    

|v1.26.0
a|
* docker.io/netapp/trident:23.10.0                      
* docker.io/netapp/trident-autosupport:23.10                   
* registry.k8s.io/sig-storage/csi-provisioner:v3.6.0 
* registry.k8s.io/sig-storage/csi-attacher:v4.4.0             
* registry.k8s.io/sig-storage/csi-resizer:v1.9.0               
* registry.k8s.io/sig-storage/csi-snapshotter:v6.3.0           
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0 
* docker.io/netapp/trident-operator:23.10.0 (optional)  

|v1.27.0
a|
* docker.io/netapp/trident:23.10.0
* docker.io/netapp/trident-autosupport:23.10 
* registry.k8s.io/sig-storage/csi-provisioner:v3.6.0 
* registry.k8s.io/sig-storage/csi-attacher:v4.4.0 
* registry.k8s.io/sig-storage/csi-resizer:v1.9.0
* registry.k8s.io/sig-storage/csi-snapshotter:v6.3.0
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0
* docker.io/netapp/trident-operator:23.10.0 (optional)

|v1.28.0
a|
* docker.io/netapp/trident:23.10.0
* docker.io/netapp/trident-autosupport:23.10 
* registry.k8s.io/sig-storage/csi-provisioner:v3.6.0 
* registry.k8s.io/sig-storage/csi-attacher:v4.4.0 
* registry.k8s.io/sig-storage/csi-resizer:v1.9.0
* registry.k8s.io/sig-storage/csi-snapshotter:v6.3.0
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0
* docker.io/netapp/trident-operator:23.10.0 (optional)


|===

