---
sidebar: sidebar
permalink: trident-concepts/automatic-workernode.html
keywords: beta feature, trident, automatic worker node, worker node prep, preparation, NFS, iSCSI
summary: Trident can automatically install the required NFS and iSCSI tools on the nodes present in the Kubernetes cluster.
---

= Automatic worker node preparation
:hardbreaks:
:icons: font
:imagesdir: ../media/

Trident can automatically install the required `NFS` and `iSCSI` tools
on the nodes present in the Kubernetes cluster. This is a *beta feature* and
is *not meant for* production clusters. Today, the feature is
available for nodes that run *CentOS, RHEL, and Ubuntu*.

For this feature, Trident includes a new install flag: `--enable-node-prep` for installations deployed with `tridentctl`. For deployments with the Trident operator, use the Boolean option
`enableNodePrep`.

WARNING: The `--enable-node-prep` installation option tells Trident to
install and ensure that NFS and iSCSI packages and/or services are
running when a volume is mounted on a worker node. This is a *beta
feature* meant to be used in dev/test environments that is *not
qualified* for production use.

When the `--enable-node-prep` flag is included for Trident installations
deployed with `tridentctl`, the following happens:

. As part of the installation, Trident registers the nodes it runs on.
. When a PVC request is made, Trident creates a PV from one of the
backends it manages.
. Using the PVC in a pod would require Trident to mount the volume on
the node the pod runs on. Trident attempts to install the required
NFS/iSCSI client utilities and to ensure that the required services are
active. This is done before mounting the volume.

The preparation of a worker node is done only once as part of the first
attempt made to mount a volume. All subsequent volume mounts should
succeed as long as no changes outside Trident touch the `NFS` and
`iSCSI` utilities.

In this manner, Trident can make sure that all the nodes in a Kubernetes
cluster have the required utilities needed to mount and attach volumes.
For NFS volumes, the export policy should also permit the volume to be
mounted. Trident can automatically manage export policies per backend;
alternatively, users can manage export policies out-of-band.
