---
sidebar: sidebar
permalink: trident-concepts/intro.html
keywords: product overview, astra trident
summary: Provisioning in Astra Trident has two primary phases. The first phase associates a storage class with the set of suitable backend storage pools and occurs as a necessary preparation before provisioning. The second phase includes the volume creation itself and requires choosing a storage pool from those associated with the pending volume’s storage class.
---

= Intro to Astra Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

Astra Trident is a fully supported open source project maintained by NetApp. It has been designed from the ground up to help you meet your containerized applications’ persistence demands using industry-standard interfaces, such as the Container Storage Interface (CSI).

Astra Trident deploys in Kubernetes clusters as pods and provides dynamic storage orchestration services for your Kubernetes workloads. It enables your containerized applications to quickly and easily consume persistent storage from NetApp’s broad portfolio that includes ONTAP (AFF/FAS/Select/Cloud/Amazon FSx for NetApp ONTAP), Element software (NetApp HCI/SolidFire), as well as the Azure NetApp Files service, Cloud Volumes Service on Google Cloud, and the Cloud Volumes Service on AWS.

Astra Trident is also a foundational technology for NetApp’s Astra, which addresses your data protection, disaster recovery, portability, and migration use cases for Kubernetes workloads leveraging NetApp’s industry-leading data management technology for snapshots, backups, replication, and cloning.

== What is Astra?

Astra makes it easier for enterprises to manage, protect, and move their data-rich containerized workloads running on Kubernetes within and across public clouds and on-premises. Astra provisions and provides persistent container storage using Astra Trident from NetApp’s proven and expansive storage portfolio in the public cloud and on-premises. It also offers a rich set of advanced application-aware data management functionality, such as snapshot, backup and restore, activity logs, and active cloning for data protection, disaster/data recovery, data audit, and migration use-cases for Kubernetes workloads.

Take a look at the Astra documentation to get started today. You can sign up for a free trial today on the Astra page.

* https://docs.netapp.com/us-en/astra/get-started/intro.html[Intro to Astra Control Service^]
* https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html[Get started with Astra API^]
* https://docs.netapp.com/us-en/astra-control-center/concepts/intro.html[Learn about Astra Control Center^]
