---
sidebar: sidebar
permalink: trident-concepts/intro.html
keywords: product overview, astra trident, fsx, element, astra, google cloud, cvs
summary: Astra Trident is a fully supported open source project maintained by NetApp as part of the Astra product family. It has been designed to help you meet your containerized applications’ persistence demands using industry-standard interfaces, such as the Container Storage Interface (CSI).
---

= Intro to Astra Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

Astra Trident is a fully supported open source project maintained by NetApp as part of the link:https://docs.netapp.com/us-en/astra-family/intro-family.html[Astra product family^]. It has been designed to help you meet your containerized applications’ persistence demands using industry-standard interfaces, such as the Container Storage Interface (CSI).

Astra Trident deploys in Kubernetes clusters as pods and provides dynamic storage orchestration services for your Kubernetes workloads. It enables your containerized applications to quickly and easily consume persistent storage from NetApp’s broad portfolio that includes ONTAP (AFF/FAS/Select/Cloud/Amazon FSx for NetApp ONTAP), Element software (NetApp HCI/SolidFire), Astra Data Store, as well as the Azure NetApp Files service, and Cloud Volumes Service on Google Cloud.

Astra Trident is also a foundational technology for NetApp’s Astra, which addresses your data protection, disaster recovery, portability, and migration use cases for Kubernetes workloads leveraging NetApp’s industry-leading data management technology for snapshots, backups, replication, and cloning.

== Supported Kubernetes cluster architectures

Astra Trident is supported with the following Kubernetes architectures:

[cols=3*,options="header"]
|===
|Kubernetes cluster architectures
|Supported
|Default install
|Single master, compute |Yes a| Yes
|Multiple master, compute |Yes a|
Yes
|Master, `etcd`, compute |Yes a|
Yes
|Master, infrastructure, compute |Yes a|
Yes
|===

== What is Astra?

Astra makes it easier for enterprises to manage, protect, and move their data-rich containerized workloads running on Kubernetes within and across public clouds and on-premises. Astra provisions and provides persistent container storage using Astra Trident from NetApp’s proven and expansive storage portfolio in the public cloud and on-premises. It also offers a rich set of advanced application-aware data management functionality, such as snapshot, backup and restore, activity logs, and active cloning for data protection, disaster/data recovery, data audit, and migration use-cases for Kubernetes workloads.

You can sign up for a free trial on the Astra page.

== For more information

* https://docs.netapp.com/us-en/astra-family/intro-family.html[NetApp Astra product family]
* https://docs.netapp.com/us-en/astra/get-started/intro.html[Astra Control Service documentation^]
* https://docs.netapp.com/us-en/astra-control-center/index.html[Astra Control Center documentation^]
* https://docs.netapp.com/us-en/astra-data-store/index.html[Astra Data Store documentation^]
* https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html[Astra API documentation^]
