---
sidebar: sidebar
permalink: trident-concepts/k8s-storage.html
keywords: kubernetes objects, persistent volume claim, storage class, backend, snapshot, persistent volume
summary: The Kubernetes storage paradigm includes several entities, which are important to each stage of requesting, consuming, and managing storage for containerized applications. At a high level, Kubernetes uses three types of objects for storage.
---

= Kubernetes storage concepts
:hardbreaks:
:icons: font
:imagesdir: ../media/

The Kubernetes storage paradigm includes several entities, which are important to each stage of requesting, consuming, and managing storage for containerized applications. At a high level, Kubernetes uses three types of objects for storage.

== Persistent Volume Claim

Persistent Volume Claims (PVCs) are used by applications to request access to storage resources. At a minimum, a PVC includes two key parameters, Size and Access mode. Storage Class is optional.

See the following table for information about the PVC parameters and their descriptions:

[cols=2*,options="header",cols="25,75"]
|===
| Parameter
| Description
| Size | The capacity desired by an application component.
| Access mode | The rules for accessing the storage volume. The PVC can use one of three access modes:
Read Write Once (RWO): Only one node is allowed to have read/write access to the storage volume at a time.
Read Only Many (ROX): Many nodes can access the storage volume in read-only mode.
Read Write Many (RWX): Many nodes can simultaneously read and write to the storage volume.
| Storage Class (optional) | Identifies which Storage Class to request for this PVC.
|===

NOTE: For more information about PVCs, see the https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims[Kubernetes PVC^] or https://docs.openshift.com/container-platform/3.11/architecture/additional_concepts/storage.html#persistent-volume-claims[OpenShift PVC^] documentation.

== Persistent Volume

Persistent Volumes (PVs) are Kubernetes objects that describe how to connect to a storage device. Kubernetes supports many different types of storage. NetApp platforms and services support NFS and iSCSI protocols. At a minimum, the PV should contain these parameters:

[cols=2*,options="header",cols="25,75"]
|===
| Parameter
| Description
| Capacity | The size of the volume represented by the object. For example, “5Gi”.
| Access mode | The rules for accessing the storage volume. It depends on the protocol used. The PVC can use one of three access modes:
Read Write Once (RWO): Only one node is allowed to have read/write access to the storage volume at a time. Supported by all PVs.
Read Only Many (ROX): Many nodes can access the storage volume in read-only mode. Supported primarily by file and file-like protocols. For example, NFS and CephFS. However, some block protocols are supported, such as iSCSI.
Read Write Many (RWX): Many nodes can simultaneously read and write to the storage volume. Supported by file and file-like protocols, such as, NFS and also supported by iSCSI raw block devices.
| Protocol  | Type of protocol (for example, “iSCSI” or “NFS”) to use and additional information needed to access the storage. For example, an NFS PV requires the NFS server and a mount path.
| Reclaim policy | Describes the Kubernetes action when the PV is released. Three reclaim policy options are available:
Retain: Mark the volume as waiting for administrator action. The volume cannot be reissued to another PVC.
Recycle: Kubernetes connects the volume to a temporary pod and issues a `rm -rf` command to clear the data after the volume is released. This is only supported by NFS volumes.
Delete: Kubernetes deletes the PV when it is released. However, Kubernetes does not delete the storage which was referenced by the PV. A storage administrator should delete the volume on the backend.
|===

NOTE: For more information about PVs, see the https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes[Kubernetes PV^] or https://docs.openshift.com/container-platform/3.11/architecture/additional_concepts/storage.html#persistent-volumes[OpenShift PV^] documentation.

== Storage Class

Kubernetes uses the Storage Class object to describe storage with specific characteristics. An administrator might define several Storage Classes that each define different storage properties. The Storage Classes are used by the PVC to provision storage. A Storage Class can have a provisioner associated with it that triggers Kubernetes to wait for the volume to be provisioned by the specified provider. In the case of Trident, the provisioner identifier used is `netapp.io/trident`. The value of the provisioner for Trident using its enhanced CSI provisioner is `csi.trident.netapp.io`.

A Storage Class object in Kubernetes has only two required fields:

[cols=2*,options="header",cols="25,75"]
|===
| Parameter
| Description
| Name | Uniquely identifies the Storage Class from the PVC.
| Provisioner | Identifies which plug-in to use to provision the volume. You can find the full list of provisioners in the https://kubernetes.io/docs/concepts/storage/storage-classes/[Kubernetes documentation^].
The provisioner used might require additional attributes which will be specific to the provisioner used. Additionally, the Storage Class might have a reclaim policy and mount options specified, which are applied to all the volumes created for that storage class.
|===

NOTE: For more information about storage classes, see the https://kubernetes.io/docs/concepts/storage/storage-classes/[Kubernetes^] or https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/dynamically_provisioning_pvs.html[OpenShift^] documentation.
