---
sidebar: sidebar
permalink: trident-concepts/vol-access-groups.html
keywords: volume access groups, element, solidfire, chap, trident, hci, netapp hci, storage system, access volumes,
summary: Learn more about how Trident uses volume access groups.
---

= Volume access groups
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn more about how Trident uses https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html[volume access groups^].

NOTE: Ignore this section if you are using CHAP, which is recommended to simplify management and avoid the scaling limit described below. In addition, if using Trident in CSI mode, you can ignore this section. Trident uses CHAP when installed as an enhanced CSI provisioner.

Trident can use volume access groups to control access to the volumes that it provisions. If CHAP is disabled, it expects to find an access group called `trident` unless you specify one or more access group IDs in the configuration.

While Trident associates new volumes with the configured access group(s), it does not create or otherwise manage access groups themselves. The access group(s) must exist before the storage backend is added to Trident, and they need to contain the iSCSI IQNs from every node in the Kubernetes cluster that could potentially mount the volumes provisioned by that backend. In most installations, that includes every worker node in the cluster.

For Kubernetes clusters with more than 64 nodes, you will need to use multiple access groups. Each access group may contain up to 64 IQNs, and each volume can belong to four access groups. With the maximum four access groups configured, any node in a cluster up to 256 nodes in size will be able to access any volume. For latest limits on volume access groups, see https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html[here^].

If you’re modifying the configuration from one that is using the default `trident` access group to one that uses others as well, include the ID for the `trident` access group in the list.
