---
sidebar: sidebar
permalink: trident-reco/deploy-reco.html
keywords: deployment, deploy, trident, namespace
summary: Use the recommendations listed here when you deploy Trident.
---

= Deployment
:hardbreaks:
:icons: font
:imagesdir: ../media/

Use the recommendations listed here when you deploy Trident.

== Deploy Trident to a dedicated namespace

https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/[Namespaces^] provide administrative separation between different applications and are a barrier for resource sharing. For example, a PVC from one namespace cannot be consumed from another. Trident provides PV resources to all the namespaces in the Kubernetes cluster and consequently leverages a service account which has elevated privileges.

Additionally, access to the Trident pod might enable a user to access storage system credentials and other sensitive information.  It is important to ensure that application users and management applications do not have the ability to access the Trident object definitions or the pods themselves.

== Use quotas and range limits to control storage consumption

Kubernetes has two features which, when combined, provide a powerful mechanism for limiting the resource consumption by applications.  The https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota[storage quota mechanism^] enables the administrator to implement global, and storage class specific, capacity and object count consumption limits on a per-namespace basis. Further, using a https://kubernetes.io/docs/tasks/administer-cluster/limit-storage-consumption/#limitrange-to-limit-requests-for-storage[range limit^] ensures that the PVC requests are within both a minimum and maximum value before the request is forwarded to the provisioner.

These values are defined on a per-namespace basis, which means that each namespace should have values defined which fall in line with their resource requirements. See here for information about https://netapp.io/2017/06/09/self-provisioning-storage-kubernetes-without-worry[how to leverage quotas^].
