---
sidebar: sidebar
permalink: trident-reco/security-reco.html
keywords: security, chap, trident, namespace, nve, nae, encryption, volume encryption, aggregate encryption
summary: Use the recommendations listed here to ensure that your Astra Trident installation is secure.
---

= Security
:hardbreaks:
:icons: font
:imagesdir: ../media/

Use the recommendations listed here to ensure that your Astra Trident installation is secure.

== Run Astra Trident in its own namespace

It is important to prevent applications, application administrators, users, and management applications from accessing Astra Trident object definitions or the pods to ensure reliable storage and block potential malicious activity.

To separate the other applications and users from Astra Trident, always install Astra Trident in its own Kubernetes namespace (`trident`). Putting Astra Trident in its own namespace assures that only the Kubernetes administrative personnel have access to the Astra Trident pod and the artifacts (such as backend and CHAP secrets if applicable) stored in the namespaced CRD objects.
You should ensure that you allow only administrators access to the Astra Trident namespace and thus access to the `tridentctl` application.

== Use CHAP authentication with ONTAP SAN backends

Astra Trident supports CHAP-based authentication for ONTAP SAN workloads (using the `ontap-san` and `ontap-san-economy` drivers). NetApp recommends using bidirectional CHAP with Astra Trident for authentication between a host and the storage backend.

For ONTAP backends that use the SAN storage drivers, Astra Trident can set up bidirectional CHAP and manage CHAP usernames and secrets through `tridentctl`.
See link:../trident-use/ontap-san-prep.html[here] to understand how Astra Trident configures CHAP on ONTAP backends.

NOTE: CHAP support for ONTAP backends is available with Trident 20.04 and later.

== Use CHAP authentication with NetApp HCI and SolidFire backends

NetApp recommends deploying bidirectional CHAP to ensure authentication between a host and the NetApp HCI and SolidFire backends. Astra Trident uses a secret object that includes two CHAP passwords per tenant. When Trident is installed as a CSI provisioner, it manages the CHAP secrets and stores them in a `tridentvolume` CR object for the respective PV. When you create a PV, CSI Astra Trident uses the CHAP secrets to initiate an iSCSI session and communicate with the NetApp HCI and SolidFire system over CHAP.

NOTE: The volumes that are created by CSI Trident are not associated with any Volume Access Group.

In the non-CSI frontend, the attachment of volumes as devices on the worker nodes is handled by Kubernetes. After volume creation, Astra Trident makes an API call to the NetApp HCI/SolidFire system to retrieve the secrets if the secret for that tenant does not already exist. Astra Trident then passes the secrets on to Kubernetes. The kubelet located on each node accesses the secrets via the Kubernetes API and uses them to run/enable CHAP between each node accessing the volume and the NetApp HCI/SolidFire system where the volumes are located.

== Use NVE and NAE with ONTAP backends

NetApp ONTAP backends provide Federal Information Processing Standard (FIPS) 140-2–compliant data-at-rest encryption to protect sensitive data in the event a disk is stolen, returned, or repurposed. 

By default, ONTAP 9 and later include three encryption solutions using external key management or the link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html^[onboard key manager] (OKM):

* link:https://www.netapp.com/cyber-resilience/data-protection/storage-encryption/[NetApp Storage Encryption^] is a hardware solution using self-encrypting drives. 
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html^[NetApp Volume Encryption (NVE)] is a software solution that enables encryption of any data volume on any drive type. NVE is enabled using a unique key for each volume.
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-aggregate-level-encryption-nve-license-task.html^[NetApp Aggregate Encryption (NAE)] is a software solution enabling encryption of any data volume on any drive type. NAE is enabled using a unique key for each aggregate.

You can manually enable or disable NAE and NVE in Astra Trident.

NOTE: NAE and NVE do not affect ONTAP storage efficiency features; however, NVE volumes are excluded from aggregate deduplication.  

=== Enable NAE and NVE
In ONTAP 9.7 and later, NVE and NAE are enabled by default on  new volumes or aggregates. For ONTAP versions earlier than 9.7, you can manually enable or disable NAE. 

[role="tabbed-block"]
====
.Enable or disable NVE
--
To enable or disable NVE when creating the volume, use te `encrypt` flag with value `true` for enable or `false` for disable. The following example enables NVE on a volume:
[source,cli]
----
volume create -volume abc -aggregate aggr_encryp -size 10M encrypt true
----
--
.Enable or disable NAE
--
To enable or disable NAE when creating the aggregate, use the `encrypt-with-aggr-key` flag with value `true` for enable or `false` for disable. The following example disables NAE on an aggregate:
[source,cli]
----
storage aggregate create -aggregate OnPrem_HQ_01_SSD_1 -diskcount 23 -node OnPrem-HQ-01 -raidtype raid_dp -encrypt-with-aggr-key false
----
--
====




