---
sidebar: sidebar
permalink: trident-kubernetes/kubernetes-deploy-operator.html
keywords: deploy, trident, methods, operator, tridentctl, helm
summary: You can deploy Trident operator either manually or using Helm.
---

= Deploy by using the Trident operator
:hardbreaks:
:icons: font
:imagesdir: ../media/

You can deploy the Trident operator either manually or using Helm.

TIP: If you have not already familiarized yourself with the basic concepts <insert link>, now is a great time to do that.

.What you'll need

To deploy Trident by using the operator, the following prerequisites should be met:

* You have full privileges to a supported Kubernetes cluster running Kubernetes 1.14 and above.
* You have access to a supported NetApp storage system.
* You have the capability to mount volumes from all of the Kubernetes worker nodes.
* You have a Linux host with `kubectl` (or `oc`, if you are using OpenShift) installed and configured to manage the Kubernetes cluster that you want to use.
* You have set the `KUBECONFIG` environment variable to point to your Kubernetes cluster configuration.
* You have enabled the feature gates required by Trident. (INSERT LINK TO FEATURE REQUIREMENTS TOPIC.)
* If you are using Kubernetes with Docker Enterprise, https://docs.docker.com/ee/ucp/user-access/cli/[follow their steps to enable CLI access].

Got all that? Great! Let's get started.

== Deploy the Trident operator by using Helm

Perform the steps listed to deploy the Trident operator by using Helm.

.What you'll need

In addition to the prerequisites listed above, to deploy Trident Operator by using Helm, you need the following:

* Kubernetes 1.16 and later
* Helm version 3

.Steps

. Download the Trident 21.04 installer bundle from the https://github.com/netapp/trident/releases[Trident GitHub] page. The
installer bundle includes the Helm chart in the `/helm` directory.
. Use the `helm install` command and specify a name for your deployment.
See the following example:

[source,console]
----
$ helm install <name> trident-operator-21.01.0.tgz
----

There are two ways to pass configuration data during the install:

* `--values` (or `-f`): Specify a YAML file with overrides. This can be
specified multiple times and the rightmost file will take precedence.
* `--set`: Specify overrides on the command line.

For example, to change the default value of `debug`, run the following
`--set` command:

[source,console]
----
$ helm install <name> trident-operator-21.01.0.tgz --set tridentDebug=true
----

The `values.yaml` file, which is part of the Helm chart provides the
list of keys and their default values.

`helm list` shows you details about the Trident installation, such as
name, namespace, chart, status, app version, revision number, and so on.

== Deploy the Trident operator manually

Perform the steps listed to manually deploy the Trident operator.

=== Step 1: Qualify your Kubernetes cluster

The first thing you need to do is log in to the Linux host and verify that it is managing a _working_, supported Kubernetes cluster that you have the necessary privileges to.

NOTE: With OpenShift, use `oc` instead of `kubectl` in all of the examples that follow, and log in as *system:admin* first by
running `oc login -u system:admin` or `oc login -u kube-admin`.

[source,console]
----
# Is your Kubernetes version greater than 1.14?
kubectl version

# Are you a Kubernetes cluster administrator?
kubectl auth can-i '*' '*' --all-namespaces

# Can you launch a pod that uses an image from Docker Hub and can reach your
# storage system over the pod network?
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----

=== Step 2: Download and set up the operator

NOTE: Beginning with 21.01, the Trident Operator is cluster scoped. Using the Trident operator to install Trident requires creating the `TridentOrchestrator` Custom Resource Definition (CRD) and defining other resources. You should perform these steps to set up the operator before you can install Trident.

. Download the latest version of the https://github.com/NetApp/trident/releases/latest[Trident installer bundle] from the _Downloads_ section and extract it.
+
[source,console]
----
wget https://github.com/NetApp/trident/releases/download/v21.04/trident-installer-21.04.tar.gz
tar -xf trident-installer-21.04.tar.gz
cd trident-installer
----

. Use the appropriate CRD manifest to create the `TridentOrchestrator`
CRD. You then create a `TridentOrchestrator` Custom Resource later on to instantiate a Trident install by the operator.
+
[source,console]
----
# Is your Kubernetes version < 1.16?
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_pre1.16.yaml

# If not, your Kubernetes version must be 1.16 and above
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----

. After the `TridentOrchestrator` CRD is created, create the following resources required for the operator deployment:
* A ServiceAccount for the operator
* A ClusterRole and ClusterRoleBinding to the ServiceAccount
* A dedicated PodSecurityPolicy
* The operator itself
+
The Trident installer contains manifests for defining these resources. By default, the operator is deployed in the `trident` namespace. If the `trident` namespace does not exist, use the following manifest to create one.
+
[source,console]
----
$ kubectl apply -f deploy/namespace.yaml
----

. To deploy the operator in a namespace other than the
default `trident` namespace, you should update the
`serviceaccount.yaml`, `clusterrolebinding.yaml` and `operator.yaml` manifests and generate your `bundle.yaml`.
+
[source,console]
----
# Have you updated the yaml manifests? Generate your bundle.yaml
# using the kustomization.yaml
kubectl kustomize deploy/ > deploy/bundle.yaml

# Create the resources and deploy the operator
kubectl create -f deploy/bundle.yaml
----

. Verify the status of the operator after you have deployed:
+
[source,console]
----
$ kubectl get deployment -n <operator-namespace>
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
trident-operator   1/1     1            1           3m

$ kubectl get pods -n <operator-namespace>
NAME                              READY   STATUS             RESTARTS   AGE
trident-operator-54cb664d-lnjxh   1/1     Running            0          3m
----

The operator deployment successfully creates a pod running on one of the worker nodes in your cluster.

IMPORTANT: There should only be *one instance* of the operator in a Kubernetes cluster. Do not create multiple deployments of the Trident operator.

=== Step 3: Create `TridentOrchestrator` and install Trident

You are now ready to install Trident using the operator! This will require creating `TridentOrchestrator`. The Trident installer comes with example definitions for creating `TridentOrchestrator`. This kicks off a Trident installation in the `trident` namespace.
[source,console]
----
$ kubectl create -f deploy/crds/tridentorchestrator_cr.yaml
tridentorchestrator.trident.netapp.io/trident created

$ kubectl describe torc trident
Name:        trident
Namespace:
Labels:      <none>
Annotations: <none>
API Version: trident.netapp.io/v1
Kind:        TridentOrchestrator
...
Spec:
  Debug:     true
  Namespace: trident
Status:
  Current Installation Params:
    IPv6:                      false
    Autosupport Hostname:
    Autosupport Image:         netapp/trident-autosupport:21.04
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:                     true
    Enable Node Prep:          false
    Image Pull Secrets:
    Image Registry:
    k8sTimeout:           30
    Kubelet Dir:          /var/lib/kubelet
    Log Format:           text
    Silence Autosupport:  false
    Trident Image:        netapp/trident:21.04.0
  Message:                  Trident installed  Namespace:                trident
  Status:                   Installed
  Version:                  v21.04.0
Events:
    Type Reason Age From Message ---- ------ ---- ---- -------Normal
    Installing 74s trident-operator.netapp.io Installing Trident Normal
    Installed 67s trident-operator.netapp.io Trident installed
----

The Trident operator enables you to customize the manner in which Trident is installed by using the attributes in the `TridentOrchestrator` spec. See link:kubernetes-customize-deploy.html[Customize your Trident deployment^].

The Status of `TridentOrchestrator` indicates if the installation was successful and displays the version of Trident installed.
[width="100%",cols="20%,80%",options="header",]
|===
|Status |Description
|Installing |The operator is installing Trident using this
`TridentOrchestrator` CR.

|Installed |Trident has successfully installed.

|Uninstalling |The operator is uninstalling Trident, since
`spec.uninstall=true`.

|Uninstalled |Trident is uninstalled.

|Failed |The operator could not install, patch, update or uninstall
Trident; the

| |operator will automatically try to recover from this state. If this

| |state persists you will require troubleshooting.

|Updating |The operator is updating an existing Trident installation.

|Error |The `TridentOrchestrator` is not used. Another one already
exists.
|===

During the installation, the status of `TridentOrchestrator` changes from `Installing` to `Installed`. If you observe the `Failed` status and the operator is unable to recover by itself, you should  check the logs of the operator. See the link:../troubleshooting.html[Troubleshooting^] section.

You can confirm if the Trident installation completed by taking a look
at the pods that have been created:

[source,console]
----
$ kubectl get pod -n trident
NAME                                READY   STATUS    RESTARTS   AGE
trident-csi-7d466bf5c7-v4cpw        5/5     Running   0           1m
trident-csi-mr6zc                   2/2     Running   0           1m
trident-csi-xrp7w                   2/2     Running   0           1m
trident-csi-zh2jt                   2/2     Running   0           1m
trident-operator-766f7b8658-ldzsv   1/1     Running   0           3m
----
You can also use `tridentctl` to check the version of Trident installed.

[source,console]
----
$ ./tridentctl -n trident version
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 21.04.0        | 21.04.0        |
+----------------+----------------+
----
Now you can go ahead and create a Trident backend. See link:kubernetes-postdeployment.html[post-deployment tasks^].
