---
sidebar: sidebar
permalink: trident-deploy-k8s/kubernetes-deploy.html
keywords: deploy, trident, methods, operator, tridentctl, helm
summary: You can deploy Trident using the Trident operator or with `tridentctl`.
---

= Deploy Trident
:hardbreaks:
:icons: font
:imagesdir: ../media/

You can deploy Trident using the Trident operator or with `tridentctl`.

== Choose the deployment method

To determine which deployment method to use, consider the following:

=== Why should I use the Trident operator?

The Trident operator is a great way to dynamically manage Trident resources and automate the setup phase. There are some prerequisites that must be satisfied. See <insert link to Requirements> topic.

The Trident operator provides the following benefits:

* Self-healing capability: You can monitor a Trident installation and actively take measures to address issues, such as when the Trident deployment is deleted or if the installation is modified accidentally. When the operator is set up as a deployment, a `trident-operator-<generated-id>` pod is created. This pod associates a TridentOrchestrator CR with a Trident installation and always ensures there is only one active TridentOrchestrator. In other words, the operator ensures that there is only one instance of Trident in the cluster and controls its setup, making sure the installation is idempotent. When changes are made to the Trident install (such as, deleting the Trident deployment or node daemonset), the operator identifies them and fixes them individually.
* Easy updates to existing installations: You can easily update an existing Trident deployment with the operator. You only need to edit the TridentOrchestrator CR to make updates to a Trident installation.

.Enable Trident to generate debug logs
====
To do this, patch your TridentOrchestrator to set `spec.debug` to `true`:
----
kubectl patch torc <trident-orchestrator-name> -n trident --type=merge -p '{"spec":{"debug":true}}'
----
====

After the TridentOrchestrator is updated, the operator processes the updates and patches the existing installation. This might triggers the creation of new pods to modify the installation accordingly.

* Automatically handles Kubernetes upgrades: When the Kubernetes version of the cluster is upgraded to a supported
version, the operator updates an existing Trident installation
automatically and changes it to ensure that it meets the requirements of
the Kubernetes version.

NOTE: If the cluster is upgraded to an unsupported version, the operator prevents installing Trident. If Trident has already been
installed with the operator, a warning is displayed to indicate that
Trident is installed on an unsupported Kubernetes version.

=== Why should I use Helm?

If you have other applications that you are managing using Helm, starting with Trident 21.01, you can manage your Trident deployment also using Helm.

=== When should I use `tridenctl`?

If you have an existing Trident deployment that must be upgraded to or if you are looking to highly customize your Trident deployment, you should take a look at using `tridentctl`. This is the conventional method of deploying Trident.

== Consider before moving between deployment methods

It is not hard to imagine a scenario where moving between deployment methods is desired. You should consider the following before attempting to move from a `tridentctl` deployment to an operator-based deployment, or vice-versa:

* Always use the same method for uninstalling Trident. If you have deployed Trident with `tridentctl`, you should use the appropriate version of the `tridentctl` binary to uninstall Trident. Similarly, if deploying Trident with the operator, you should edit the TridentOrchestrator CR and set `spec.uninstall=true` to uninstall Trident.
* If you have a Trident operator deployment that you want to remove and use `tridentctl` to deploy Trident, you should first edit the TridentOrchestrator and set `spec.uninstall=true` to uninstall Trident. Then delete the TridentOrchestrator and the operator deployment. You can then install Trident with `tridentctl`.
* If you have a manual Trident operator deployment, and you want to use Helm-based Trident operator deployment, you should manually uninstall the operator first, and then do the Helm install. This enables Helm to deploy the Trident operator with the required labels and annotations. If you do not do this, your Helm-based Trident Operator deployment will fail with label validation error and annotation validation error. If you have a `tridentctl`-based deployment, you can use Helm-based deployment without running into issues.
