---
permalink: trident-protect/monitor-trident-protect-resources.html
sidebar: sidebar
keywords: manage, authentication, rbac
summary: "You can monitor the state of Trident protect resources using kube-state-metrics and Prometheus. This gives you health information about deployments, nodes, and pods."
---
= Monitor Trident protect resources
:icons: font
:imagesdir: ../media/

[.lead]
The kube-state-metrics service is an open source tool that generates metrics from Kubernetes API communication. Using it with Trident protect exposes useful information about the state of resources in your environment.

Prometheus is an open source monitoring toolkit that can ingest the data generated by kube-state-metrics and present it as easily readable information about these objects. Together, kube-state-metrics and Prometheus provide a way for you to monitor the health and status of the resources you are managing with Trident protect. 

To enable resource monitoring, you need to install and configure kube-state-metrics and Promethus separately, and configure them to work together.

NOTE: The configurations included in these steps are only examples; you will n eed to customize them to match your environment. Refer to the 

== Install kube-state-metrics
You can install kube-state-metrics using Helm. You will need to perform the following basic steps:

. Add the Helm chart
. Create a configuration
. Deploy the Helm chart 

.Steps
. Add the Helm chart. For example:
+
[source,console]
----
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
----

. Create a configuration file for the Helm chart (for example, `metrics-config.yaml`). You can customize the following example configuration to match your environment:
+
.metrics-config.yaml
[source,yaml]
----
---
extraArgs:
  # Collect only custom metrics
  - --custom-resource-state-only=true

customResourceState:
  enabled: true
  config:
    kind: CustomResourceStateMetrics
    spec:
      resources:
      - groupVersionKind:
          group: astra.netapp.io
          kind: "Backup"
          version: "v1"
        labelsFromPath:
          backup_uid: [metadata, uid]
          backup_name: [metadata, name]
          creation_time: [metadata, creationTimestamp]
        metrics:
        - name: backup_info
          help: "Exposes details about the Backup state"
          each:
            type: Info
            info:
              labelsFromPath:
                appVaultReference: ["spec", "appVaultRef"]
                appReference: ["spec", "applicationRef"]
rbac:
  extraRules:
  - apiGroups: ["backups.astra.netapp.io"]
    resources: ["backups"]
    verbs: ["list", "watch"]
 
# Collect metrics from all namespaces
namespaces: ""
 
# Ensure that the metrics are collected by Prometheus
prometheus:
  monitor:
    enabled: true
----

. Deploy the Helm chart. For example:
+
[source,console]
----
helm install custom-resource -f metrics-config.yaml prometheus-community/kube-state-metrics --version 5.21.0
----

== Install Prometheus
Refer to the https://prometheus.io/docs/prometheus/latest/installation/[official Prometheus documentation^] for Prometheus installation instructions.

== Integrate kube-state-metrics with Prometheus
After you install kube-state-metrics and Prometheus, you can integrate them to start monitoring your resources.

.Steps
. Edit the Prometheus configuration file (`prometheus.yml`) and add the kube-state-metrics service information. For example:
+
.prometheus.yml
[source,yaml]
----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: astra-connector
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.astra-connector.svc:8080']
----

== Configure Prometheus alerts
After you integrate Prometheus, you are ready to define alerting rules for resources in Prometheus. 

.Steps
. Edit the Prometheus configuration file (`prometheus.yml`) and add the following section to instruct Prometheus to send alerts to the Trident protect Alertmanager. For example:
+
.prometheus.yml: Send alerts to alertmanager
[source,yaml]
----
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager.astra-connector.svc:9093']
----

=== Send alerts to other channels
You can configure Alertmanager to send notifications to other channels, such as e-mail, PagerDuty, Microsoft Teams, or other notification services by specifying the respective configuration in the `alertmanager.yml` file.

== Alert examples
The following configuration examples cover common alerting scenarios that you can explore with Prometheus.


=== Backup alert example
The following example defines a critical alert that is triggered when the status of the backup custom resource is set to `Error` for 5 seconds or longer.

.rules.yml: Define an alert for failed backups
[source,yaml]
----
rules.yml: |
  groups:     
    - name: fail-backup
        rules:
          - alert: BackupFailed
            expr: kube_customresource_backup_info{status="Error"}
            for: 5s
            labels:
              severity: critical
            annotations:
              summary: "Backup Failed"
              description: "A Backup has failed."
----

=== 
