---
sidebar: sidebar
permalink: trident-protect/trident-protect-migrate-apps.html
keywords: trident, protect, migrate, storage, restore, backup
summary: You can restore your backup or snapshot data to a different cluster or storage class
---
= Migrate applications
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can restore your backup or snapshot data to a different cluster or storage class.

== Backup and restore operations

To perform backup and restore operations for the following scenarios, you can automate specific backup and restore tasks.

=== Clone to same cluster

To clone to the same cluster, create a snapshot or backup and restore the data to the same cluster.

.Steps

. Do one of the following:
.. link:trident-protect-protect-apps.html#create-an-on-demand-snapshot[Create a snapshot].
.. link:trident-protect-protect-apps.html#create-an-on-demand-backup[Create a backup].

. On the same cluster, do one of the following, depending on if you created a snapshot or a backup:
.. link:trident-protect-restore-apps.html#restore-from-a-snapshot-to-a-different-namespace[Restore your data from the snapshot].
.. link:trident-protect-restore-apps.html#restore-from-a-backup-to-a-different-namespace[Restore your data from the backup].

=== Clone to different cluster

To clone to a different cluster (perform a cross-cluster clone), create a snapshot or backup and restore the data to a different cluster. Make sure that Trident protect is installed on the destination cluster.

. Do one of the following:
.. link:trident-protect-protect-apps.html#create-an-on-demand-snapshot[Create a snapshot].
.. link:trident-protect-protect-apps.html#create-an-on-demand-backup[Create a backup].

. Ensure that the AppVault CR for the object storage bucket that contains the backup or snapshot has been configured on the destination cluster.
. On the destination cluster, do one of the following, depending on if you created a snapshot or a backup:
.. link:trident-protect-restore-apps.html#restore-from-a-snapshot-to-a-different-namespace[Restore your data from the snapshot].
.. link:trident-protect-restore-apps.html#restore-from-a-backup-to-a-different-namespace[Restore your data from the backup].

== Migrate data from one storage class to another storage class

You can migrate data from one storage class to a different storage class by restoring a snapshot to the different destination storage class.

For example (excluding the secrets from the restore):

[source,yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: "${snapshotRestoreCRName}"
spec:
  appArchivePath: "${snapshotArchivePath}"
  appVaultRef: "${appVaultCRName}"
  namespaceMapping:
    destination: "${destinationNamespace}"
    source: "${sourceNamespace}"
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
  resourceFilter:
    resourceMatchers:
      kind: Secret
      version: v1
    resourceSelectionCriteria: exclude
----

