---
sidebar: sidebar
permalink: trident-protect/trident-protect-installation.html
keywords: install, trident, protect, requirements, registry
summary: If your environment meets the requirements, you can follow these steps to install Trident protect.
---
= Install and configure Trident protect
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If your environment meets the requirements for Trident protect, you can follow these steps to install Trident protect on your cluster. You can obtain Trident protect from NetApp, or install it from your own private registry. Installing from a private registry is helpful if your cluster cannot access the Internet.

NOTE: By default, Trident protect collects support information that helps with any NetApp support cases that you might open, including logs, metrics, and topology information about clusters and managed applications. Trident protect sends these support bundles to NetApp on a daily schedule. You can optionally disable this support bundle collection when you install Trident protect. You can manually link:trident-protect-generate-support-bundle.html[generate a support bundle] at any time.

[role="tabbed-block"]
====
.Install Trident protect from NetApp
--
.Steps
. Add the Trident Helm repository:
+
[source,console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Install the Trident protect CRDs:
+
[source,console]
----
helm install trident-protect-crds netapp-trident-protect/trident-protect-crds --version 100.2410.0 --create-namespace --namespace trident-protect
----
. Use Helm to install Trident protect using one of the following commands. Replace `<name_of_cluster>` with a cluster name, which will be assigned to the cluster and used to identify the cluster's backups and snapshots:
+
* Install Trident protect normally:
+
[source,console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2410.0 --create-namespace --namespace trident-protect
----
+
* Install Trident protect and disable the scheduled daily Trident protect AutoSupport support bundle uploads:
+
[source,console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set autoSupport.enabled=false --set clusterName=<name_of_cluster> --version 100.2410.0 --create-namespace --namespace trident-protect
----
--
.Install Trident protect from a private registry
--
You can install Trident protect from a private image registry if your Kubernetes cluster is unable to access the Internet. In these examples, replace values in brackets with information from your environment:

.Steps
. Pull the following images to your local machine, update the tags, and then push them to your private registry:
+
[source,console]
----
netapp/controller:24.10.0
netapp/restic:24.10.0
netapp/kopia:24.10.0
netapp/trident-autosupport:24.10.0
netapp/exechook:24.10.0
netapp/resourcebackup:24.10.0
netapp/resourcerestore:24.10.0
netapp/resourcedelete:24.10.0
bitnami/kubectl:1.30.2
kubebuilder/kube-rbac-proxy:v0.16.0
----
+
For example:
+
[source,console]
----
docker pull netapp/controller:24.10.0
----
+
[source,console]
----
docker tag netapp/controller:24.10.0 <private-registry-url>/controller:24.10.0
----
+
[source,console]
----
docker push <private-registry-url>/controller:24.10.0
----

. Create the Trident protect system namespace:
+
[source,console]
----
kubectl create ns trident-protect
----
. Log in to the registry:
+
[source,console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. Create a pull secret to use for private registry authentication:
+
[source,console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----

. Add the Trident Helm repository:
+
[source,console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----

. Create a file named `protectValues.yaml` that contains the following Trident protect settings:
+
[source,yaml]
----
image:
  registry: <private-registry-url>
imagePullSecrets:
- name: regcred
controller:
  image:
    registry: <private-registry-url>
rbacProxy:
  image:
    registry: <private-registry-url>
crCleanup:
  imagePullSecrets:
  - name: regcred
webhooksCleanup:
  imagePullSecrets:
  - name: regcred
----

. Install the Trident protect CRDs:
+
[source,console]
----
helm install trident-protect-crds netapp-trident-protect/trident-protect-crds --version 100.2410.0 --create-namespace --namespace trident-protect
----
. Use Helm to install Trident protect using one of the following commands. Replace `<name_of_cluster>` with a cluster name, which will be assigned to the cluster and used to identify the cluster's backups and snapshots: 
+
* Install Trident protect normally:
+
[source,console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2410.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
+
* Install Trident protect and disable the scheduled daily Trident protect AutoSupport support bundle uploads:
+
[source,console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set autoSupport.enabled=false --set clusterName=<name_of_cluster> --version 100.2410.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
--
====

////
. Log in to the registry:
+
[source,console]
----
helm registry login cr.astra.netapp.io -u <account-id> -p <api-token>
----

. Create a pull secret:
+
[source,console]
----
kubectl create secret docker-registry regcred --docker-username=<account-id> --docker-password=<api-token> -n trident-protect --docker-server= cr.astra.netapp.io
----
////