---
sidebar: sidebar
permalink: trident-protect/trident-protect-use-execution-hooks.html
keywords: trident, protect, execution hooks 
summary: You can create a custom execution hook for an app using Trident protect. You need to have Owner, Admin, or Member permissions to create execution hooks.
---
= Create an execution hook
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can create a custom execution hook for an app using Trident protect. You need to have Owner, Admin, or Member permissions to create execution hooks.

. Create the custom resource (CR) file and name it `trident-protect-hook.yaml`.
+
. Configure the following attributes to match your Trident protect environment and cluster configuration:
+
* *metadata.name*: (_Required_) The name of this custom resource; choose a unique and sensible name for your environment.
* *spec.applicationRef*: (_Required_) The Kubernetes name of the application for which to run the execution hook.
* *spec.stage*: (_Required_) A string indicating which stage during the action that the execution hook should run. Possible values:
** Pre
** Post
* *spec.action*: (_Required_) A string indicating which action the execution hook will take, assuming any execution hook filters specified are matched. Possible values:
** Snapshot
** Backup
** Restore
** Failover
* *spec.enabled*: (_Optional_) Indicates whether this execution hook is enabled or disabled. If not specified, the default value is true.
* *spec.hookSource*: (_Required_) A string containing the base64-encoded hook script.
* *spec.timeout*: (_Optional_) A number defining how long in minutes that the execution hook is allowed to run. The minimum value is 1 minute, and the default value is 25 minutes if not specified.
* *spec.arguments*: (_Optional_) A YAML list of arguments that you can specify for the execution hook.
* *spec.matchingCriteria*: (_Optional_) An optional list of criteria key value pairs, each pair making up an execution hook filter. You can add up to 10 filters per execution hook.
* *spec.matchingCriteria.type*: (_Optional_) A string identifying the execution hook filter type. Possible values:
** ContainerImage
** ContainerName
** PodName
** PodLabel
** NamespaceName
* *spec.matchingCriteria.value*: (_Optional_) A string or regular expression identifying the execution hook filter value.
+
*Example YAML*:
+
-----
apiVersion: protect.trident.netapp.io/v1
kind: ExecHook
metadata: 
  name: example-hook-cr
  annotations: 
    astra.netapp.io/astra-control-hook-source-id: /account/test/hookSource/id
spec: 
  applicationRef: my-app-name
  stage: pre
  action: snapshot
  enabled: true
  hookSource: IyEmlhookNoCmsourcegZmg85lcCAxCexamplekGZQo=
  timeout: 10
  arguments: 
    - FirstExampleArg
    - SecondExampleArg
  matchingCriteria: 
    - type: containerName
      value: mysql
    - type: containerImage
      value: bitnami/mysql
    - type: podName
      value: mysql
    - type: namespaceName
      value: mysql-a
    - type: podLabel
      value: app.kubernetes.io/component=primary
    - type: podLabel
      value: helm.sh/chart=mysql-10.1.0
    - type: podLabel
      value: deployment-type=production
-----
+ 
. After you populate the CR file with the correct values, apply the CR:

----- 
kubectl apply -f trident-protect-hook.yaml
-----


