---
sidebar: sidebar
permalink: trident-protect/trident-protect-upgrade.html
keywords: trident, protect, netapp, upgrade, new, version
summary: You can upgrade Trident protect to the latest version to take advantage of new features or bug fixes. 
---
= Upgrade Trident protect
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can upgrade Trident protect to the latest version to take advantage of new features or bug fixes.

[NOTE]
====
When you upgrade from version 24.10, snapshots running during the upgrade might fail.  This failure does not prevent future snapshots, whether manual or scheduled, from being created. If a snapshot fails during the upgrade, you can manually create a new snapshot to ensure your application is protected.
To avoid potential failures, you can disable all snapshot schedules before the upgrade and re-enable them afterward. However, this results in missing any scheduled snapshots during the upgrade period.
====


To upgrade Trident protect, perform the following steps.

.Steps
. Update the Trident Helm repository:
+
[source,console]
----
helm repo update
----
. Upgrade the Trident protect CRDs:
+
[source,console]
----
helm upgrade trident-protect-crds netapp-trident-protect/trident-protect-crds --version 100.2502.0  --namespace trident-protect
----
. Upgrade Trident protect:
+
[source,console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2502.0 --namespace trident-protect
----
