---
sidebar: sidebar
permalink: trident-protect/trident-protect-migrate-apps.html
keywords: trident, protect, migrate, storage, restore, backup
summary: You can restore your backup or snapshot data to a different cluster or storage class
---
= Migrate applications
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can migrate your applications between clusters or storage classes by restoring your backup or snapshot data to a different cluster or storage class.

== Backup and restore operations

To perform backup and restore operations for the following scenarios, you can automate specific backup and restore tasks.

=== Clone to same cluster

To clone an application to the same cluster, create a snapshot or backup and restore the data to the same cluster.

.Steps

. Do one of the following:
.. link:trident-protect-protect-apps.html#create-an-on-demand-snapshot[Create a snapshot].
.. link:trident-protect-protect-apps.html#create-an-on-demand-backup[Create a backup].

. On the same cluster, do one of the following, depending on if you created a snapshot or a backup:
.. link:trident-protect-restore-apps.html#restore-from-a-snapshot-to-a-different-namespace[Restore your data from the snapshot].
.. link:trident-protect-restore-apps.html#restore-from-a-backup-to-a-different-namespace[Restore your data from the backup].

=== Clone to different cluster

To clone an application to a different cluster (perform a cross-cluster clone), create a snapshot or backup and restore the data to a different cluster. Make sure that Trident protect is installed on the destination cluster.

.Steps

. Do one of the following:
.. link:trident-protect-protect-apps.html#create-an-on-demand-snapshot[Create a snapshot].
.. link:trident-protect-protect-apps.html#create-an-on-demand-backup[Create a backup].

. Ensure that the AppVault CR for the object storage bucket that contains the backup or snapshot has been configured on the destination cluster.
. On the destination cluster, do one of the following, depending on if you created a snapshot or a backup:
.. link:trident-protect-restore-apps.html#restore-from-a-snapshot-to-a-different-namespace[Restore your data from the snapshot].
.. link:trident-protect-restore-apps.html#restore-from-a-backup-to-a-different-namespace[Restore your data from the backup].

== Migrate applications from one storage class to another storage class

You can migrate applications from one storage class to a different storage class by restoring a snapshot to the different destination storage class.

For example (excluding the secrets from the restore CR):

[source,yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: "${snapshotRestoreCRName}"
spec:
  appArchivePath: "${snapshotArchivePath}"
  appVaultRef: "${appVaultCRName}"
  namespaceMapping:
    destination: "${destinationNamespace}"
    source: "${sourceNamespace}"
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
  resourceFilter:
    resourceMatchers:
      kind: Secret
      version: v1
    resourceSelectionCriteria: exclude
----

// begin tabbed block
[role="tabbed-block"]
====
.Restore the snapshot using a CR
--
. Create the custom resource (CR) file and name it `trident-protect-snapshot-restore-cr.yaml`. Update the values in brackets <> to match your Trident protect environment and cluster configuration:
+
* <CR_NAME>: The name of this CR operation; choose a sensible name for your environment.
* <APPVAULT_NAME>: The name of the AppVault where the snapshot contents are stored.
* <SNAPSHOT_PATH>: The path inside AppVault where the snapshot contents are stored. You can use the following command to find this path:
+
[source,console]
-----
kubectl get snapshots <SNAPHOT_NAME> -n trident-protect -o jsonpath='{.status.appArchivePath}'
-----
+
* <SOURCE_NAMESPACE>: The source namespace of the restore operation.
* <DESTINATION_NAMESPACE>: The destination namespace of the restore operation.
+
[source,yaml]
-------
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: <CR_NAME>
  namespace: trident-protect
spec:
  appArchivePath: <SNAPSHOT_PATH>
  appVaultRef: <APPVAULT_NAME>
  namespaceMapping: [{"source": "<SOURCE_NAMESPACE>", "destination": "<DESTINATION_NAMESPACE>"}]
-------
+
. (_Optional_) If you need to select only certain resources of the application to restore, add filtering that includes or excludes resources marked with particular labels:
+
* "<INCLUDE-EXCLUDE>": (Required for filtering) Use `include or exclude` to include or exclude a resource defined in resourceMatchers. Add the following resourceMatchers parameters to define the resources to be included or excluded:
+
* <GROUP>: (_Optional_) Group of the resource to be filtered.
* <KIND>: (_Optional_) Kind of the resource to be filtered.
* <VERSION>: (_Optional_) Version of the resource to be filtered.
* <NAMES>: (_Optional_) Names in the Kubernetes metadata.name field of the resource to be filtered.
* <NAMESPACES>: (_Optional_) Namespaces in the Kubernetes metadata.name field of the resource to be filtered.
* <SELECTORS>: (_Optional_) Label selector string in the Kubernetes metadata.name field of the resource as defined in the https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Kubernetes documentation^]. Example: `"trident.netapp.io/os=linux"`. 
+
For example:
+
[source,yaml]
-------
spec:    
  resourceFilter: 
    resourceSelectionCriteria: "<INCLUDE-EXCLUDE>"
    resourceMatchers:
      group: <GROUP>
      kind: <KIND>
      version: <VERSION>
      names: <NAMES>
      namespaces: <NAMESPACES>
      labelSelectors: <SELECTORS>
-------
+
. After you populate the `trident-protect-snapshot-restore-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
-----
kubectl apply -f trident-protect-snapshot-restore-cr.yaml
-----


--
.Restore the snapshot using the CLI
--
. Restore the snapshot to a different namespace, replacing values in brackets with information from your environment.
+
* The `snapshot` argument uses a namespace and snapshot name in the format `<namespace>/<name>`. 
* The `namespace-mapping` argument uses colon-separated namespaces to map source namespaces to the correct destination namespaces in the format `source1:dest1,source2:dest2`.
+
For example:
+
[source,console]
-----
tridentctl protect create snapshotrestore <my_restore_name> --snapshot <namespace/snapshot_to_restore> --namespace-mapping <source_to_destination_namespace_mapping>
-----
--
====
// end tabbed block