---
sidebar: sidebar
permalink: trident-protect/trident-protect-migrate-apps.html
keywords: trident, protect, migrate, storage, restore, backup
summary: You can restore your backup or snapshot data to a different cluster or storage class
---
= Migrate applications using Trident protect
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can migrate your applications between clusters or to different storage classes by restoring backup data.

NOTE: When you migrate an application, all execution hooks configured for the application are migrated with the app. If a post-restore execution hook is present, it runs automatically as part of the restore operation.

== Backup and restore operations

To perform backup and restore operations for the following scenarios, you can automate specific backup and restore tasks.

=== Clone to same cluster

To clone an application to the same cluster, create a snapshot or backup and restore the data to the same cluster.

.Steps

. Do one of the following:
.. link:trident-protect-protect-apps.html#create-an-on-demand-snapshot[Create a snapshot].
.. link:trident-protect-protect-apps.html#create-an-on-demand-backup[Create a backup].

. On the same cluster, do one of the following, depending on if you created a snapshot or a backup:
.. link:trident-protect-restore-apps.html#restore-from-a-snapshot-to-a-different-namespace[Restore your data from the snapshot].
.. link:trident-protect-restore-apps.html#restore-from-a-backup-to-a-different-namespace[Restore your data from the backup].

=== Clone to different cluster

To clone an application to a different cluster (perform a cross-cluster clone), create a backup on the source cluster, and then restore the backup to a different cluster. Make sure that Trident protect is installed on the destination cluster.

NOTE: You can replicate an application between different clusters using link:trident-protect-use-snapmirror-replication.html[SnapMirror replication].

.Steps

. link:trident-protect-protect-apps.html#create-an-on-demand-backup[Create a backup].
. Ensure that the AppVault CR for the object storage bucket that contains the backup has been configured on the destination cluster.
. On the destination cluster, link:trident-protect-restore-apps.html#restore-from-a-backup-to-a-different-namespace[restore your data from the backup].

== Migrate applications from one storage class to another storage class

You can migrate applications from one storage class to a different storage class by restoring a backup to the destination storage class.

For example (excluding the secrets from the restore CR):

[source,yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: "${snapshotRestoreCRName}"
spec:
  appArchivePath: "${snapshotArchivePath}"
  appVaultRef: "${appVaultCRName}"
  namespaceMapping:
    - destination: "${destinationNamespace}"
      source: "${sourceNamespace}"
  storageClassMapping:
    - destination: "${destinationStorageClass}"
      source: "${sourceStorageClass}"
  resourceFilter:
    resourceMatchers:
      kind: Secret
      version: v1
    resourceSelectionCriteria: exclude
----

// begin tabbed block
[role="tabbed-block"]
====
.Restore the snapshot using a CR
--
.Steps
. Create the custom resource (CR) file and name it `trident-protect-snapshot-restore-cr.yaml`. 
. In the file you created, configure the following attributes:
+
* *metadata.name*: (_Required_) The name of this custom resource; choose a unique and sensible name for your environment.
* *spec.appArchivePath*: The path inside AppVault where the snapshot contents are stored. You can use the following command to find this path:
+
[source,console]
-----
kubectl get snapshots <my-snapshot-name> -n trident-protect -o jsonpath='{.status.appArchivePath}'
-----
+
* *spec.appVaultRef*: (_Required_) The name of the AppVault where the snapshot contents are stored.
* *spec.namespaceMapping*: The mapping of the source namespace of the restore operation to the destination namespace. Replace `my-source-namespace` and `my-destination-namespace` with information from your environment.
+
[source,yaml]
-------
---
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: my-cr-name
  namespace: trident-protect
spec:
  appArchivePath: my-snapshot-path
  appVaultRef: appvault-name
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
-------
+
. Optionally, if you need to select only certain resources of the application to restore, add filtering that includes or excludes resources marked with particular labels:
+
* *resourceFilter.resourceSelectionCriteria*: (Required for filtering) Use `include or exclude` to include or exclude a resource defined in resourceMatchers. Add the following resourceMatchers parameters to define the resources to be included or excluded:
** *resourceFilter.resourceMatchers*: An array of resourceMatcher objects. If you define multiple elements in this array, they match as an OR operation, and the fields inside each element (group, kind, version) match as an AND operation.
*** *resourceMatchers[].group*: (_Optional_) Group of the resource to be filtered.
*** *resourceMatchers[].kind*: (_Optional_) Kind of the resource to be filtered.
*** *resourceMatchers[].version*: (_Optional_) Version of the resource to be filtered.
*** *resourceMatchers[].names*: (_Optional_) Names in the Kubernetes metadata.name field of the resource to be filtered.
*** *resourceMatchers[].namespaces*: (_Optional_) Namespaces in the Kubernetes metadata.name field of the resource to be filtered.
*** *resourceMatchers[].labelSelectors*: (_Optional_) Label selector string in the Kubernetes metadata.name field of the resource as defined in the https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Kubernetes documentation^]. For example: `"trident.netapp.io/os=linux"`.
+
For example:
+
[source,yaml]
-------
spec:    
  resourceFilter: 
    resourceSelectionCriteria: "include"
    resourceMatchers:
      - group: my-resource-group-1
        kind: my-resource-kind-1
        version: my-resource-version-1
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
      - group: my-resource-group-2
        kind: my-resource-kind-2
        version: my-resource-version-2
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
-------
+
. After you populate the `trident-protect-snapshot-restore-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
-----
kubectl apply -f trident-protect-snapshot-restore-cr.yaml
-----


--
.Restore the snapshot using the CLI
--
.Steps
. Restore the snapshot to a different namespace, replacing values in brackets with information from your environment.
+
* The `snapshot` argument uses a namespace and snapshot name in the format `<namespace>/<name>`. 
* The `namespace-mapping` argument uses colon-separated namespaces to map source namespaces to the correct destination namespaces in the format `source1:dest1,source2:dest2`.
+
For example:
+
[source,console]
-----
tridentctl-protect create snapshotrestore <my_restore_name> --snapshot <namespace/snapshot_to_restore> --namespace-mapping <source_to_destination_namespace_mapping>
-----
--
====
// end tabbed block