---
sidebar: sidebar
permalink: trident-protect/trident-protect-upgrade.html
keywords: trident, protect, netapp, upgrade, new, version
summary: You can upgrade Trident Protect to the latest version to take advantage of new features or bug fixes. 
---
= Upgrade Trident Protect
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can upgrade Trident Protect to the latest version to take advantage of new features or bug fixes.

[NOTE]
====
* When you upgrade from version 24.10, snapshots running during the upgrade might fail. This failure does not prevent future snapshots, whether manual or scheduled, from being created. If a snapshot fails during the upgrade, you can manually create a new snapshot to ensure your application is protected.
+
To avoid potential failures, you can disable all snapshot schedules before the upgrade and re-enable them afterward. However, this results in missing any scheduled snapshots during the upgrade period.

* For private registry installations, ensure the required Helm chart and images for the target version are available in your private registry, and verify your custom Helm values are compatible with the new chart version. For more information, refer to link:trident-protect-installation.html[Install Trident Protect from a private registry].

====


== ##Step 1: Select a version##
Trident Protect versions follow a date-based `YY.MM` naming convention, where "YY" is the last two digits of the year and "MM" is the month. Dot releases follow a `YY.MM.X` convention, where "X" is the patch level. You will select the version to upgrade to based on the version you are upgrading from.

* You can perform a direct upgrade to any target release that is within a four-release window of your installed version. For example, you can directly upgrade from 24.10 (or any 24.10 dot release) to 25.10.
* If you are upgrading from a release outside of the four-release window, perform a multi-step upgrade. Use the upgrade instructions for the link:../earlier-versions.html[earlier version] you are upgrading from to upgrade to the most recent release that fits the four-release window. For example, if you are running 24.02 and want to upgrade to 25.10:

. First upgrade from 24.02 to 24.10.

. Then upgrade from 24.10 to 25.10.

== Step 2: Upgrade Trident Protect
To upgrade Trident Protect, perform the following steps.

.Steps
. Update the Trident Helm repository:
+
[source,console]
----
helm repo update
----
. Upgrade the Trident Protect CRDs:
+
NOTE: This step is required if you are upgrading from a version earlier than 25.06, as the CRDs are now included in the Trident Protect Helm chart.
+
.. Run this command to shift management of CRDs from `trident-protect-crds` to `trident-protect`:
+
[source,console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
+
.. Run this command to delete the Helm secret for the `trident-protect-crds` chart:
+  
NOTE: Do not uninstall the `trident-protect-crds` chart using Helm, as this could remove your CRDs and any related data.
+
[source,console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----
. Upgrade Trident Protect:
+
[source,console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2510.0 --namespace trident-protect
----
+
NOTE: You can configure the logging level during upgrade by adding `--set logLevel=debug` to the upgrade command. The default logging level is `warn`. Debug logging is recommended for troubleshooting as it helps NetApp support diagnose issues without requiring log level changes or problem reproduction.

