---
sidebar: sidebar
permalink: trident-protect/trident-protect-restore-apps.html
keywords: trident, protect, restore, data, backup
summary: You can use Trident protect to restore your application from a snapshot or backup. Restoring from an existing snapshot will be faster when restoring the application to the same cluster.
---
= Restore applications using Trident protect
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use Trident protect to restore your application from a snapshot or backup. Restoring from an existing snapshot will be faster when restoring the application to the same cluster.

NOTE: When you restore an application, all execution hooks configured for the application are restored with the app. If a post-restore execution hook is present, it runs automatically as part of the restore operation.

include::../_include/namespace-anno-labels.adoc[]

== Restore from a backup to a different namespace

When you restore a backup to a different namespace using a BackupRestore CR, Trident protect restores the application in a new namespace and creates an application CR for the restored application. To protect the restored application, create on-demand backups or snapshots, or establish a protection schedule.

NOTE: Restoring a backup to a different namespace with existing resources will not alter any resources that share names with those in the backup. To restore all resources in the backup, either delete and re-create the target namespace, or restore the backup to a new namespace.

include::../_include/restore-include-sessiontoken-note.adoc[]

NOTE: When you restore backups using Kopia as the data mover, you can optionally specify annotations in the CR or using the CLI to control the behavior of the emphemeral storage used by Kopia. Refer to the https://kopia.io/docs/getting-started/[Kopia documentation^] for more information about the options you can configure.

// begin tabbed block
[role="tabbed-block"]
====
.Use a CR
--
.Steps

. Create the custom resource (CR) file and name it `trident-protect-backup-restore-cr.yaml`. 
. In the file you created, configure the following attributes:
+
* *metadata.name*: (_Required_) The name of this custom resource; choose a unique and sensible name for your environment.
* *spec.appArchivePath*: The path inside AppVault where the backup contents are stored. You can use the following command to find this path:
+
[source,console]
-----
kubectl get backups <BACKUP_NAME> -n my-app-namespace -o jsonpath='{.status.appArchivePath}'
-----
* *spec.appVaultRef*: (_Required_) The name of the AppVault where the backup contents are stored.
* *spec.namespaceMapping*: The mapping of the source namespace of the restore operation to the destination namespace. Replace `my-source-namespace` and `my-destination-namespace` with information from your environment.
* *spec.storageClassMapping*: The mapping of the source storage class of the restore operation to the destination storage class. Replace `destinationStorageClass` and `sourceStorageClass` with information from your environment.
+
[source,yaml]
-------
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: my-cr-name
  namespace: my-destination-namespace
  annotations: # Optional annotations for Kopia data mover
    protect.trident.netapp.io/kopia-content-cache-size-limit-mb: 1000
    protect.trident.netapp.io/kopia-content-cache-size-mb: 500
    protect.trident.netapp.io/kopia-content-min-sweep-age-minutes: 1
spec:
  appArchivePath: my-backup-path
  appVaultRef: appvault-name
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
-------
+
. (_Optional_) If you need to select only certain resources of the application to restore, add filtering that includes or excludes resources marked with particular labels:
+
* *resourceFilter.resourceSelectionCriteria*: (Required for filtering) Use `Include` or `Exclude` to include or exclude a resource defined in resourceMatchers. Add the following resourceMatchers parameters to define the resources to be included or excluded:
** *resourceFilter.resourceMatchers*: An array of resourceMatcher objects. If you define multiple elements in this array, they match as an OR operation, and the fields inside each element (group, kind, version) match as an AND operation.
*** *resourceMatchers[].group*: (_Optional_) Group of the resource to be filtered.
*** *resourceMatchers[].kind*: (_Optional_) Kind of the resource to be filtered.
*** *resourceMatchers[].version*: (_Optional_) Version of the resource to be filtered.
*** *resourceMatchers[].names*: (_Optional_) Names in the Kubernetes metadata.name field of the resource to be filtered.
*** *resourceMatchers[].namespaces*: (_Optional_) Namespaces in the Kubernetes metadata.name field of the resource to be filtered.
*** *resourceMatchers[].labelSelectors*: (_Optional_) Label selector string in the Kubernetes metadata.name field of the resource as defined in the https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Kubernetes documentation^]. For example: `"trident.netapp.io/os=linux"`.
+
For example:
+
[source,yaml]
-------
spec:    
  resourceFilter: 
    resourceSelectionCriteria: "Include"
    resourceMatchers:
      - group: my-resource-group-1
        kind: my-resource-kind-1
        version: my-resource-version-1
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
      - group: my-resource-group-2
        kind: my-resource-kind-2
        version: my-resource-version-2
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
-------
+ 
. After you populate the `trident-protect-backup-restore-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
-----
kubectl apply -f trident-protect-backup-restore-cr.yaml
-----

--
.Use the CLI
--
.Steps
. Restore the backup to a different namespace, replacing values in brackets with information from your environment. The `namespace-mapping` argument uses colon-separated namespaces to map source namespaces to the correct destination namespaces in the format `source1:dest1,source2:dest2`. For example:
+
[source,console]
-----
tridentctl-protect create backuprestore <my_restore_name> \
--backup <backup_namespace>/<backup_to_restore> \
--namespace-mapping <source_to_destination_namespace_mapping> \
-n <application_namespace>
-----
--
====
// end tabbed block

== Restore from a backup to the original namespace
You can restore a backup to the original namespace at any time.

include::../_include/restore-include-sessiontoken-note.adoc[]

NOTE: When you restore backups using Kopia as the data mover, you can optionally specify annotations in the CR or using the CLI to control the behavior of the emphemeral storage used by Kopia. Refer to the https://kopia.io/docs/getting-started/[Kopia documentation^] for more information about the options you can configure.

// begin tabbed block
[role="tabbed-block"]
====
.Use a CR
--
.Steps
. Create the custom resource (CR) file and name it `trident-protect-backup-ipr-cr.yaml`. 
. In the file you created, configure the following attributes:
+
* *metadata.name*: (_Required_) The name of this custom resource; choose a unique and sensible name for your environment.
* *spec.appArchivePath*: The path inside AppVault where the backup contents are stored. You can use the following command to find this path:
+
[source,console]
-----
kubectl get backups <BACKUP_NAME> -n my-app-namespace -o jsonpath='{.status.appArchivePath}'
-----
* *spec.appVaultRef*: (_Required_) The name of the AppVault where the backup contents are stored.
+
For example:
+
[source,yaml]
-------
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupInplaceRestore
metadata:
  name: my-cr-name
  namespace: my-app-namespace
  annotations: # Optional annotations for Kopia data mover
    protect.trident.netapp.io/kopia-content-cache-size-limit-mb: 1000
    protect.trident.netapp.io/kopia-content-cache-size-mb: 500
    protect.trident.netapp.io/kopia-content-min-sweep-age-minutes: 1  
spec:
  appArchivePath: my-backup-path
  appVaultRef: appvault-name
-------
+
. (_Optional_) If you need to select only certain resources of the application to restore, add filtering that includes or excludes resources marked with particular labels:
+
* *resourceFilter.resourceSelectionCriteria*: (Required for filtering) Use `Include` or `Exclude` to include or exclude a resource defined in resourceMatchers. Add the following resourceMatchers parameters to define the resources to be included or excluded:
** *resourceFilter.resourceMatchers*: An array of resourceMatcher objects. If you define multiple elements in this array, they match as an OR operation, and the fields inside each element (group, kind, version) match as an AND operation.
*** *resourceMatchers[].group*: (_Optional_) Group of the resource to be filtered.
*** *resourceMatchers[].kind*: (_Optional_) Kind of the resource to be filtered.
*** *resourceMatchers[].version*: (_Optional_) Version of the resource to be filtered.
*** *resourceMatchers[].names*: (_Optional_) Names in the Kubernetes metadata.name field of the resource to be filtered.
*** *resourceMatchers[].namespaces*: (_Optional_) Namespaces in the Kubernetes metadata.name field of the resource to be filtered.
*** *resourceMatchers[].labelSelectors*: (_Optional_) Label selector string in the Kubernetes metadata.name field of the resource as defined in the https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Kubernetes documentation^]. For example: `"trident.netapp.io/os=linux"`.
+
For example:
+
[source,yaml]
-------
spec:    
  resourceFilter: 
    resourceSelectionCriteria: "Include"
    resourceMatchers:
      - group: my-resource-group-1
        kind: my-resource-kind-1
        version: my-resource-version-1
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
      - group: my-resource-group-2
        kind: my-resource-kind-2
        version: my-resource-version-2
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
-------
+
. After you populate the `trident-protect-backup-ipr-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
------
kubectl apply -f trident-protect-backup-ipr-cr.yaml
------
--
.Use the CLI
--
.Steps
. Restore the backup to the original namespace, replacing values in brackets with information from your environment. The `backup` argument uses a namespace and backup name in the format `<namespace>/<name>`. For example:
+
[source,console]
-----
tridentctl-protect create backupinplacerestore <my_restore_name> \
--backup <namespace/backup_to_restore> \
-n <application_namespace>
-----
--
====
// end tabbed block

== Restore from a backup to a different cluster

You can restore a backup to a different cluster if there is an issue with the original cluster.

NOTE: When you restore backups using Kopia as the data mover, you can optionally specify annotations in the CR or using the CLI to control the behavior of the emphemeral storage used by Kopia. Refer to the https://kopia.io/docs/getting-started/[Kopia documentation^] for more information about the options you can configure.

.Before you begin

Ensure the following prerequisites are met:

* The destination cluster has Trident protect installed.
* The destination cluster has access to the bucket path of the same AppVault as the source cluster, where the backup is stored.
* Ensure that the AWS session token expiration is sufficient for any long-running restore operations. If the token expires during the restore operation, the operation can fail.
** Refer to the https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html[AWS API documentation^] for more information about checking the current session token expiration.
** Refer to the https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html[AWS documentation^] for more information about credentials with AWS resources.

.Steps
. Check the availability of the AppVault CR on the destination cluster using Trident protect CLI plugin:
+
[source,console]
----
tridentctl-protect get appvault --context <destination_cluster_name>
----
+
NOTE: Ensure that the namespace intended for the application restore exists on the destination cluster.
. View the backup contents of the available AppVault from the destination cluster:
+
[source,console]
----
tridentctl-protect get appvaultcontent <appvault_name> \
--show-resources backup \
--show-paths \
--context <destination_cluster_name>
----
+
Running this command displays the available backups in the AppVault, including their originating clusters, corresponding application names, timestamps, and archive paths.
+
*Example output:*
+
----
+-------------+-----------+--------+-----------------+--------------------------+-------------+
|   CLUSTER   |    APP    |  TYPE  |      NAME       |        TIMESTAMP         |    PATH     |
+-------------+-----------+--------+-----------------+--------------------------+-------------+
| production1 | wordpress | backup | wordpress-bkup-1| 2024-10-30 08:37:40 (UTC)| backuppath1 |
| production1 | wordpress | backup | wordpress-bkup-2| 2024-10-30 08:37:40 (UTC)| backuppath2 |
+-------------+-----------+--------+-----------------+--------------------------+-------------+
----
. Restore the application to the destination cluster using the AppVault name and archive path:

// begin tabbed block
[role="tabbed-block"]
====
.Use a CR
--
[start=4]
. Create the custom resource (CR) file and name it `trident-protect-backup-restore-cr.yaml`.
. In the file you created, configure the following attributes:
+
* *metadata.name*: (_Required_) The name of this custom resource; choose a unique and sensible name for your environment.
* *spec.appVaultRef*: (_Required_) The name of the AppVault where the backup contents are stored.
* *spec.appArchivePath*: The path inside AppVault where the backup contents are stored. You can use the following command to find this path:
+
[source,console]
----
kubectl get backups <BACKUP_NAME> -n my-app-namespace -o jsonpath='{.status.appArchivePath}'
----
+
NOTE: If BackupRestore CR is not available, you can use the command mentioned in step 2 to view the backup contents.

+
* *spec.namespaceMapping*: The mapping of the source namespace of the restore operation to the destination namespace. Replace `my-source-namespace` and `my-destination-namespace` with information from your environment.
+
For example:
+
[source,yaml]
----
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: my-cr-name
  namespace: my-destination-namespace
  annotations: # Optional annotations for Kopia data mover
    protect.trident.netapp.io/kopia-content-cache-size-limit-mb: 1000
    protect.trident.netapp.io/kopia-content-cache-size-mb: 500
    protect.trident.netapp.io/kopia-content-min-sweep-age-minutes: 1
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
----
. After you populate the `trident-protect-backup-restore-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
----
kubectl apply -f trident-protect-backup-restore-cr.yaml
----

--
.Use the CLI
--
[start=4]
. Use the following command to restore the application, replacing values in brackets with information from your environment. The namespace-mapping argument uses colon-separated namespaces to map source namespaces to the correct destination namespaces in the format source1:dest1,source2:dest2. For example:
+
[source,console]
----
tridentctl-protect create backuprestore <restore_name> \
--namespace-mapping <source_to_destination_namespace_mapping> \
--appvault <appvault_name> \
--path <backup_path> \
--context <destination_cluster_name> \
-n <application_namespace>
----
--
====
// end tabbed block

== Restore from a snapshot to a different namespace

You can restore data from a snapshot using a custom resource (CR) file either to a different namespace or the original source namespace. When you restore a snapshot to a different namespace using a SnapshotRestore CR, Trident protect restores the application in a new namespace and creates an application CR for the restored application. To protect the restored application, create on-demand backups or snapshots, or establish a protection schedule.

include::../_include/restore-include-sessiontoken-note.adoc[]

// begin tabbed block
[role="tabbed-block"]
====
.Use a CR
--
.Steps
. Create the custom resource (CR) file and name it `trident-protect-snapshot-restore-cr.yaml`. 
. In the file you created, configure the following attributes:
+
* *metadata.name*: (_Required_) The name of this custom resource; choose a unique and sensible name for your environment.
* *spec.appVaultRef*: (_Required_) The name of the AppVault where the snapshot contents are stored.
* *spec.appArchivePath*: The path inside AppVault where the snapshot contents are stored. You can use the following command to find this path:
+
[source,console]
-----
kubectl get snapshots <SNAPHOT_NAME> -n my-app-namespace -o jsonpath='{.status.appArchivePath}'
-----
+
* *spec.namespaceMapping*: The mapping of the source namespace of the restore operation to the destination namespace. Replace `my-source-namespace` and `my-destination-namespace` with information from your environment.
* *spec.storageClassMapping*: The mapping of the source storage class of the restore operation to the destination storage class. Replace `destinationStorageClass` and `sourceStorageClass` with information from your environment.
+
[source,yaml]
-------
---
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: my-cr-name
  namespace: my-app-namespace
spec:
  appVaultRef: appvault-name
  appArchivePath: my-snapshot-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
-------
+
. (_Optional_) If you need to select only certain resources of the application to restore, add filtering that includes or excludes resources marked with particular labels:
+
* *resourceFilter.resourceSelectionCriteria*: (Required for filtering) Use `Include` or `Exclude` to include or exclude a resource defined in resourceMatchers. Add the following resourceMatchers parameters to define the resources to be included or excluded:
** *resourceFilter.resourceMatchers*: An array of resourceMatcher objects. If you define multiple elements in this array, they match as an OR operation, and the fields inside each element (group, kind, version) match as an AND operation.
*** *resourceMatchers[].group*: (_Optional_) Group of the resource to be filtered.
*** *resourceMatchers[].kind*: (_Optional_) Kind of the resource to be filtered.
*** *resourceMatchers[].version*: (_Optional_) Version of the resource to be filtered.
*** *resourceMatchers[].names*: (_Optional_) Names in the Kubernetes metadata.name field of the resource to be filtered.
*** *resourceMatchers[].namespaces*: (_Optional_) Namespaces in the Kubernetes metadata.name field of the resource to be filtered.
*** *resourceMatchers[].labelSelectors*: (_Optional_) Label selector string in the Kubernetes metadata.name field of the resource as defined in the https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Kubernetes documentation^]. For example: `"trident.netapp.io/os=linux"`.
+
For example:
+
[source,yaml]
-------
spec:    
  resourceFilter: 
    resourceSelectionCriteria: "Include"
    resourceMatchers:
      - group: my-resource-group-1
        kind: my-resource-kind-1
        version: my-resource-version-1
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
      - group: my-resource-group-2
        kind: my-resource-kind-2
        version: my-resource-version-2
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
-------
+
. After you populate the `trident-protect-snapshot-restore-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
-----
kubectl apply -f trident-protect-snapshot-restore-cr.yaml
-----

--
.Use the CLI
--
.Steps
. Restore the snapshot to a different namespace, replacing values in brackets with information from your environment.
+
* The `snapshot` argument uses a namespace and snapshot name in the format `<namespace>/<name>`. 
* The `namespace-mapping` argument uses colon-separated namespaces to map source namespaces to the correct destination namespaces in the format `source1:dest1,source2:dest2`.
+
For example:
+
[source,console]
-----
tridentctl-protect create snapshotrestore <my_restore_name> \
--snapshot <namespace/snapshot_to_restore> \
--namespace-mapping <source_to_destination_namespace_mapping> \
-n <application_namespace>
-----
--
====
// end tabbed block


== Restore from a snapshot to the original namespace
You can restore a snapshot to the original namespace at any time.

include::../_include/restore-include-sessiontoken-note.adoc[]

// begin tabbed block
[role="tabbed-block"]
====
.Use a CR
--
.Steps
. Create the custom resource (CR) file and name it `trident-protect-snapshot-ipr-cr.yaml`. 
. In the file you created, configure the following attributes:

* *metadata.name*: (_Required_) The name of this custom resource; choose a unique and sensible name for your environment.
* *spec.appVaultRef*: (_Required_) The name of the AppVault where the snapshot contents are stored.
* *spec.appArchivePath*: The path inside AppVault where the snapshot contents are stored. You can use the following command to find this path:
+
[source,console]
------
kubectl get snapshots <SNAPSHOT_NAME> -n my-app-namespace -o jsonpath='{.status.appArchivePath}'
------
+
[source,yaml]
-------
---
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotInplaceRestore
metadata:
  name: my-cr-name
  namespace: my-app-namespace
spec:
  appVaultRef: appvault-name
    appArchivePath: my-snapshot-path
-------
+
. (_Optional_) If you need to select only certain resources of the application to restore, add filtering that includes or excludes resources marked with particular labels:
+
* *resourceFilter.resourceSelectionCriteria*: (Required for filtering) Use `Include` or `Exclude` to include or exclude a resource defined in resourceMatchers. Add the following resourceMatchers parameters to define the resources to be included or excluded:
** *resourceFilter.resourceMatchers*: An array of resourceMatcher objects. If you define multiple elements in this array, they match as an OR operation, and the fields inside each element (group, kind, version) match as an AND operation.
*** *resourceMatchers[].group*: (_Optional_) Group of the resource to be filtered.
*** *resourceMatchers[].kind*: (_Optional_) Kind of the resource to be filtered.
*** *resourceMatchers[].version*: (_Optional_) Version of the resource to be filtered.
*** *resourceMatchers[].names*: (_Optional_) Names in the Kubernetes metadata.name field of the resource to be filtered.
*** *resourceMatchers[].namespaces*: (_Optional_) Namespaces in the Kubernetes metadata.name field of the resource to be filtered.
*** *resourceMatchers[].labelSelectors*: (_Optional_) Label selector string in the Kubernetes metadata.name field of the resource as defined in the https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Kubernetes documentation^]. For example: `"trident.netapp.io/os=linux"`.
+
For example:
+
[source,yaml]
-------
spec:    
  resourceFilter: 
    resourceSelectionCriteria: "Include"
    resourceMatchers:
      - group: my-resource-group-1
        kind: my-resource-kind-1
        version: my-resource-version-1
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
      - group: my-resource-group-2
        kind: my-resource-kind-2
        version: my-resource-version-2
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
-------
+
. After you populate the `trident-protect-snapshot-ipr-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
------
kubectl apply -f trident-protect-snapshot-ipr-cr.yaml
------
--
.Use the CLI
--
.Steps
. Restore the snapshot to the original namespace, replacing values in brackets with information from your environment. For example:
+
[source,console]
-----
tridentctl-protect create snapshotinplacerestore <my_restore_name> \
--snapshot <snapshot_to_restore> \
-n <application_namespace>
-----
--
====
// end tabbed block

== Check the status of a restore operation
You can use the command line to check the status of a restore operation that is in progress, has completed, or has failed.

.Steps

. Use the following command to retrieve status of the restore operation, replacing values in brackes with information from your environment:
+
[source,console]
------
kubectl get backuprestore -n <namespace_name> <my_restore_cr_name> -o jsonpath='{.status}'
------