---
sidebar: sidebar
permalink: trident-protect/trident-protect-restore-settings.html
keywords: trident, protect, restore, data, backup
summary: You can customize Trident protect restore operations using annotations, namespace settings, and storage options. 
---
= Customize Trident protect restore annotations and options
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can customize Trident protect restore operations using annotations, namespace settings, and storage options. 

include::../_include/namespace-anno-labels.adoc[]

== Supported annotations
This section lists the supported annotations for configuring various behaviors in the system. If an annotation is not explicitly set by the user, the system will use the default value.

[cols="1,1,3,1", options="header"]
|===
| Annotation | Type | Description | Default value

| protect.trident.netapp.io/data-mover-timeout-sec
| string
| The maximum time (in seconds) allowed for data mover operation to be stalled.
| 300
| protect.trident.netapp.io/kopia-content-cache-size-limit-mb
| integer
| The maximum size limit (in megabytes) for the Kopia content cache.
| 1000
|===

== ##Supported options##
This section describes additional configuration options available for restore operations.

=== Storage class mapping
The `spec.storageClassMapping` attribute defines a mapping from a storage class present in the source application to a new storage class on the target cluster. This is useful when migrating applications between clusters with different storage classes or when changing the storage backend for BackupRestore operations.

*Example:*
[source,yaml]
----
storageClassMapping:
  - destination: "destinationStorageClass1"
    source: "sourceStorageClass1"
  - destination: "destinationStorageClass2"
    source: "sourceStorageClass2"
----
