---
sidebar: sidebar
permalink: trident-protect/trident-protect-cli.html
keywords: trident, protect, command line utility, cli, netapp, custom, resources
summary: You can use the protectctl command to create and interact with Trident protect custom resources.
---
= Install the Trident protect CLI plugin
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use the Trident protect command line plugin, which is an extension of the Trident `tridentctl` utility, to create and interact with Trident protect custom resources (CRs).

== Install the Trident protect CLI plugin
Before using the command line utility, you need to install it on the machine you use to access your cluster. Follow these steps, depending on if your machine uses an x64 or ARM CPU.

[role="tabbed-block"]
====
.Download plugin for Linux AMD64 CPUs
--
.Steps
. Download the Trident protect CLI plugin:
+
[source,console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-protect-linux-amd64
----
--
.Download plugin for Linux ARM64 CPUs
--
.Steps
. Download the Trident protect CLI plugin:
+
[source,console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-protect-linux-arm64
----
--
.Download plugin for Mac AMD64 CPUs
--
.Steps
. Download the Trident protect CLI plugin:
+
[source,console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-protect-macos-amd64
----
--
.Download plugin for Mac ARM64 CPUs
--
.Steps
. Download the Trident protect CLI plugin:
+
[source,console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-protect-macos-arm64
----
--
====

[start=2]
. Enable execute permissions for the plugin binary:
+
[source,console]
----
chmod +x tridentctl-protect
----
. Copy the plugin binary to a location that is defined in your PATH variable. For example, `/usr/bin` or `/usr/local/bin` (you might need elevated privileges):
+
[source,console]
----
cp ./tridentctl-protect /usr/local/bin/
----
. Optionally, you can copy the plugin binary to a location in your home directory. In this case, it is recommended to ensure the location is part of your PATH variable:
+
[source,console]
----
cp ./tridentctl-protect ~/bin/
----

NOTE: Copying the plugin to a location in your PATH variable enables you to use the plugin by typing `tridentctl-protect` or `tridentctl protect` from any location.

== View Trident CLI plugin help
You can use the built-in plugin help features to get detailed help on the capabilities of the plugin:

.Steps 
. Use the help function to view usage guidance:
+
[source,console]
----
tridentctl-protect help
----

== Enable command auto-completion
After you have installed the Trident protect CLI plugin, you can enable auto-completion for certain commands. 

// For more information, use the `tridentctl protect completion --help` command.


[role="tabbed-block"]
====
.Enable auto-completion for the Bash shell
--
.Steps
. Download the completion script:
+
[source,console]
----
curl -L -O https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-completion.bash
----
. Make a new directory in your home directory to contain the script:
+
[source,console]
----
mkdir -p ~/.bash/completions
----
. Move the downloaded script to the `~/.bash/completions` directory:
+
[source,console]
----
mv tridentctl-completion.bash ~/.bash/completions/
----
. Add the following line to the `~/.bashrc` file in your home directory:
+
[source,console]
----
source ~/.bash/completions/tridentctl-completion.bash
----

--
.Enable auto-completion for the Z shell
--
.Steps
. Download the completion script:
+
[source,console]
----
curl -L -O https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-completion.zsh
----
. Make a new directory in your home directory to contain the script:
+
[source,console]
----
mkdir -p ~/.zsh/completions
----
. Move the downloaded script to the `~/.zsh/completions` directory:
+
[source,console]
----
mv tridentctl-completion.zsh ~/.zsh/completions/
----
. Add the following line to the `~/.zprofile` file in your home directory:
+
[source,console]
----
source ~/.zsh/completions/tridentctl-completion.zsh
----
--
====

.Result
Upon your next shell login, you can use command auto-completion with the tridentctl-protect plugin.

