---
sidebar: sidebar
permalink: trident-protect/trident-protect-requirements.html
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration
summary: Get started by verifying the readiness of your operational environment, application clusters, applications, and licenses. Ensure that your environment meets these requirements to deploy and operate Trident protect.
---
= Trident protect requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Get started by verifying the readiness of your operational environment, application clusters, applications, and licenses. Ensure that your environment meets these requirements to deploy and operate Trident protect.

== Trident protect Kubernetes compatibility

Trident protect is compatible with a wide range of fully managed and self-managed Kubernetes offerings, including:

* Google Kubernetes Engine (GKE)
* Amazon Elastic Kubernetes Service (EKS)
* Microsoft Azure Kubernetes Service (AKS)
* Red Hat OpenShift
* Rancher
* VMware Tanzu Portfolio
* Upstream Kubernetes

== Trident protect storage backend compatibility
Ensure that your storage backend meets the following requirements:

* Ensure that NetApp storage connected to the cluster is using Astra Trident 24.02 or newer (Trident 24.10 is recommended). 
** If Astra Trident is older than version 24.06.1 and you plan to use NetApp SnapMirror disaster recovery functionality, you need to manually enable Astra Control Provisioner.

* Ensure that you have the latest Astra Control Provisioner (installed and enabled by default as of Astra Trident 24.06.1).
* Ensure that you have a NetApp ONTAP storage backend.
* Ensure that you have configured an object storage bucket for storing backups.
* Create any application namespaces that you plan to use for applications or application data management operations. Trident protect does not create these namespaces for you; if you specify a nonexistent namespace in a custom resource, the operation will fail.

== Requirements for nas-economy volumes
Trident protect supports backup and restore operations to nas-economy volumes. Snapshots, clones, and SnapMirror replication to nas-economy volumes are not currently supported. You need to enable a snapshot directory for each nas-economy volume you plan to use with Trident protect.

[NOTE]
====
Some applications are not compatible with volumes that use a snapshot directory. For these applications you need to hide the snapshot directory by running the following command on the ONTAP storage system:
[source,console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====

You can enable the snapshot directory by running the following command for each nas-economy volume:
[source,console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --at-pool=true -n trident-protect-system
----

NOTE: You can enable snapshot directories by default for new volumes by setting the Trident storage configuration option `config.ontap_config.default.snapshotDir` to `true`. Existing volumes are not affected.

== Requirements for SnapMirror replication
NetApp SnapMirror is available for use with Trident protect for the following ONTAP solutions:

* NetApp ASA
* NetApp AFF
* NetApp FAS
* NetApp ONTAP Select
* NetApp Cloud Volumes ONTAP
* Amazon FSx for NetApp ONTAP

=== ONTAP cluster requirements for SnapMirror replication
Ensure your ONTAP cluster meets the following requirements if you plan to use SnapMirror replication:

* *Astra Control Provisioner or Trident*: Astra Control Provisioner or Trident must exist on both the source and destination Kubernetes clusters that utilize ONTAP as a backend. Trident protect supports replication with NetApp SnapMirror technology using storage classes backed by the following drivers:
** `ontap-nas`
** `ontap-san`
* *Licenses*: ONTAP SnapMirror asynchronous licenses using the Data Protection bundle must be enabled on both the source and destination ONTAP clusters. Refer to https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html[SnapMirror licensing overview in ONTAP^] for more information.

=== Peering considerations for SnapMirror replication
Ensure your environment meets the following requirements if you plan to use storage backend peering:

* *Cluster and SVM*: The ONTAP storage backends must be peered. Refer to https://docs.netapp.com/us-en/ontap/peering/index.html[Cluster and SVM peering overview^] for more information. 
+
[NOTE] 
Ensure that the SVM names used in the replication relationship between two ONTAP clusters are unique.
+
* *Astra Control Provisioner or Trident and SVM*: The peered remote SVMs must be available to Astra Control Provisioner or Trident on the destination cluster.
* *Managed backends*: You need to add and manage ONTAP storage backends in Trident protect to create a replication relationship.
* *NVMe over TCP*: Trident protect does not support NetApp SnapMirror replication for storage backends that are using the NVMe over TCP protocol.

=== Trident / ONTAP configuration for SnapMirror replication
Trident protect requires that you configure at least one storage backend that supports replication for both the source and destination clusters. If the source and destination clusters are the same, the destination application should use a different storage backend than the source application for the best resiliency.




