---
sidebar: sidebar
permalink: trident-protect/trident-protect-restore-apps.html
keywords: trident, protect, restore, data, backup
summary: You can use Trident protect to restore your application from a snapshot or backup. Restoring from an existing snapshot will be faster when restoring the application to the same cluster.
---
= Restore applications
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use Trident protect to restore your application from a snapshot or backup. Restoring from an existing snapshot will be faster when restoring the application to the same cluster.

== Restore from a backup to a different namespace

When you restore a backup to a different namespace using a BackupRestore CR, Trident protect restores the application in a new namespace, but the restored application is not automatically protected by Trident protect. To protect the restored application, you need to create an Application CR for the restored application so that it will be protected by Trident protect.

.Steps

. Create the custom resource (CR) file and name it `trident-protect-backup-restore-cr.yaml`. Update the values in brackets <> to match your Astra environment and cluster configuration:
+
* <CR_NAME>: The name of this CR operation; choose a sensible name for your environment.

* <APPVAULT_NAME>: The name of the AppVault where the backup contents are stored.

* <BACKUP_PATH>: The path inside AppVault where the backup contents are stored. You can use the following command to find this path:
+
[source,console]
-----
kubectl get backups <BACKUP_NAME> -n trident-protect -o jsonpath='{.status.appArchivePath}'
-----
+
* <SOURCE_NAMESPACE>: The source namespace of the restore operation.
+
* <DESTINATION_NAMESPACE>: The destination namespace of the restore operation.
+
[source,yaml]
-------
apiVersion: protect.trident.netapp.io/v1o	
kind: BackupRestore
metadata:
  name: <CR_NAME>
  namespace: trident-protect
spec:
  appVaultRef: <APPVAULT_NAME>
  appArchivePath: <BACKUP_PATH>
  namespaceMapping: [{"source": "<SOURCE_NAMESPACE>", "destination": "<DESTINATION_NAMESPACE>"}]
-------
+
. (_Optional_) If you need to select only certain resources of the application to restore, add filtering that includes or excludes resources marked with particular labels:
*  "<INCLUDE-EXCLUDE>": (_Required for filtering_) Use `include or exclude` to include or exclude a resource defined in resourceMatchers. Add the following resourceMatchers parameters to define the resources to be included or excluded:
** <GROUP>: (_Optional_) Group of the resource to be filtered.
** <KIND>: (_Optional_) Kind of the resource to be filtered.
** <VERSION>: (_Optional_) Version of the resource to be filtered.
** <NAMES>: (_Optional_) Names in the Kubernetes metadata.name field of the resource to be filtered.
** <NAMESPACES>: (_Optional_) Namespaces in the Kubernetes metadata.name field of the resource to be filtered.
** <SELECTORS>: (_Optional_) Label selector string in the Kubernetes metadata.name field of the resource as defined in the https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Kubernetes documentation^]. Example: `"trident.netapp.io/os=linux"`.
+
For example:
+
[source,yaml]
-------
spec:    
  resourceFilter: 
    resourceSelectionCriteria: "<INCLUDE-EXCLUDE>"
      resourceMatchers:
        group: <GROUP>
        kind: <KIND>
        version: <VERSION>
        names: <NAMES>
        namespaces: <NAMESPACES>
        labelSelectors: <SELECTORS>
-------
+ 
. After you populate the `trident-protect-backup-restore-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
-----
kubectl apply -f trident-protect-backup-restore-cr.yaml
-----

== Restore from a backup to the original namespace

.Steps

. Create the custom resource (CR) file and name it `trident-protect-backup-ipr-cr.yaml`. Update the values in brackets <> to match your Trident protect environment and cluster configuration:
+
* <CR_NAME>: The name of this CR operation; choose a sensible name for your environment.
* <APPVAULT_NAME>: The name of the AppVault where the backup contents are stored.
* <BACKUP_PATH>: The path inside AppVault where the backup contents are stored. You can use the following command to find this path:
+
[source,console]
-----
kubectl get backups <BACKUP_NAME> -n trident-protect -o jsonpath='{.status.appArchivePath}'
-----
+
For example:
+
[source,yaml]
-------
apiVersion: protect.trident.netapp.io/v1
kind: BackupInplaceRestore
metadata:
  name: <CR_NAME>
  namespace: trident-protect
spec:
  appVaultRef: <APPVAULT_NAME>
  appArchivePath: <BACKUP_PATH>
-------
+
. (_Optional_) If you need to select only certain resources of the application to restore, add filtering that includes or excludes resources marked with particular labels:

* "<INCLUDE-EXCLUDE>": (_Required for filtering_) Use `include or exclude` to include or exclude a resource defined in resourceMatchers. Add the following resourceMatchers parameters to define the resources to be included or excluded:

** <GROUP>: (_Optional_) Group of the resource to be filtered.
** <KIND>: (_Optional_) Kind of the resource to be filtered.
** <VERSION>: (_Optional_) Version of the resource to be filtered.
** <NAMES>: (_Optional_) Names in the Kubernetes metadata.name field of the resource to be filtered.
** <NAMESPACES>: (_Optional_) Namespaces in the Kubernetes metadata.name field of the resource to be filtered. 
** <SELECTORS>: (_Optional_) Label selector string in the Kubernetes metadata.name field of the resource as defined in the https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Kubernetes documentation^]. Example: `"trident.netapp.io/os=linux"`.
+
For example:
+
[source,yaml]
-------
spec:    
  resourceFilter: 
    resourceSelectionCriteria: "<INCLUDE-EXCLUDE>"
      resourceMatchers:
        group: <GROUP>
        kind: <KIND>
        version: <VERSION>
        names: <NAMES>
        namespaces: <NAMESPACES>
        labelSelectors: <SELECTORS>
-------
+
. After you populate the `trident-protect-backup-ipr-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
------
kubectl apply -f trident-protect-backup-ipr-cr.yaml
------

== Restore from a snapshot to a different namespace

You can restore data from a snapshot using a custom resource (CR) file either to a different namespace or the original source namespace. When you restore a snapshot to a different namespace using a SnapshotRestore CR, Trident protect restores the application in a new namespace, but the restored application is not automatically protected by Trident protect. To protect the restored application, you need to create an Application CR for the restored application so that it will be protected by Trident protect.

.Steps

. Create the custom resource (CR) file and name it `trident-protect-snapshot-restore-cr.yaml`. Update the values in brackets <> to match your Trident protect environment and cluster configuration:
+
* <CR_NAME>: The name of this CR operation; choose a sensible name for your environment.
* <APPVAULT_NAME>: The name of the AppVault where the snapshot contents are stored.
* <SNAPSHOT_PATH>: The path inside AppVault where the snapshot contents are stored. You can use the following command to find this path:
+
[source,console]
-----
kubectl get snapshots <SNAPHOT_NAME> -n trident-protect -o jsonpath='{.status.appArchivePath}'
-----
+
* <SOURCE_NAMESPACE>: The source namespace of the restore operation.
* <DESTINATION_NAMESPACE>: The destination namespace of the restore operation.
+
[source,yaml]
-------
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: <CR_NAME>
  namespace: trident-protect
spec:
  appArchivePath: <SNAPSHOT_PATH>
  appVaultRef: <APPVAULT_NAME>
  namespaceMapping: [{"source": "<SOURCE_NAMESPACE>", "destination": "<DESTINATION_NAMESPACE>"}]
-------
+
. (_Optional_) If you need to select only certain resources of the application to restore, add filtering that includes or excludes resources marked with particular labels:
+
* "<INCLUDE-EXCLUDE>": (Required for filtering) Use `include or exclude` to include or exclude a resource defined in resourceMatchers. Add the following resourceMatchers parameters to define the resources to be included or excluded:
+
* <GROUP>: (_Optional_) Group of the resource to be filtered.
* <KIND>: (_Optional_) Kind of the resource to be filtered.
* <VERSION>: (_Optional_) Version of the resource to be filtered.
* <NAMES>: (_Optional_) Names in the Kubernetes metadata.name field of the resource to be filtered.
* <NAMESPACES>: (_Optional_) Namespaces in the Kubernetes metadata.name field of the resource to be filtered.
* <SELECTORS>: (_Optional_) Label selector string in the Kubernetes metadata.name field of the resource as defined in the https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Kubernetes documentation^]. Example: `"trident.netapp.io/os=linux"`. 
+
For example:
+
[source,yaml]
-------
spec:    
  resourceFilter: 
    resourceSelectionCriteria: "<INCLUDE-EXCLUDE>"
    resourceMatchers:
      group: <GROUP>
      kind: <KIND>
      version: <VERSION>
      names: <NAMES>
      namespaces: <NAMESPACES>
      labelSelectors: <SELECTORS>
-------
+
. After you populate the `trident-protect-snapshot-restore-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
-----
kubectl apply -f trident-protect-snapshot-restore-cr.yaml
-----

== Restore from a snapshot to the original namespace

.Steps

. Create the custom resource (CR) file and name it `trident-protect-snapshot-ipr-cr.yaml`. Update the values in brackets <> to match your Trident protect environment and cluster configuration:

* <CR_NAME>: The name of this CR operation; choose a sensible name for your environment.
* <APPVAULT_NAME>: The name of the AppVault where the snapshot contents are stored.
* <BACKUP_PATH>: The path inside AppVault where the snapshot contents are stored. You can use the following command to find this path:
+
[source,console]
------
kubectl get snapshot <SNAPSHOT_NAME> -n trident-protect -o jsonpath='{.status.appArchivePath}'
------
+
[source,yaml]
-------
apiVersion: protect.trident.netapp.io/v1
kind: SnapshotInplaceRestore
metadata:
  name: <CR_NAME>
  namespace: trident-protect
spec:
  appArchivePath: <BACKUP_PATH>
  appVaultRef: <APPVAULT_NAME>
-------
+
. (_Optional_) If you need to select only certain resources of the application to restore, add filtering that includes or excludes resources marked with particular labels:

* "<INCLUDE-EXCLUDE>": (_Required for filtering_) Use include or exclude to include or exclude a resource defined in resourceMatchers. Add the following resourceMatchers parameters to define the resources to be included or excluded:

* <GROUP>: (_Optional_) Group of the resource to be filtered.
* <KIND>: (_Optional_) Kind of the resource to be filtered.
* <VERSION>: (_Optional_) Version of the resource to be filtered.
* <NAMES>: (_Optional_) Names in the Kubernetes metadata.name field of the resource to be filtered.
* <NAMESPACES>: (_Optional_) Namespaces in the Kubernetes metadata.name field of the resource to be filtered. 
* <SELECTORS>: (_Optional_) Label selector string in the Kubernetes metadata.name field of the resource as defined in the https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Kubernetes documentation^]. Example: `"trident.netapp.io/os=linux"`.
+
For example:
+
[source,yaml]
-------
spec:    
  resourceFilter: 
    resourceSelectionCriteria: "<INCLUDE-EXCLUDE>"
    resourceMatchers:
      group: <GROUP>
      kind: <KIND>
      version: <VERSION>
      names: <NAMES>
      namespaces: <NAMESPACES>
labelSelectors: <SELECTORS>
-------
+
. After you populate the `trident-protect-snapshot-ipr-cr.yaml` file with the correct values, apply the CR:
+
[source,console]
------
kubectl apply -f trident-protect-snapshot-ipr-cr.yaml
------

== Check the status of a restore operation
You can use the command line to check the status of a restore operation that is in progress, has completed, or has failed.

.Steps

. Use the following command to retrieve status of the restore operation, replacing values in brackes with information from your environment:
+
[source,console]
------
kubectl get backuprestore -n <namespace_name> <my_restore_cr_name> -o jsonpath='{.status}'
------
