---
sidebar: sidebar
permalink: trident-protect/trident-protect-use-execution-hooks.html
keywords: trident, protect, execution hooks 
summary: You can create a custom execution hook for an app using Trident protect. You need to have Owner, Admin, or Member permissions to create execution hooks.
---
= Manage execution hooks
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
An execution hook is a custom action that you can configure to run in conjunction with a data protection operation of a managed app. For example, if you have a database app, you can use an execution hook to pause all database transactions before a snapshot, and resume transactions after the snapshot is complete. This ensures application-consistent snapshots.

== Types of execution hooks
Trident protect supports the following types of execution hooks, based on when they can be run:

* Pre-snapshot
* Post-snapshot
* Pre-backup
* Post-backup
* Post-restore
* Post-failover

== Execution hook filters
When you add or edit an execution hook for an application, you can add filters to the execution hook to manage which containers the hook will match. Filters are useful for applications that use the same container image on all containers, but might use each image for a different purpose (such as Elasticsearch). Filters allow you to create scenarios where execution hooks run on some but not necessarily all identical containers. If you create multiple filters for a single execution hook, they are combined with a logical AND operator. You can have up to 10 active filters per execution hook.

Each filter you add to an execution hook uses a regular expression to match containers in your cluster. When a hook matches a container, the hook will run its associated script on that container. Regular expressions for filters use the Regular Expression 2 (RE2) syntax, which does not support creating a filter that excludes containers from the list of matches. For information on the syntax that Trident protect supports for regular expressions in execution hook filters, see https://github.com/google/re2/wiki/Syntax[Regular Expression 2 (RE2) syntax support^].

NOTE: If you add a namespace filter to an execution hook that runs after a restore or clone operation and the restore or clone source and destination are in different namespaces, the namespace filter is only applied to the destination namespace.

== Execution hook examples
Visit the https://github.com/NetApp/Verda[NetApp Verda GitHub project] to download real execution hooks for popular apps such as Apache Cassandra and Elasticsearch. You can also see examples and get ideas for structuring your own custom execution hooks.

== Create an execution hook
You can create a custom execution hook for an app using Trident protect. You need to have Owner, Admin, or Member permissions to create execution hooks.

.Steps

. Create the custom resource (CR) file and name it `trident-protect-hook.yaml`.
+
. Configure the following attributes to match your Trident protect environment and cluster configuration:
+
* *metadata.name*: (_Required_) The name of this custom resource; choose a unique and sensible name for your environment.
* *spec.applicationRef*: (_Required_) The Kubernetes name of the application for which to run the execution hook.
* *spec.stage*: (_Required_) A string indicating which stage during the action that the execution hook should run. Possible values:
** Pre
** Post
* *spec.action*: (_Required_) A string indicating which action the execution hook will take, assuming any execution hook filters specified are matched. Possible values:
** Snapshot
** Backup
** Restore
** Failover
* *spec.enabled*: (_Optional_) Indicates whether this execution hook is enabled or disabled. If not specified, the default value is true.
* *spec.hookSource*: (_Required_) A string containing the base64-encoded hook script.
* *spec.timeout*: (_Optional_) A number defining how long in minutes that the execution hook is allowed to run. The minimum value is 1 minute, and the default value is 25 minutes if not specified.
* *spec.arguments*: (_Optional_) A YAML list of arguments that you can specify for the execution hook.
* *spec.matchingCriteria*: (_Optional_) An optional list of criteria key value pairs, each pair making up an execution hook filter. You can add up to 10 filters per execution hook.
* *spec.matchingCriteria.type*: (_Optional_) A string identifying the execution hook filter type. Possible values:
** ContainerImage
** ContainerName
** PodName
** PodLabel
** NamespaceName
* *spec.matchingCriteria.value*: (_Optional_) A string or regular expression identifying the execution hook filter value.
+
Example YAML:
+
[source,yaml]
-----
apiVersion: protect.trident.netapp.io/v1
kind: ExecHook
metadata: 
  name: example-hook-cr
  annotations: 
    astra.netapp.io/astra-control-hook-source-id: /account/test/hookSource/id
spec: 
  applicationRef: my-app-name
  stage: pre
  action: snapshot
  enabled: true
  hookSource: IyEmlhookNoCmsourcegZmg85lcCAxCexamplekGZQo=
  timeout: 10
  arguments: 
    - FirstExampleArg
    - SecondExampleArg
  matchingCriteria: 
    - type: containerName
      value: mysql
    - type: containerImage
      value: bitnami/mysql
    - type: podName
      value: mysql
    - type: namespaceName
      value: mysql-a
    - type: podLabel
      value: app.kubernetes.io/component=primary
    - type: podLabel
      value: helm.sh/chart=mysql-10.1.0
    - type: podLabel
      value: deployment-type=production
-----
+ 
. After you populate the CR file with the correct values, apply the CR:
+
[source,console]
----- 
kubectl apply -f trident-protect-hook.yaml
-----


