---
sidebar: sidebar
permalink: trident-reference/k8s-cluster-components.html
keywords: kubernetes, clusters, nodes, components, master, compute
summary: A Kubernetes cluster typically consists of two types of nodes, each responsible for different aspects of functionality.
---

= Kubernetes cluster components
:hardbreaks:
:icons: font
:imagesdir: ../media/

A Kubernetes cluster typically consists of two types of nodes, each responsible for different aspects of functionality:

* *Master nodes*: These nodes host the control plane aspects of the cluster and are responsible for the API endpoint, which the users interact with, and provide scheduling for pods across resources. Typically, these nodes are not used to schedule application workloads. Master nodes are critical to the operation of the cluster. If no masters are running, or the master nodes are unable to reach a quorum, the cluster is unable to schedule and execute applications.
+
NOTE: See https://kubernetes.io/docs/setup/cluster-large/#size-of-master-and-master-components[here] for best practices for large clusters.
* *Compute nodes*: These nodes are responsible for executing workloads for the cluster users. You can add and remove compute nodes from the cluster quickly and easily to accommodate the scale of the applications, which are being hosted. This makes it very easy to burst, and reclaim, resources based on real-time application workload.

The cluster has a number of Kubernetes intrinsic services, which are deployed in the cluster. Depending on the service type, each service is deployed on only one type of node (master or compute) or on a mixture of node types. Some of these services, such as `etcd` and DNS, are mandatory for the cluster to be functional, while other services are optional. All of these services are deployed as pods within Kubernetes.

* *`etcd`*: It is a distributed key-value datastore.  It is used heavily by Kubernetes to track the state and manage the resources associated with the cluster.
* *DNS*: Kubernetes maintains an internal DNS service to provide local resolution for the applications that have been deployed. This enables inter-pod communication to happen while referencing friendly names instead of internal IP addresses, which can change as the container instances are scheduled.
* *API Server*: Kubernetes deploys the API server to allow interaction between Kubernetes and the outside world. This is deployed on the master node(s).
* *Dashboard*: This is an optional component, which provides a graphical interface to the cluster.
* *Monitoring and logging*: These are optional components, which can aid with resource reporting.
