---
sidebar: sidebar
permalink: trident-reference/k8s-compute.html
keywords: kubernetes containers, pods, services, deployments, statefulsets
summary: Learn about the Kubernetes compute objects that are involved in the consumption of storage resources.
---

= Kubernetes compute concepts
:hardbreaks:
:icons: font
:imagesdir: ../media/

Learn about the Kubernetes compute objects that are involved in the consumption of storage resources.

Kubernetes, as a container orchestrator, dynamically assigns containerized workloads to cluster members according to resource requirements that you specify.

== Pods

A pod represents one or more containers, which are related to each other. It is the smallest (atomic) unit for Kubernetes. Containers which are members of the same pod are co-scheduled to the same node in the cluster. They typically share the same namespace, network, and storage resources. However, not every container in the pod can access the storage or be publicly accessible via the network.

=== Create and destroy pods

Kubernetes creates and destroys pods (workloads). It does not “move” them like live VM migration performed by hypervisors. When Kubernetes scales down or needs to redeploy a workload on a different host, the pod and the container(s) on the original host are stopped, destroyed, and the resources are unmounted. The standard mount and instantiate process is then followed wherever in the cluster the same workload is redeployed as a different pod with a different name, IP address, and so on. Stateful sets are an exception and can redeploy a pod with the same name.
When an application being deployed relies on persistent storage, that storage must be accessible from any Kubernetes node deploying the workload within the cluster. Without a shared storage system available for persistence, the data would be abandoned, and usually deleted, on the source system when the workload is re-deployed elsewhere in the cluster. To maintain a persistent pod that is always deployed on the same node with the same name and characteristics, a StatefulSet should be used.

== Services

A Kubernetes service adds an abstraction layer over pods. It typically acts as an internal load balancer for replicated pods. The service enables the scaling of pods while maintaining a consistent service IP address. There are several types of services. A service can be reachable only within the cluster if you specify the type as `ClusterIP`, or can be exposed to the outside world if you specify the type as `NodePort`, `LoadBalancer`, or `ExternalName`.

== Deployments

A Kubernetes https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[deployment^] is one or more pods which are related to each other and often represent a “service” to a larger application being deployed. The application administrator uses deployments to declare the state of their application component and requests that Kubernetes ensures that the state is implemented at all times. This can include several options:

* Pods, which should be deployed, including versions, storage, network, and other resource requests.
* Number of replicas of each pod instance.

The application administrator then uses the deployment as the interface for managing the application. For example, by increasing or decreasing the number of replicas desired, the application can be horizontally scaled in or out. Updating the deployment with a new version of the application pod(s) triggers Kubernetes to remove existing instances and redeploy by using the new version. Conversely, rolling back to a previous version of the deployment causes Kubernetes to revert the pods to the previously specified version and configuration.

== StatefulSets

Deployments specify how to scale pods. When a webserver (which is managed as a Kubernetes deployment) is scaled up, Kubernetes adds more instances of that pod to reach the desired count. However, when a PVC is added to a deployment, the PVC is shared by all the pod replicas. What if each pod needs unique persistent storage?

https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/[StatefulSets^] are a special type of deployment where separate persistent storage is requested along with each replica of the pod(s), so that each pod receives its own volume of storage. To accomplish this, the StatefulSet definition includes a template PVC, which is used to request additional storage resources as the application is scaled out. This is generally used for stateful applications, such as databases.

To accomplish the above, StatefulSets provide unique pod names and network identifiers that are persistent across pod restarts. They also allow ordered operations, including startup, scale-up, upgrades, and deletion.

As the number of pod replicas increase, the number of PVCs also increases. However, scaling down the application does not result in the PVCs being destroyed, because Kubernetes relies on the application administrator to clean up the PVCs to prevent inadvertent data loss.
