---
sidebar: sidebar
permalink: trident-reference/pod-security.html
keywords: psp, pss, scc, pod security, pod security standards, pod security policies, security context contraints
summary: Pod Security Standards
---

= Pod Security Standards (PSS)
:hardbreaks:
:icons: font
:imagesdir: ../media/

Kubernetes Pod Security Standards (PSS) and Pod Security Policies (PSP) define permission levels and restrict the behavior of pods. To provide this customization, Astra Trident enables certain permissions during installation. 

== Pod Security Policies (PSP)

PSS replaces Pod Security Policies (PSP). PSP was deprecated in Kubernetes v1.21 and will be removed in v1.25. For more information, see link:https://kubernetes.io/docs/concepts/security/[Kubernetes: Security].

.PSS permissions
[cols=",,,",options="header",]
|===
|Labels 
|Description 
|Required 
|Default

//row 
|`pod-security.kubernetes.io/enforce: privileged`

 `pod-security.kubernetes.io/enforce-version: <max-version>` 

|Allows the Trident Controller and nodes to be admitted into the install namespace. Do not change the namespace label. 

| Yes

|`enforce: privileged`

`enforce-version: <version of the current cluster or highest version of PSS tested.>``

|===

== Pod Security Standards (PSS)
Because bidirectional mounts are allowed only on privileged containers, the node pod must run as a privileged container. For more information, see link:https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation[Kubernetes: Mount proagation]. 

.PSP permissions
[cols=",",options="header",]
|===
|Permission 
|Description 

//row 
|Host networking

|Required for the iSCSI daemon. 

//row
|Host IPC

|NFS uses interprocess communication (IPC) to communicate with the NSFD. 

//row 
|Host PID

|Required to start `rpc-statd` for NFS. 

//row 
|Capabilities

|`CAP_SYS_ADMIN` is required to mount volumes. 

The default capabilities for the privileged container are:
`CapPrm: 0000003fffffffff`
`CapEff: 0000003fffffffff`

//row 
|`seccomp`

|`seccomp` cannot be enabled in privileged containers; therefore, it can't be enabled in Astra Trident.

//row 
|SELinux

|On OpenShift, SELinux privileged containers are granted Super Privileged Container (`spc_t`) status. On RHEL with `containerd`, SELinux is disabled and grants all containers `spc_t` status. 

Astra Trident does not add `seLinuxOptions` to containers. 

//row 
|DAC

|Privileged containers must be run as root. 

|===

WARNING: Changing the namespace labels can result in pods not being scheduled, an "Error creating: ..." or, "Warning: trident-csi-...". If this happens, check if the namespace label for `privileged` was changed. If so, reinstall Trident.