---
sidebar: sidebar
permalink: trident-reference/pod-security.html
keywords: psp, pss, scc, pod security, pod security standards, pod security policies, security context contraints
summary: Pod Security Standards
---

= Pod Security Standards (PSS)
:hardbreaks:
:icons: font
:imagesdir: ../media/

Kubernetes Pod Security Standards (PSS) and Pod Security Policies (PSP) define permission levels and restrict the behavior of pods. To provide this customization, Astra Trident enables certain permissions during installation. 

== Pod Security Policies (PSP)

PSS replaces Pod Security Policies (PSP). PSP was deprecated in Kubernetes v1.21 and will be removed in v1.25. For more information, see link:https://kubernetes.io/docs/concepts/security/[Kubernetes: Security].

[cols=",,",options="header",]
|===
|Labels 
|Description 
|Default

//row 
|`pod-security.kubernetes.io/enforce: privileged`

 `pod-security.kubernetes.io/enforce-version: <max-version>` 

|Allows the Trident Controller and nodes to be admitted into the install namespace. 

Do not change the namespace label. 

|`enforce: privileged`

`enforce-version: <version of the current cluster or highest version of PSS tested.>``

|===

== Pod Security Standards (PSS)
Because bidirectional mounts are allowed only on privileged containers, the node pod must run as a privileged container. For more information, see link:https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation[Kubernetes: Mount proagation]. 

[cols=",",options="header",]
|===
|Permission 
|Description 

//row 
|Host networking

|Required for the iSCSI daemon. `iscsiadm` manages iSCSI mounts and uses host networking to communicate with the iSCSI daemon.

//row
|Host IPC

|NFS uses interprocess communication (IPC) to communicate with the NFSD. 

//row 
|Host PID

|Required to start `rpc-statd` for NFS. Astra Trident queries host processes to determine if `rpc-statd` is running before mounting NFS volumes

//row 
|Capabilities

|The `SYS_ADMIN` capability is provided as part of the default capabilities for privileged containers. For example, Docker sets these capabilities for privileged containers:
`CapPrm: 0000003fffffffff`
`CapEff: 0000003fffffffff`

//row 
|`seccomp`

|`seccomp` profile is always "Unconfined" in privileged containers; therefore, it cannot be enabled in Astra Trident

//row 
|SELinux

|On OpenShift, privileged containers are run in the `spc_t` ("Super Privileged Container") domain, and unprivileged containers are run in the `container_t` domain. On `containerd`, with `container-selinux` installed, all containers are run in the `spc_t` domain, which effectively disables SELinux.

Astra Trident does not add `seLinuxOptions` to containers. 

//row 
|DAC

|Privileged containers must be run as root. Non-privileged containers can be run as the default user.

|===

WARNING: Changing the namespace labels can result in pods not being scheduled, an "Error creating: ..." or, "Warning: trident-csi-...". If this happens, check if the namespace label for `privileged` was changed. If so, reinstall Trident.