---
sidebar: sidebar
permalink: trident-reference/tridentctl.html
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags
summary: Learn more about tridentctl, a command-line utility that provides simple access to Trident.
---

= `tridentctl` commands and options
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
The https://github.com/NetApp/trident/releases[Trident installer bundle^] includes a command-line utility, `tridentctl`, that provides simple access to Astra Trident. Kubernetes users with sufficient privileges can use it to install Astra Trident as well as to interact with it directly to manage the namespace that contains the Astra Trident pod.

For usage information, run `tridentctl --help`.

The available commands and global options are:
----
Usage:
  tridentctl [command]
----
Available commands:

* `create`: Add a resource to Astra Trident.
* `delete`: Remove one or more resources from Astra Trident.
* `get`: Get one or more resources from Astra Trident.
* `help`: Help about any command.
* `images`: Print a table of the container images Astra Trident needs.
* `import`: Import an existing resource to Astra Trident.
* `install`: Install Astra Trident.
* `logs`: Print the logs from Astra Trident.
* `send`: Send a resource from Astra Trident.
* `uninstall`: Uninstall Astra Trident.
* `update`: Modify a resource in Astra Trident.
* `upgrade`: Upgrade a resource in Astra Trident.
* `version`: Print the version of Astra Trident.

Flags:

* ``-d, --debug`: Debug output.
* ``-h, --help`: Help for `tridentctl`.
* ``-n, --namespace string`: Namespace of Astra Trident deployment.
* ``-o, --output string`: Output format. One of json|yaml|name|wide|ps (default).
* ``-s, --server string`: Address/port of Astra Trident REST interface.
+
CAUTION: Trident REST interface can be configured to listen and serve at 127.0.0.1 (for IPv4) or [::1] (for IPv6) only.

CAUTION: Trident REST interface can be configured to listen and serve at 127.0.0.1 (for IPv4) or [::1] (for IPv6) only.

== `create`

You can use run the `create` command to add a resource to Astra Trident.
----
Usage:
  tridentctl create [option]
----
Available option:
`backend`: Add a backend to Astra Trident.

== `delete`

You can run the `delete` command to remove one or more resources from Astra Trident.
----
Usage:
  tridentctl delete [option]
----
Available options:

* `backend`: Delete one or more storage backends from Astra Trident.
* `snapshot`: Delete one or more volume snapshots from Astra Trident.
* `storageclass`: Delete one or more storage classes from Astra Trident.
* `volume`: Delete one or more storage volumes from Astra Trident.

== `get`

You can run the `get` command to get one or more resources from Astra Trident.
----
Usage:
  tridentctl get [option]
----
Available options:

* `backend`: Get one or more storage backends from Astra Trident.
* `snapshot`: Get one or more snapshots from Astra Trident.
* `storageclass`: Get one or more storage classes from Astra Trident.
* `volume`: Get one or more volumes from Astra Trident.

`volume` flags:
* ``-h, --help`: Help for volumes.
* `--parentOfSubordinate string`: Limit query to subordinate source volume. 
* `--subordinateOf string`: Limit query to subordinates of volume. 

== `images`

You can run the `images` flag to print a table of the container images Astra Trident needs.
----
Usage:
  tridentctl images [flags]
----
Flags:
* ``-h, --help`: Help for images.
* ``-v, --k8s-version string`: Semantic version of Kubernetes cluster.

== `import volume`

You can run the `import volume` command to import an existing volume to Astra Trident.
----
Usage:
  tridentctl import volume <backendName> <volumeName> [flags]
----
Aliases:
`volume, v`

Flags:

* ``-f, --filename string`: Path to YAML or JSON PVC file.
* ``-h, --help`: Help for volume.
* ``--no-manage`: Create PV/PVC only. Don't assume volume lifecycle management.

== `install`

You can run the `install` flags to install Astra Trident.
----
Usage:
  tridentctl install [flags]
----
Flags:

* ``--autosupport-image string`: The container image for Autosupport Telemetry (default "netapp/trident autosupport:20.07.0").
* ``--autosupport-proxy string`: The address/port of a proxy for sending Autosupport Telemetry.
* ``--csi`: Install CSI Trident (override for Kubernetes 1.13 only, requires feature gates).
* ``--enable-node-prep`: Attempt to install required packages on nodes.
* ``--generate-custom-yaml`: Generate YAML files without installing anything.
* ``-h, --help`: Help for install.
* ``--http-request-timeout`: Override the HTTP request timeout for Trident controller’s REST API (default 1m30s).
* ``--image-registry string`: The address/port of an internal image registry.
* ``--k8s-timeout duration`: The timeout for all Kubernetes operations (default 3m0s).
* ``--kubelet-dir string`: The host location of kubelet's internal state (default "/var/lib/kubelet").
* ``--log-format string`: The Astra Trident logging format (text, json) (default "text").
* ``--pv string`: The name of the legacy PV used by Astra Trident, makes sure this doesn't exist (default "trident").
* ``--pvc string`: The name of the legacy PVC used by Astra Trident, makes sure this doesn't exist (default "trident").
* ``--silence-autosupport`: Don't send autosupport bundles to NetApp automatically (default true).
* ``--silent`: Disable most output during installation.
* ``--trident-image string`: The Astra Trident image to install.
* ``--use-custom-yaml`: Use any existing YAML files that exist in setup directory.
* ``--use-ipv6`: Use IPv6 for Astra Trident's communication.

== `logs`

You can run the `logs` flags to print the logs from Astra Trident.
----
Usage:
  tridentctl logs [flags]
----
Flags:

* ``-a, --archive`: Create a support archive with all logs unless otherwise specified.
* ``-h, --help`: Help for logs.
* ``-l, --log string`: Astra Trident log to display. One of trident|auto|trident-operator|all (default "auto").
* ``--node string`: The Kubernetes node name from which to gather node pod logs.
* ``-p, --previous`: Get the logs for the previous container instance if it exists.
* ``--sidecars`: Get the logs for the sidecar containers.

== `send`

You can run the `send` command to send a resource from Astra Trident.
----
Usage:
  tridentctl send [option]
----
Available option:
`autosupport`: Send an Autosupport archive to NetApp.

== `uninstall`

You can run the `uninstall` flags to uninstall Astra Trident.
----
Usage:
  tridentctl uninstall [flags]
----
Flags:
* `-h, --help`: Help for uninstall.
* `--silent`: Disable most output during uninstallation.

== `update`

You can run the `update` commands to modify a resource in Astra Trident.
----
Usage:
  tridentctl update [option]
----
Available options:
`backend`: Update a backend in Astra Trident.

== `upgrade`

You can run the `upgrade` commands to upgrade a resource in Astra Trident.
----
Usage:
tridentctl upgrade [option]
----
Available option:
`volume`: Upgrade one or more persistent volumes from NFS/iSCSI to CSI.

== `version`

You can run the `version` flags to print the version of `tridentctl` and the running Trident service.
----
Usage:
  tridentctl version [flags]
----
Flags:
* `--client`: Client version only (no server required).
* `-h, --help`: Help for version.
