---
sidebar: sidebar
permalink: trident-reference/trident-cl.html
keywords: command-line, options, logging, kubernetes, docker, ports
summary: Trident exposes several command-line options and communicates over certain ports.
---

= trident Command-line options
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Trident exposes several command-line options. You can modify them in your deployment.

== Logging

* `-debug`: Enables debugging output.
* `-loglevel <level>`: Sets the logging level (debug, info, warn, error, fatal). Defaults to info.

== Kubernetes

* `-k8s_pod`: Use this option or `-k8s_api_server` to enable Kubernetes support. Setting this causes Trident to use its containing pod's Kubernetes service account credentials to contact the API server. This only works when Trident runs as a pod in a Kubernetes cluster with service accounts enabled.
* `-k8s_api_server <insecure-address:insecure-port>`: Use this option or `-k8s_pod` to enable Kubernetes support. When specified, Trident connects to the Kubernetes API server using the provided insecure address and port. This allows Trident to be deployed outside of a pod; however, it only supports insecure connections to the API server. To connect securely, deploy Trident in a pod with the `-k8s_pod` option.
* `-k8s_config_path <file>`: Path to a KubeConfig file.

== Docker

* `-volume_driver <name>`: Driver name used when registering the Docker plugin. Defaults to 'netapp'.
* `-driver_port <port-number>`: Listen on this port rather than a UNIX domain socket.
* `-config <file>`: Path to a backend configuration file.

== REST

* `-address <ip-or-host>`: Specifies the address on which Trident's REST server should listen. Defaults to localhost. When listening on localhost and running inside a Kubernetes pod, the REST interface isn't directly accessible from outside the pod. Use -address "" to make the REST interface accessible from the pod IP address.
* `-port <port-number>`: Specifies the port on which Trident's REST server should listen. Defaults to 8000.
* `-rest`: Enables the REST interface. Defaults to true.

== Ports

Trident communicates over the following ports:

[cols="2,4" options="header"]
|===
|Port |Purpose
|8443 |Backchannel HTTPS
|8001 |Prometheus metrics endpoint
|8000 |Trident REST server
|17546 |Liveness/readiness probe port used by Trident daemonset pods
|===

[NOTE]
The liveness/readiness probe port can be changed during installation time using the `--probe-port` flag. It is important to make sure this port isn't being used by another process on the worker nodes.
